import type { Question } from "@/types/question";

/** 양자택일 질문 — 모든 카테고리 혼합 */
export const CHOICE_QUESTIONS: Question[] = [
  { id: 2001, category: "choice", content: "산 vs 바다", answerType: "choice", optionA: "산 ⛰️", optionB: "바다 🏖️" },
  { id: 2002, category: "choice", content: "치킨 vs 피자", answerType: "choice", optionA: "치킨 🍗", optionB: "피자 🍕" },
  { id: 2003, category: "choice", content: "아침형 vs 저녁형", answerType: "choice", optionA: "아침형 🌅", optionB: "저녁형 🌙" },
  { id: 2004, category: "choice", content: "영화관 vs 넷플릭스", answerType: "choice", optionA: "영화관 🎬", optionB: "넷플릭스 📺" },
  { id: 2005, category: "choice", content: "여름 vs 겨울", answerType: "choice", optionA: "여름 ☀️", optionB: "겨울 ❄️" },
  { id: 2006, category: "choice", content: "전화 vs 문자", answerType: "choice", optionA: "전화 📞", optionB: "문자 💬" },
  { id: 2007, category: "choice", content: "계획적 vs 즉흥적", answerType: "choice", optionA: "계획적 📋", optionB: "즉흥적 🎲" },
  { id: 2008, category: "choice", content: "한식 vs 양식", answerType: "choice", optionA: "한식 🍚", optionB: "양식 🍝" },
  { id: 2009, category: "choice", content: "집 데이트 vs 밖 데이트", answerType: "choice", optionA: "집 🏠", optionB: "밖 🌳" },
  { id: 2010, category: "choice", content: "사진 찍기 vs 찍히기", answerType: "choice", optionA: "찍기 📸", optionB: "찍히기 🤳" },
  { id: 2011, category: "choice", content: "카페 vs 술집", answerType: "choice", optionA: "카페 ☕", optionB: "술집 🍺" },
  { id: 2012, category: "choice", content: "강아지 vs 고양이", answerType: "choice", optionA: "강아지 🐶", optionB: "고양이 🐱" },
  { id: 2013, category: "choice", content: "돈 vs 시간", answerType: "choice", optionA: "돈 💰", optionB: "시간 ⏰" },
  { id: 2014, category: "choice", content: "먼저 사과 vs 기다리기", answerType: "choice", optionA: "먼저 사과 🙏", optionB: "기다리기 ⏳" },
  { id: 2015, category: "choice", content: "매운 거 vs 안 매운 거", answerType: "choice", optionA: "매운 거 🌶️", optionB: "안 매운 거 🍙" },
  { id: 2016, category: "choice", content: "텍스트 vs 음성메시지", answerType: "choice", optionA: "텍스트 ⌨️", optionB: "음성 🎙️" },
  { id: 2017, category: "choice", content: "일찍 도착 vs 딱 맞춰 도착", answerType: "choice", optionA: "일찍 ⏰", optionB: "딱 맞춰 🎯" },
  { id: 2018, category: "choice", content: "새 맛집 도전 vs 단골집", answerType: "choice", optionA: "새 맛집 🆕", optionB: "단골집 🏪" },
  { id: 2019, category: "choice", content: "드라마 vs 예능", answerType: "choice", optionA: "드라마 🎭", optionB: "예능 😆" },
  { id: 2020, category: "choice", content: "운동 vs 낮잠", answerType: "choice", optionA: "운동 💪", optionB: "낮잠 😴" },
  { id: 2021, category: "choice", content: "비 오는 날 vs 눈 오는 날", answerType: "choice", optionA: "비 🌧️", optionB: "눈 ❄️" },
  { id: 2022, category: "choice", content: "서프라이즈 vs 미리 알려주기", answerType: "choice", optionA: "서프라이즈 🎉", optionB: "미리 알려줘 📢" },
  { id: 2023, category: "choice", content: "도시 vs 시골", answerType: "choice", optionA: "도시 🏙️", optionB: "시골 🌾" },
  { id: 2024, category: "choice", content: "요리해주기 vs 요리받기", answerType: "choice", optionA: "해주기 👨‍🍳", optionB: "받기 😋" },
  { id: 2025, category: "choice", content: "같이 운동 vs 같이 게임", answerType: "choice", optionA: "운동 🏃", optionB: "게임 🎮" },
  { id: 2026, category: "choice", content: "단 거 vs 짠 거", answerType: "choice", optionA: "단 거 🍰", optionB: "짠 거 🧂" },
  { id: 2027, category: "choice", content: "연락 자주 vs 가끔 깊게", answerType: "choice", optionA: "자주 📱", optionB: "가끔 깊게 💎" },
  { id: 2028, category: "choice", content: "혼자만의 시간 vs 항상 같이", answerType: "choice", optionA: "혼자 시간 🧘", optionB: "항상 같이 👫" },
  { id: 2029, category: "choice", content: "빈티지 vs 모던", answerType: "choice", optionA: "빈티지 🪵", optionB: "모던 🏢" },
  { id: 2030, category: "choice", content: "편지 vs 선물", answerType: "choice", optionA: "편지 💌", optionB: "선물 🎁" },
  { id: 2031, category: "choice", content: "아이스 아메리카노 vs 따뜻한 라떼", answerType: "choice", optionA: "아아 🧊", optionB: "따라 ☕" },
  { id: 2032, category: "choice", content: "장거리 여행 vs 근교 당일치기", answerType: "choice", optionA: "장거리 ✈️", optionB: "당일치기 🚗" },
  { id: 2033, category: "choice", content: "책 vs 유튜브", answerType: "choice", optionA: "책 📚", optionB: "유튜브 📱" },
  { id: 2034, category: "choice", content: "놀이공원 vs 워터파크", answerType: "choice", optionA: "놀이공원 🎢", optionB: "워터파크 🏊" },
  { id: 2035, category: "choice", content: "한강 치맥 vs 루프탑 바", answerType: "choice", optionA: "한강 치맥 🍻", optionB: "루프탑 🌃" },
  { id: 2036, category: "choice", content: "이모티콘 많이 vs 담백하게", answerType: "choice", optionA: "이모티콘 😄🥰🎉", optionB: "담백하게 ." },
  { id: 2037, category: "choice", content: "우리 사진 SNS 공개 vs 비공개", answerType: "choice", optionA: "공개 📸", optionB: "비공개 🔒" },
  { id: 2038, category: "choice", content: "커플룩 vs 각자 스타일", answerType: "choice", optionA: "커플룩 👕👕", optionB: "각자 스타일 👗👔" },
  { id: 2039, category: "choice", content: "새벽 감성 대화 vs 낮에 실속 대화", answerType: "choice", optionA: "새벽 감성 🌙", optionB: "낮에 실속 ☀️" },
  { id: 2040, category: "choice", content: "기념일 꼭 챙기기 vs 편하게", answerType: "choice", optionA: "꼭 챙기기 📅", optionB: "편하게 😌" },
];
