import type { Question } from "@/types/question";

/** 추가 양자택일 질문 Part 3 (ID 2281-2400) */
export const CHOICE_EXTRA_3: Question[] = [
  // --- 음식 디테일 (2281-2300) ---
  { id: 2281, category: "choice", content: "탕수육 부먹 vs 찍먹", answerType: "choice", optionA: "부먹 🥘", optionB: "찍먹 🥢" },
  { id: 2282, category: "choice", content: "소주 vs 맥주", answerType: "choice", optionA: "소주 🍶", optionB: "맥주 🍺" },
  { id: 2283, category: "choice", content: "핫도그 vs 토스트", answerType: "choice", optionA: "핫도그 🌭", optionB: "토스트 🍞" },
  { id: 2284, category: "choice", content: "치즈 좋아 vs 치즈 별로", answerType: "choice", optionA: "좋아 🧀", optionB: "별로 🙅" },
  { id: 2285, category: "choice", content: "곱창 vs 대창", answerType: "choice", optionA: "곱창 🫕", optionB: "대창 🍢" },
  { id: 2286, category: "choice", content: "스테이크 레어 vs 웰던", answerType: "choice", optionA: "레어 🩸", optionB: "웰던 🔥" },
  { id: 2287, category: "choice", content: "초코 vs 바닐라", answerType: "choice", optionA: "초코 🍫", optionB: "바닐라 🍦" },
  { id: 2288, category: "choice", content: "딸기 vs 포도", answerType: "choice", optionA: "딸기 🍓", optionB: "포도 🍇" },
  { id: 2289, category: "choice", content: "찐만두 vs 군만두", answerType: "choice", optionA: "찐만두 🥟", optionB: "군만두 🔥" },
  { id: 2290, category: "choice", content: "크로플 vs 와플", answerType: "choice", optionA: "크로플 🥐", optionB: "와플 🧇" },
  { id: 2291, category: "choice", content: "밤 vs 고구마", answerType: "choice", optionA: "밤 🌰", optionB: "고구마 🍠" },
  { id: 2292, category: "choice", content: "된장 vs 고추장", answerType: "choice", optionA: "된장 🫘", optionB: "고추장 🌶️" },
  { id: 2293, category: "choice", content: "뷔페 vs 코스요리", answerType: "choice", optionA: "뷔페 🍽️", optionB: "코스요리 🍷" },
  { id: 2294, category: "choice", content: "수박 vs 참외", answerType: "choice", optionA: "수박 🍉", optionB: "참외 🍈" },
  { id: 2295, category: "choice", content: "떡국 vs 만둣국", answerType: "choice", optionA: "떡국 🥣", optionB: "만둣국 🥟" },
  { id: 2296, category: "choice", content: "감자튀김 vs 치즈스틱", answerType: "choice", optionA: "감자튀김 🍟", optionB: "치즈스틱 🧀" },
  { id: 2297, category: "choice", content: "녹차 vs 홍차", answerType: "choice", optionA: "녹차 🍵", optionB: "홍차 🫖" },
  { id: 2298, category: "choice", content: "편의점 도시락 vs 김밥천국", answerType: "choice", optionA: "편의점 🏪", optionB: "김밥천국 🍙" },
  { id: 2299, category: "choice", content: "쫄면 vs 냉면", answerType: "choice", optionA: "쫄면 🍜", optionB: "냉면 🥶" },
  { id: 2300, category: "choice", content: "치킨 양념 vs 후라이드", answerType: "choice", optionA: "양념 🍗", optionB: "후라이드 🍗" },
  // --- 커플 상황극 (2301-2320) ---
  { id: 2301, category: "choice", content: "깜짝 선물 vs 같이 고르기", answerType: "choice", optionA: "깜짝 🎁", optionB: "같이 고르기 🛍️" },
  { id: 2302, category: "choice", content: "힘들 때 안아주기 vs 들어주기", answerType: "choice", optionA: "안아주기 🫂", optionB: "들어주기 👂" },
  { id: 2303, category: "choice", content: "데이트 비용 나누기 vs 번갈아 쏘기", answerType: "choice", optionA: "나누기 ➗", optionB: "번갈아 🔄" },
  { id: 2304, category: "choice", content: "같이 자기 vs 따로 자기", answerType: "choice", optionA: "같이 자기 🛏️", optionB: "따로 자기 🛏️🛏️" },
  { id: 2305, category: "choice", content: "아침에 깨워주기 vs 자게 두기", answerType: "choice", optionA: "깨워주기 ⏰", optionB: "자게 두기 😴" },
  { id: 2306, category: "choice", content: "요리 같이 vs 설거지 같이", answerType: "choice", optionA: "요리 같이 🍳", optionB: "설거지 같이 🧽" },
  { id: 2307, category: "choice", content: "운동 코치 해주기 vs 응원하기", answerType: "choice", optionA: "코치 🏋️", optionB: "응원 📣" },
  { id: 2308, category: "choice", content: "서로 일기 공유 vs 비밀 유지", answerType: "choice", optionA: "공유 📖", optionB: "비밀 🔐" },
  { id: 2309, category: "choice", content: "싸운 뒤 바로 대화 vs 시간 갖기", answerType: "choice", optionA: "바로 대화 💬", optionB: "시간 갖기 ⏳" },
  { id: 2310, category: "choice", content: "매일 영상통화 vs 주1회 만남", answerType: "choice", optionA: "매일 영통 📹", optionB: "주1회 만남 💑" },
  { id: 2311, category: "choice", content: "서프라이즈 편지 vs 서프라이즈 꽃", answerType: "choice", optionA: "편지 💌", optionB: "꽃 💐" },
  { id: 2312, category: "choice", content: "노래 불러주기 vs 춤 춰주기", answerType: "choice", optionA: "노래 🎵", optionB: "춤 💃" },
  { id: 2313, category: "choice", content: "함께 공부 vs 함께 청소", answerType: "choice", optionA: "함께 공부 📚", optionB: "함께 청소 🧹" },
  { id: 2314, category: "choice", content: "아플 때 간호 vs 아플 때 맛있는거", answerType: "choice", optionA: "간호 🩺", optionB: "맛있는거 🍲" },
  { id: 2315, category: "choice", content: "커플 브이로그 vs 커플 사진첩", answerType: "choice", optionA: "브이로그 📹", optionB: "사진첩 📸" },
  { id: 2316, category: "choice", content: "같은 옷 입기 vs 같은 향수 뿌리기", answerType: "choice", optionA: "같은 옷 👕", optionB: "같은 향수 🌹" },
  { id: 2317, category: "choice", content: "아침 모닝콜 vs 저녁 잘자 콜", answerType: "choice", optionA: "모닝콜 🌅", optionB: "잘자 콜 🌙" },
  { id: 2318, category: "choice", content: "셀카 vs 타이머 사진", answerType: "choice", optionA: "셀카 🤳", optionB: "타이머 📸" },
  { id: 2319, category: "choice", content: "함께 목표 세우기 vs 각자 응원", answerType: "choice", optionA: "함께 목표 🎯", optionB: "각자 응원 📣" },
  { id: 2320, category: "choice", content: "서로 옷 골라주기 vs 각자 입기", answerType: "choice", optionA: "골라주기 👗", optionB: "각자 입기 🧑" },
  // --- 이것저것 디테일 (2321-2340) ---
  { id: 2321, category: "choice", content: "아이폰 vs 갤럭시", answerType: "choice", optionA: "아이폰 🍎", optionB: "갤럭시 📱" },
  { id: 2322, category: "choice", content: "맥북 vs 윈도우", answerType: "choice", optionA: "맥북 💻", optionB: "윈도우 🖥️" },
  { id: 2323, category: "choice", content: "유튜브 vs 넷플릭스", answerType: "choice", optionA: "유튜브 📺", optionB: "넷플릭스 🎬" },
  { id: 2324, category: "choice", content: "트위터 vs 인스타", answerType: "choice", optionA: "트위터 🐦", optionB: "인스타 📸" },
  { id: 2325, category: "choice", content: "이마트 vs 코스트코", answerType: "choice", optionA: "이마트 🏬", optionB: "코스트코 🛒" },
  { id: 2326, category: "choice", content: "올리브영 vs 다이소", answerType: "choice", optionA: "올리브영 💚", optionB: "다이소 🟡" },
  { id: 2327, category: "choice", content: "우산 vs 비 맞기", answerType: "choice", optionA: "우산 ☂️", optionB: "비 맞기 🌧️" },
  { id: 2328, category: "choice", content: "엘리베이터 vs 에스컬레이터", answerType: "choice", optionA: "엘리베이터 🛗", optionB: "에스컬레이터 🪜" },
  { id: 2329, category: "choice", content: "사탕 vs 껌", answerType: "choice", optionA: "사탕 🍬", optionB: "껌 🫧" },
  { id: 2330, category: "choice", content: "저녁 약속 vs 점심 약속", answerType: "choice", optionA: "저녁 🌙", optionB: "점심 ☀️" },
  { id: 2331, category: "choice", content: "노트 vs 태블릿", answerType: "choice", optionA: "노트 📓", optionB: "태블릿 📱" },
  { id: 2332, category: "choice", content: "카톡 vs 인스타 DM", answerType: "choice", optionA: "카톡 💛", optionB: "DM 💜" },
  { id: 2333, category: "choice", content: "현관문 비번 vs 열쇠", answerType: "choice", optionA: "비번 🔢", optionB: "열쇠 🔑" },
  { id: 2334, category: "choice", content: "계단 vs 에스컬레이터", answerType: "choice", optionA: "계단 🪜", optionB: "에스컬레이터 ➡️" },
  { id: 2335, category: "choice", content: "손편지 vs 이메일", answerType: "choice", optionA: "손편지 ✉️", optionB: "이메일 📧" },
  { id: 2336, category: "choice", content: "스티커 사진 vs 셀프 사진", answerType: "choice", optionA: "스티커 📷", optionB: "셀프 🤳" },
  { id: 2337, category: "choice", content: "라디오 vs 팟캐스트", answerType: "choice", optionA: "라디오 📻", optionB: "팟캐스트 🎙️" },
  { id: 2338, category: "choice", content: "택시 vs 버스", answerType: "choice", optionA: "택시 🚕", optionB: "버스 🚌" },
  { id: 2339, category: "choice", content: "자판기 커피 vs 편의점 커피", answerType: "choice", optionA: "자판기 ☕", optionB: "편의점 🏪" },
  { id: 2340, category: "choice", content: "종이 영수증 vs 전자 영수증", answerType: "choice", optionA: "종이 🧾", optionB: "전자 📱" },
  // --- 감정/분위기 (2341-2360) ---
  { id: 2341, category: "choice", content: "감동 영화 vs 웃긴 영화", answerType: "choice", optionA: "감동 😭", optionB: "웃긴 😂" },
  { id: 2342, category: "choice", content: "설레는 것 vs 편안한 것", answerType: "choice", optionA: "설레는 💓", optionB: "편안한 🧸" },
  { id: 2343, category: "choice", content: "새 시작 vs 완벽한 마무리", answerType: "choice", optionA: "새 시작 🌱", optionB: "완벽 마무리 🏁" },
  { id: 2344, category: "choice", content: "조용한 카페 vs 활기찬 카페", answerType: "choice", optionA: "조용한 🤫", optionB: "활기찬 🎉" },
  { id: 2345, category: "choice", content: "감성 사진 vs 재밌는 사진", answerType: "choice", optionA: "감성 🌅", optionB: "재밌는 😝" },
  { id: 2346, category: "choice", content: "슬플 때 음악 vs 슬플 때 산책", answerType: "choice", optionA: "음악 🎧", optionB: "산책 🚶" },
  { id: 2347, category: "choice", content: "집중 모드 vs 멀티태스킹", answerType: "choice", optionA: "집중 🎯", optionB: "멀티 🔀" },
  { id: 2348, category: "choice", content: "향수에 젖기 vs 새로움 찾기", answerType: "choice", optionA: "향수 📼", optionB: "새로움 🆕" },
  { id: 2349, category: "choice", content: "혼자 힐링 vs 함께 힐링", answerType: "choice", optionA: "혼자 🧘", optionB: "함께 👫" },
  { id: 2350, category: "choice", content: "크게 웃기 vs 조용히 미소", answerType: "choice", optionA: "크게 😆", optionB: "조용히 😊" },
  { id: 2351, category: "choice", content: "긍정 에너지 vs 현실 조언", answerType: "choice", optionA: "긍정 🌟", optionB: "현실 📊" },
  { id: 2352, category: "choice", content: "떠들기 vs 조용히 있기", answerType: "choice", optionA: "떠들기 🗣️", optionB: "조용히 🤐" },
  { id: 2353, category: "choice", content: "사람 많은 곳 vs 한적한 곳", answerType: "choice", optionA: "사람 많은 🏙️", optionB: "한적한 🏞️" },
  { id: 2354, category: "choice", content: "눈물 참기 vs 마음껏 울기", answerType: "choice", optionA: "참기 😤", optionB: "울기 😭" },
  { id: 2355, category: "choice", content: "고백 듣기 vs 고백 하기", answerType: "choice", optionA: "듣기 👂", optionB: "하기 💌" },
  { id: 2356, category: "choice", content: "아날로그 감성 vs 디지털 감성", answerType: "choice", optionA: "아날로그 📼", optionB: "디지털 💻" },
  { id: 2357, category: "choice", content: "자연 소리 vs 도시 소리", answerType: "choice", optionA: "자연 🦗", optionB: "도시 🏙️" },
  { id: 2358, category: "choice", content: "별 보기 vs 달 보기", answerType: "choice", optionA: "별 ⭐", optionB: "달 🌙" },
  { id: 2359, category: "choice", content: "느린 아침 vs 바쁜 아침", answerType: "choice", optionA: "느린 🐢", optionB: "바쁜 🐇" },
  { id: 2360, category: "choice", content: "우연한 행복 vs 계획한 행복", answerType: "choice", optionA: "우연 🍀", optionB: "계획 📋" },
  // --- 미래/꿈 (2361-2380) ---
  { id: 2361, category: "choice", content: "시골 카페 운영 vs 도시 회사원", answerType: "choice", optionA: "시골 카페 ☕", optionB: "도시 회사 🏢" },
  { id: 2362, category: "choice", content: "세계일주 vs 한곳 깊이 살기", answerType: "choice", optionA: "세계일주 🌍", optionB: "한곳 깊이 🏡" },
  { id: 2363, category: "choice", content: "유명해지기 vs 평범하게 살기", answerType: "choice", optionA: "유명 ⭐", optionB: "평범 😌" },
  { id: 2364, category: "choice", content: "재택근무 vs 출근", answerType: "choice", optionA: "재택 🏠", optionB: "출근 🏢" },
  { id: 2365, category: "choice", content: "좋아하는 일 vs 돈 되는 일", answerType: "choice", optionA: "좋아하는 ❤️", optionB: "돈 되는 💰" },
  { id: 2366, category: "choice", content: "큰 집 vs 좋은 위치", answerType: "choice", optionA: "큰 집 🏡", optionB: "좋은 위치 📍" },
  { id: 2367, category: "choice", content: "아이 1명 vs 아이 2명 이상", answerType: "choice", optionA: "1명 👶", optionB: "2명 이상 👶👶" },
  { id: 2368, category: "choice", content: "결혼식 크게 vs 결혼식 작게", answerType: "choice", optionA: "크게 🎊", optionB: "작게 💒" },
  { id: 2369, category: "choice", content: "반려동물 키우기 vs 여행 많이 다니기", answerType: "choice", optionA: "반려동물 🐾", optionB: "여행 ✈️" },
  { id: 2370, category: "choice", content: "주말 농장 vs 주말 운동", answerType: "choice", optionA: "농장 🌿", optionB: "운동 🏃" },
  { id: 2371, category: "choice", content: "자영업 vs 직장인", answerType: "choice", optionA: "자영업 🏪", optionB: "직장인 💼" },
  { id: 2372, category: "choice", content: "대학원 vs 취업", answerType: "choice", optionA: "대학원 🎓", optionB: "취업 💼" },
  { id: 2373, category: "choice", content: "해외 생활 vs 국내 정착", answerType: "choice", optionA: "해외 🌏", optionB: "국내 🇰🇷" },
  { id: 2374, category: "choice", content: "부자 동네 작은 집 vs 보통 동네 큰 집", answerType: "choice", optionA: "작은 집 🏠", optionB: "큰 집 🏡" },
  { id: 2375, category: "choice", content: "은퇴 후 취미 vs 은퇴 후 여행", answerType: "choice", optionA: "취미 🎨", optionB: "여행 🧳" },
  { id: 2376, category: "choice", content: "요리사 되기 vs 사진작가 되기", answerType: "choice", optionA: "요리사 👨‍🍳", optionB: "사진작가 📸" },
  { id: 2377, category: "choice", content: "유튜버 vs 작가", answerType: "choice", optionA: "유튜버 📹", optionB: "작가 ✍️" },
  { id: 2378, category: "choice", content: "해변가 집 vs 산속 집", answerType: "choice", optionA: "해변가 🏖️", optionB: "산속 🏔️" },
  { id: 2379, category: "choice", content: "빠른 승진 vs 워라밸", answerType: "choice", optionA: "빠른 승진 📈", optionB: "워라밸 ⚖️" },
  { id: 2380, category: "choice", content: "많은 경험 vs 깊은 전문성", answerType: "choice", optionA: "많은 경험 🌈", optionB: "깊은 전문 🔬" },
  // --- 잡학/재미 (2381-2400) ---
  { id: 2381, category: "choice", content: "좀비 아포 vs 외계인 침공", answerType: "choice", optionA: "좀비 🧟", optionB: "외계인 👽" },
  { id: 2382, category: "choice", content: "용 타기 vs 유니콘 타기", answerType: "choice", optionA: "용 🐉", optionB: "유니콘 🦄" },
  { id: 2383, category: "choice", content: "마법 지팡이 vs 타임머신", answerType: "choice", optionA: "지팡이 🪄", optionB: "타임머신 ⏰" },
  { id: 2384, category: "choice", content: "닌자 vs 해적", answerType: "choice", optionA: "닌자 🥷", optionB: "해적 🏴‍☠️" },
  { id: 2385, category: "choice", content: "화성 이주 vs 심해 탐험", answerType: "choice", optionA: "화성 🔴", optionB: "심해 🌊" },
  { id: 2386, category: "choice", content: "투명 망토 vs 날으는 양탄자", answerType: "choice", optionA: "투명 망토 🧥", optionB: "양탄자 🪄" },
  { id: 2387, category: "choice", content: "동화 속 vs SF 속", answerType: "choice", optionA: "동화 속 🏰", optionB: "SF 속 🚀" },
  { id: 2388, category: "choice", content: "1000만 구독자 vs 1000만원 월급", answerType: "choice", optionA: "구독자 📹", optionB: "월급 💰" },
  { id: 2389, category: "choice", content: "하루 강아지 vs 하루 고양이", answerType: "choice", optionA: "강아지 되기 🐕", optionB: "고양이 되기 🐈" },
  { id: 2390, category: "choice", content: "무한 피자 vs 무한 초밥", answerType: "choice", optionA: "무한 피자 🍕", optionB: "무한 초밥 🍣" },
  { id: 2391, category: "choice", content: "다음 생 한국 vs 다음 생 외국", answerType: "choice", optionA: "한국 🇰🇷", optionB: "외국 🌍" },
  { id: 2392, category: "choice", content: "마법학교 vs 우주학교", answerType: "choice", optionA: "마법학교 🧙", optionB: "우주학교 🚀" },
  { id: 2393, category: "choice", content: "10년 젊어지기 vs 10억 받기", answerType: "choice", optionA: "10년 젊게 🌟", optionB: "10억 💰" },
  { id: 2394, category: "choice", content: "공룡 시대 vs 중세 시대", answerType: "choice", optionA: "공룡 시대 🦕", optionB: "중세 시대 ⚔️" },
  { id: 2395, category: "choice", content: "거인 되기 vs 요정 되기", answerType: "choice", optionA: "거인 🦶", optionB: "요정 🧚" },
  { id: 2396, category: "choice", content: "슈퍼히어로 vs 디즈니 공주/왕자", answerType: "choice", optionA: "히어로 🦸", optionB: "공주/왕자 👸" },
  { id: 2397, category: "choice", content: "지니 소원 1개 vs 작은 행운 매일", answerType: "choice", optionA: "소원 1개 🧞", optionB: "매일 행운 🍀" },
  { id: 2398, category: "choice", content: "인어 되기 vs 새 되기", answerType: "choice", optionA: "인어 🧜", optionB: "새 🦅" },
  { id: 2399, category: "choice", content: "게임 세계 살기 vs 만화 세계 살기", answerType: "choice", optionA: "게임 세계 🎮", optionB: "만화 세계 📖" },
  { id: 2400, category: "choice", content: "어제로 돌아가기 vs 내일로 건너뛰기", answerType: "choice", optionA: "어제 ⏪", optionB: "내일 ⏩" },
];
