import type { Question } from "@/types/question";

/** 추가 양자택일 질문 Part 2 (ID 2161-2280) */
export const CHOICE_EXTRA_2: Question[] = [
  // --- 여행/이동 (2161-2180) ---
  { id: 2161, category: "choice", content: "호텔 vs 에어비앤비", answerType: "choice", optionA: "호텔 🏨", optionB: "에어비앤비 🏡" },
  { id: 2162, category: "choice", content: "비행기 vs KTX", answerType: "choice", optionA: "비행기 ✈️", optionB: "KTX 🚄" },
  { id: 2163, category: "choice", content: "계획 여행 vs 무계획 여행", answerType: "choice", optionA: "계획 📋", optionB: "무계획 🗺️" },
  { id: 2164, category: "choice", content: "맛집 투어 vs 관광지 투어", answerType: "choice", optionA: "맛집 투어 🍴", optionB: "관광지 📸" },
  { id: 2165, category: "choice", content: "해외 여행 vs 국내 여행", answerType: "choice", optionA: "해외 🌏", optionB: "국내 🇰🇷" },
  { id: 2166, category: "choice", content: "아침 일찍 출발 vs 느긋하게 출발", answerType: "choice", optionA: "일찍 ⏰", optionB: "느긋하게 😌" },
  { id: 2167, category: "choice", content: "배낭여행 vs 럭셔리 여행", answerType: "choice", optionA: "배낭 🎒", optionB: "럭셔리 👑" },
  { id: 2168, category: "choice", content: "따뜻한 나라 vs 추운 나라", answerType: "choice", optionA: "따뜻한 ☀️", optionB: "추운 ❄️" },
  { id: 2169, category: "choice", content: "섬 여행 vs 산 여행", answerType: "choice", optionA: "섬 🏝️", optionB: "산 🏔️" },
  { id: 2170, category: "choice", content: "혼자 여행 vs 단체 여행", answerType: "choice", optionA: "혼자 🧳", optionB: "단체 👥" },
  { id: 2171, category: "choice", content: "새벽 비행 vs 밤 비행", answerType: "choice", optionA: "새벽 🌅", optionB: "밤 🌙" },
  { id: 2172, category: "choice", content: "기차 여행 vs 자동차 여행", answerType: "choice", optionA: "기차 🚂", optionB: "자동차 🚗" },
  { id: 2173, category: "choice", content: "리조트 vs 펜션", answerType: "choice", optionA: "리조트 🏖️", optionB: "펜션 🏡" },
  { id: 2174, category: "choice", content: "짧은 여행 자주 vs 긴 여행 가끔", answerType: "choice", optionA: "짧게 자주 🔄", optionB: "길게 가끔 📅" },
  { id: 2175, category: "choice", content: "시장 구경 vs 백화점 구경", answerType: "choice", optionA: "시장 🏪", optionB: "백화점 🏬" },
  { id: 2176, category: "choice", content: "유명 맛집 줄서기 vs 근처 아무 데나", answerType: "choice", optionA: "줄서기 🧍", optionB: "아무 데나 🚶" },
  { id: 2177, category: "choice", content: "도보 여행 vs 렌터카 여행", answerType: "choice", optionA: "도보 🚶", optionB: "렌터카 🚗" },
  { id: 2178, category: "choice", content: "여행 사진 많이 vs 눈으로 즐기기", answerType: "choice", optionA: "사진 많이 📷", optionB: "눈으로 👀" },
  { id: 2179, category: "choice", content: "현지 음식 vs 한식 찾기", answerType: "choice", optionA: "현지 음식 🍜", optionB: "한식 찾기 🍚" },
  { id: 2180, category: "choice", content: "숙소에서 쉬기 vs 밤까지 돌아다니기", answerType: "choice", optionA: "숙소 쉬기 🛏️", optionB: "밤까지 🌃" },
  // --- 패션/스타일 (2181-2200) ---
  { id: 2181, category: "choice", content: "운동화 vs 구두", answerType: "choice", optionA: "운동화 👟", optionB: "구두 👠" },
  { id: 2182, category: "choice", content: "캐주얼 vs 포멀", answerType: "choice", optionA: "캐주얼 👕", optionB: "포멀 👔" },
  { id: 2183, category: "choice", content: "검은색 vs 흰색", answerType: "choice", optionA: "검은색 🖤", optionB: "흰색 🤍" },
  { id: 2184, category: "choice", content: "긴머리 vs 짧은머리", answerType: "choice", optionA: "긴머리 💇‍♀️", optionB: "짧은머리 💇" },
  { id: 2185, category: "choice", content: "모자 vs 선글라스", answerType: "choice", optionA: "모자 🧢", optionB: "선글라스 🕶️" },
  { id: 2186, category: "choice", content: "따뜻한 색 vs 차가운 색", answerType: "choice", optionA: "따뜻한 색 🧡", optionB: "차가운 색 💙" },
  { id: 2187, category: "choice", content: "무지 vs 패턴", answerType: "choice", optionA: "무지 ⬜", optionB: "패턴 🔲" },
  { id: 2188, category: "choice", content: "편한 옷 vs 예쁜 옷", answerType: "choice", optionA: "편한 옷 🩳", optionB: "예쁜 옷 👗" },
  { id: 2189, category: "choice", content: "향기 진한 vs 향기 은은", answerType: "choice", optionA: "진한 💐", optionB: "은은 🌿" },
  { id: 2190, category: "choice", content: "골드 vs 실버", answerType: "choice", optionA: "골드 🥇", optionB: "실버 🥈" },
  { id: 2191, category: "choice", content: "맨투맨 vs 후드티", answerType: "choice", optionA: "맨투맨 👕", optionB: "후드티 🧥" },
  { id: 2192, category: "choice", content: "청바지 vs 면바지", answerType: "choice", optionA: "청바지 👖", optionB: "면바지 🩳" },
  { id: 2193, category: "choice", content: "가방 큰 거 vs 가방 작은 거", answerType: "choice", optionA: "큰 가방 🎒", optionB: "작은 가방 👛" },
  { id: 2194, category: "choice", content: "네일 화려 vs 네일 깔끔", answerType: "choice", optionA: "화려 💅", optionB: "깔끔 ✨" },
  { id: 2195, category: "choice", content: "안경 vs 렌즈", answerType: "choice", optionA: "안경 👓", optionB: "렌즈 👁️" },
  { id: 2196, category: "choice", content: "시계 vs 팔찌", answerType: "choice", optionA: "시계 ⌚", optionB: "팔찌 📿" },
  { id: 2197, category: "choice", content: "자연 메이크업 vs 진한 메이크업", answerType: "choice", optionA: "자연 🌿", optionB: "진한 💄" },
  { id: 2198, category: "choice", content: "스트릿 vs 클래식", answerType: "choice", optionA: "스트릿 🛹", optionB: "클래식 🎩" },
  { id: 2199, category: "choice", content: "니트 vs 셔츠", answerType: "choice", optionA: "니트 🧶", optionB: "셔츠 👔" },
  { id: 2200, category: "choice", content: "슬리퍼 vs 샌들", answerType: "choice", optionA: "슬리퍼 🩴", optionB: "샌들 👡" },
  // --- 집/생활 (2201-2220) ---
  { id: 2201, category: "choice", content: "아파트 vs 단독주택", answerType: "choice", optionA: "아파트 🏢", optionB: "단독주택 🏠" },
  { id: 2202, category: "choice", content: "높은 층 vs 낮은 층", answerType: "choice", optionA: "높은 층 🏗️", optionB: "낮은 층 🌳" },
  { id: 2203, category: "choice", content: "넓은 거실 vs 넓은 침실", answerType: "choice", optionA: "거실 🛋️", optionB: "침실 🛏️" },
  { id: 2204, category: "choice", content: "욕조 있는 집 vs 테라스 있는 집", answerType: "choice", optionA: "욕조 🛁", optionB: "테라스 🌇" },
  { id: 2205, category: "choice", content: "식기세척기 vs 로봇청소기", answerType: "choice", optionA: "식기세척기 🍽️", optionB: "로봇청소기 🤖" },
  { id: 2206, category: "choice", content: "가스레인지 vs 인덕션", answerType: "choice", optionA: "가스 🔥", optionB: "인덕션 ⚡" },
  { id: 2207, category: "choice", content: "마당 있는 집 vs 역세권 집", answerType: "choice", optionA: "마당 🌿", optionB: "역세권 🚇" },
  { id: 2208, category: "choice", content: "화이트톤 vs 우드톤", answerType: "choice", optionA: "화이트톤 ⬜", optionB: "우드톤 🪵" },
  { id: 2209, category: "choice", content: "식물 키우기 vs 물고기 키우기", answerType: "choice", optionA: "식물 🌱", optionB: "물고기 🐠" },
  { id: 2210, category: "choice", content: "소파 vs 빈백", answerType: "choice", optionA: "소파 🛋️", optionB: "빈백 🫘" },
  { id: 2211, category: "choice", content: "빔프로젝터 vs 큰TV", answerType: "choice", optionA: "빔프로젝터 📽️", optionB: "큰 TV 📺" },
  { id: 2212, category: "choice", content: "주방 넓은 vs 옷방 넓은", answerType: "choice", optionA: "주방 🍳", optionB: "옷방 👗" },
  { id: 2213, category: "choice", content: "커튼 vs 블라인드", answerType: "choice", optionA: "커튼 🪟", optionB: "블라인드 🪹" },
  { id: 2214, category: "choice", content: "침대 vs 바닥 생활", answerType: "choice", optionA: "침대 🛏️", optionB: "바닥 🟫" },
  { id: 2215, category: "choice", content: "따뜻한 조명 vs 하얀 조명", answerType: "choice", optionA: "따뜻한 🕯️", optionB: "하얀 💡" },
  { id: 2216, category: "choice", content: "베란다 텃밭 vs 베란다 카페", answerType: "choice", optionA: "텃밭 🌿", optionB: "카페 ☕" },
  { id: 2217, category: "choice", content: "드럼세탁기 vs 통돌이", answerType: "choice", optionA: "드럼 🧺", optionB: "통돌이 🔄" },
  { id: 2218, category: "choice", content: "향초 vs 디퓨저", answerType: "choice", optionA: "향초 🕯️", optionB: "디퓨저 🌸" },
  { id: 2219, category: "choice", content: "무선 충전 vs 유선 충전", answerType: "choice", optionA: "무선 📶", optionB: "유선 🔌" },
  { id: 2220, category: "choice", content: "정수기 vs 생수", answerType: "choice", optionA: "정수기 💧", optionB: "생수 🧴" },
  // --- 성격/가치관 (2221-2240) ---
  { id: 2221, category: "choice", content: "넓고 얕은 인간관계 vs 좁고 깊은", answerType: "choice", optionA: "넓고 얕게 🌊", optionB: "좁고 깊게 🕳️" },
  { id: 2222, category: "choice", content: "도전 vs 안정", answerType: "choice", optionA: "도전 🚀", optionB: "안정 🏠" },
  { id: 2223, category: "choice", content: "이성적 vs 감성적", answerType: "choice", optionA: "이성적 🧠", optionB: "감성적 💗" },
  { id: 2224, category: "choice", content: "리더 vs 팔로워", answerType: "choice", optionA: "리더 👑", optionB: "팔로워 🤝" },
  { id: 2225, category: "choice", content: "외향적 vs 내향적", answerType: "choice", optionA: "외향적 🎉", optionB: "내향적 📚" },
  { id: 2226, category: "choice", content: "결과 중시 vs 과정 중시", answerType: "choice", optionA: "결과 🏆", optionB: "과정 🛤️" },
  { id: 2227, category: "choice", content: "빠른 결정 vs 신중한 결정", answerType: "choice", optionA: "빠른 ⚡", optionB: "신중한 🤔" },
  { id: 2228, category: "choice", content: "낙관적 vs 현실적", answerType: "choice", optionA: "낙관적 😄", optionB: "현실적 📊" },
  { id: 2229, category: "choice", content: "말로 표현 vs 행동으로 표현", answerType: "choice", optionA: "말 💬", optionB: "행동 🤲" },
  { id: 2230, category: "choice", content: "완벽주의 vs 적당주의", answerType: "choice", optionA: "완벽주의 💎", optionB: "적당주의 👌" },
  { id: 2231, category: "choice", content: "새로운 친구 vs 오래된 친구", answerType: "choice", optionA: "새 친구 🆕", optionB: "오래된 친구 🫂" },
  { id: 2232, category: "choice", content: "규칙 중시 vs 유연하게", answerType: "choice", optionA: "규칙 📏", optionB: "유연하게 🌊" },
  { id: 2233, category: "choice", content: "직접 경험 vs 간접 경험", answerType: "choice", optionA: "직접 🏃", optionB: "간접 📖" },
  { id: 2234, category: "choice", content: "논쟁 즐기기 vs 논쟁 피하기", answerType: "choice", optionA: "즐기기 🗣️", optionB: "피하기 🕊️" },
  { id: 2235, category: "choice", content: "미래 걱정 vs 현재 집중", answerType: "choice", optionA: "미래 걱정 🔮", optionB: "현재 집중 🎯" },
  { id: 2236, category: "choice", content: "독립적 vs 의존적", answerType: "choice", optionA: "독립적 🦅", optionB: "의존적 🐨" },
  { id: 2237, category: "choice", content: "자유 vs 책임", answerType: "choice", optionA: "자유 🕊️", optionB: "책임 ⚖️" },
  { id: 2238, category: "choice", content: "사과를 먼저 vs 해명을 먼저", answerType: "choice", optionA: "사과 먼저 🙏", optionB: "해명 먼저 💬" },
  { id: 2239, category: "choice", content: "재능 vs 노력", answerType: "choice", optionA: "재능 ⭐", optionB: "노력 💦" },
  { id: 2240, category: "choice", content: "경쟁 vs 협동", answerType: "choice", optionA: "경쟁 🏁", optionB: "협동 🤝" },
  // --- 재미 Would-You-Rather (2241-2260) ---
  { id: 2241, category: "choice", content: "항상 여름옷 vs 항상 겨울옷", answerType: "choice", optionA: "여름옷 👙", optionB: "겨울옷 🧥" },
  { id: 2242, category: "choice", content: "노래만 가능 vs 춤만 가능", answerType: "choice", optionA: "노래만 🎤", optionB: "춤만 💃" },
  { id: 2243, category: "choice", content: "밥만 먹기 vs 빵만 먹기", answerType: "choice", optionA: "밥만 🍚", optionB: "빵만 🍞" },
  { id: 2244, category: "choice", content: "평생 한 색만 vs 평생 무채색", answerType: "choice", optionA: "한 색 🔴", optionB: "무채색 ⬛" },
  { id: 2245, category: "choice", content: "기억 다 남기기 vs 선택 삭제", answerType: "choice", optionA: "다 남기기 🧠", optionB: "선택 삭제 🗑️" },
  { id: 2246, category: "choice", content: "소리 안 들림 vs 냄새 안 맡음", answerType: "choice", optionA: "소리 안 들림 🔇", optionB: "냄새 안 맡음 👃" },
  { id: 2247, category: "choice", content: "과거의 나에게 한마디 vs 미래의 나에게", answerType: "choice", optionA: "과거에게 ⏪", optionB: "미래에게 ⏩" },
  { id: 2248, category: "choice", content: "모든 동물 친구 vs 모든 식물 친구", answerType: "choice", optionA: "동물 친구 🐾", optionB: "식물 친구 🌳" },
  { id: 2249, category: "choice", content: "영원히 25살 vs 영원히 35살", answerType: "choice", optionA: "25살 🌟", optionB: "35살 🧑‍💼" },
  { id: 2250, category: "choice", content: "SNS 없는 삶 vs 현금 없는 삶", answerType: "choice", optionA: "SNS 없이 📵", optionB: "현금 없이 💳" },
  { id: 2251, category: "choice", content: "맨날 월요일 vs 맨날 금요일", answerType: "choice", optionA: "월요일 😩", optionB: "금요일 🎉" },
  { id: 2252, category: "choice", content: "1년 해외 vs 10년 한곳", answerType: "choice", optionA: "1년 해외 🌍", optionB: "10년 한곳 🏠" },
  { id: 2253, category: "choice", content: "시험 100점 vs 복권 100만원", answerType: "choice", optionA: "100점 💯", optionB: "100만원 💰" },
  { id: 2254, category: "choice", content: "3시간 수면 OK vs 3끼 1끼로 OK", answerType: "choice", optionA: "3시간 수면 😴", optionB: "1끼만 🍽️" },
  { id: 2255, category: "choice", content: "발표 왕 vs 시험 왕", answerType: "choice", optionA: "발표 왕 🎤", optionB: "시험 왕 📝" },
  { id: 2256, category: "choice", content: "1일 연예인 vs 1일 대통령", answerType: "choice", optionA: "연예인 ⭐", optionB: "대통령 🏛️" },
  { id: 2257, category: "choice", content: "평생 하나만 먹기 vs 매일 새로운 음식", answerType: "choice", optionA: "하나만 🍕", optionB: "매일 새로 🌮" },
  { id: 2258, category: "choice", content: "키 10cm 더 vs 얼굴 10배 작게", answerType: "choice", optionA: "키 10cm 📏", optionB: "얼굴 작게 🤏" },
  { id: 2259, category: "choice", content: "겨울에 에어컨 vs 여름에 히터", answerType: "choice", optionA: "겨울 에어컨 ❄️", optionB: "여름 히터 🔥" },
  { id: 2260, category: "choice", content: "1억 받고 1년 금욕 vs 그냥 살기", answerType: "choice", optionA: "1억 금욕 💰", optionB: "그냥 살기 😌" },
  // --- 계절/시간 (2261-2280) ---
  { id: 2261, category: "choice", content: "봄 소풍 vs 가을 소풍", answerType: "choice", optionA: "봄 소풍 🌷", optionB: "가을 소풍 🍁" },
  { id: 2262, category: "choice", content: "여름 바다 vs 겨울 스키장", answerType: "choice", optionA: "여름 바다 🏄", optionB: "겨울 스키 ⛷️" },
  { id: 2263, category: "choice", content: "벚꽃 놀이 vs 눈싸움", answerType: "choice", optionA: "벚꽃 놀이 🌸", optionB: "눈싸움 ☃️" },
  { id: 2264, category: "choice", content: "추석 vs 설날", answerType: "choice", optionA: "추석 🌕", optionB: "설날 🧧" },
  { id: 2265, category: "choice", content: "크리스마스 집 vs 크리스마스 밖", answerType: "choice", optionA: "집에서 🏠", optionB: "밖에서 🎄" },
  { id: 2266, category: "choice", content: "비 오는 날 데이트 vs 맑은 날 데이트", answerType: "choice", optionA: "비 오는 날 ☔", optionB: "맑은 날 ☀️" },
  { id: 2267, category: "choice", content: "월요일 아침 vs 일요일 저녁", answerType: "choice", optionA: "월요일 아침 😣", optionB: "일요일 저녁 😢" },
  { id: 2268, category: "choice", content: "주말 아침 vs 주말 밤", answerType: "choice", optionA: "주말 아침 🌤️", optionB: "주말 밤 🌙" },
  { id: 2269, category: "choice", content: "4계절 있는 곳 vs 항상 따뜻한 곳", answerType: "choice", optionA: "4계절 🍂", optionB: "항상 따뜻 🌴" },
  { id: 2270, category: "choice", content: "핼러윈 파티 vs 새해 카운트다운", answerType: "choice", optionA: "핼러윈 🎃", optionB: "카운트다운 🎆" },
  { id: 2271, category: "choice", content: "단풍 구경 vs 억새밭 구경", answerType: "choice", optionA: "단풍 🍁", optionB: "억새밭 🌾" },
  { id: 2272, category: "choice", content: "장마철 vs 한파", answerType: "choice", optionA: "장마철 🌧️", optionB: "한파 🥶" },
  { id: 2273, category: "choice", content: "오전 데이트 vs 오후 데이트", answerType: "choice", optionA: "오전 ☀️", optionB: "오후 🌆" },
  { id: 2274, category: "choice", content: "생일에 케이크 vs 생일에 선물", answerType: "choice", optionA: "케이크 🎂", optionB: "선물 🎁" },
  { id: 2275, category: "choice", content: "여름 축제 vs 겨울 축제", answerType: "choice", optionA: "여름 축제 🎆", optionB: "겨울 축제 🎄" },
  { id: 2276, category: "choice", content: "평일 휴가 vs 주말 보너스", answerType: "choice", optionA: "평일 휴가 🏖️", optionB: "주말 보너스 💰" },
  { id: 2277, category: "choice", content: "봄비 vs 가을비", answerType: "choice", optionA: "봄비 🌧️", optionB: "가을비 🍂" },
  { id: 2278, category: "choice", content: "크리스마스 이브 vs 크리스마스 당일", answerType: "choice", optionA: "이브 🌙", optionB: "당일 🎄" },
  { id: 2279, category: "choice", content: "밤산책 vs 새벽산책", answerType: "choice", optionA: "밤산책 🌙", optionB: "새벽산책 🌅" },
  { id: 2280, category: "choice", content: "불꽃놀이 vs 풍등 날리기", answerType: "choice", optionA: "불꽃놀이 🎆", optionB: "풍등 🏮" },
];
