import type { Question } from "@/types/question";

/** 추가 양자택일 질문 Part 1 (ID 2041-2160) */
export const CHOICE_EXTRA_1: Question[] = [
  // --- 음식 매치업 (2041-2060) ---
  { id: 2041, category: "choice", content: "떡볶이 vs 순대", answerType: "choice", optionA: "떡볶이 🌶️", optionB: "순대 🫕" },
  { id: 2042, category: "choice", content: "짜장면 vs 짬뽕", answerType: "choice", optionA: "짜장면 🍜", optionB: "짬뽕 🥘" },
  { id: 2043, category: "choice", content: "삼겹살 vs 소고기", answerType: "choice", optionA: "삼겹살 🥓", optionB: "소고기 🥩" },
  { id: 2044, category: "choice", content: "초밥 vs 회", answerType: "choice", optionA: "초밥 🍣", optionB: "회 🐟" },
  { id: 2045, category: "choice", content: "김치찌개 vs 된장찌개", answerType: "choice", optionA: "김치찌개 🥬", optionB: "된장찌개 🫘" },
  { id: 2046, category: "choice", content: "마라탕 vs 훠궈", answerType: "choice", optionA: "마라탕 🔥", optionB: "훠궈 🍲" },
  { id: 2047, category: "choice", content: "붕어빵 vs 호떡", answerType: "choice", optionA: "붕어빵 🐟", optionB: "호떡 🥞" },
  { id: 2048, category: "choice", content: "라면 vs 우동", answerType: "choice", optionA: "라면 🍜", optionB: "우동 🍥" },
  { id: 2049, category: "choice", content: "떡 vs 빵", answerType: "choice", optionA: "떡 🍡", optionB: "빵 🍞" },
  { id: 2050, category: "choice", content: "족발 vs 보쌈", answerType: "choice", optionA: "족발 🦶", optionB: "보쌈 🥬" },
  { id: 2051, category: "choice", content: "파스타 vs 리조또", answerType: "choice", optionA: "파스타 🍝", optionB: "리조또 🍚" },
  { id: 2052, category: "choice", content: "타코야끼 vs 오코노미야끼", answerType: "choice", optionA: "타코야끼 🐙", optionB: "오코노미 🥞" },
  { id: 2053, category: "choice", content: "햄버거 vs 샌드위치", answerType: "choice", optionA: "햄버거 🍔", optionB: "샌드위치 🥪" },
  { id: 2054, category: "choice", content: "비빔밥 vs 볶음밥", answerType: "choice", optionA: "비빔밥 🍚", optionB: "볶음밥 🍳" },
  { id: 2055, category: "choice", content: "케이크 vs 마카롱", answerType: "choice", optionA: "케이크 🎂", optionB: "마카롱 🧁" },
  { id: 2056, category: "choice", content: "아이스크림 vs 빙수", answerType: "choice", optionA: "아이스크림 🍦", optionB: "빙수 🍧" },
  { id: 2057, category: "choice", content: "콜라 vs 사이다", answerType: "choice", optionA: "콜라 🥤", optionB: "사이다 🫧" },
  { id: 2058, category: "choice", content: "와인 vs 맥주", answerType: "choice", optionA: "와인 🍷", optionB: "맥주 🍺" },
  { id: 2059, category: "choice", content: "밀크티 vs 과일차", answerType: "choice", optionA: "밀크티 🧋", optionB: "과일차 🍊" },
  { id: 2060, category: "choice", content: "국밥 vs 칼국수", answerType: "choice", optionA: "국밥 🍲", optionB: "칼국수 🍜" },
  // --- 데이트 활동 (2061-2080) ---
  { id: 2061, category: "choice", content: "등산 vs 드라이브", answerType: "choice", optionA: "등산 🥾", optionB: "드라이브 🚗" },
  { id: 2062, category: "choice", content: "보드게임 vs 퍼즐", answerType: "choice", optionA: "보드게임 🎲", optionB: "퍼즐 🧩" },
  { id: 2063, category: "choice", content: "미술관 vs 박물관", answerType: "choice", optionA: "미술관 🎨", optionB: "박물관 🏛️" },
  { id: 2064, category: "choice", content: "노래방 vs 볼링", answerType: "choice", optionA: "노래방 🎤", optionB: "볼링 🎳" },
  { id: 2065, category: "choice", content: "캠핑 vs 글램핑", answerType: "choice", optionA: "캠핑 ⛺", optionB: "글램핑 🏕️" },
  { id: 2066, category: "choice", content: "공원 산책 vs 쇼핑몰", answerType: "choice", optionA: "공원 산책 🌿", optionB: "쇼핑몰 🛍️" },
  { id: 2067, category: "choice", content: "요리 교실 vs 도예 교실", answerType: "choice", optionA: "요리 교실 👨‍🍳", optionB: "도예 교실 🏺" },
  { id: 2068, category: "choice", content: "야경 보기 vs 일출 보기", answerType: "choice", optionA: "야경 🌃", optionB: "일출 🌅" },
  { id: 2069, category: "choice", content: "사진 부스 vs 스냅 촬영", answerType: "choice", optionA: "사진 부스 📷", optionB: "스냅 촬영 📸" },
  { id: 2070, category: "choice", content: "수족관 vs 동물원", answerType: "choice", optionA: "수족관 🐠", optionB: "동물원 🦁" },
  { id: 2071, category: "choice", content: "방탈출 vs VR체험", answerType: "choice", optionA: "방탈출 🔐", optionB: "VR체험 🥽" },
  { id: 2072, category: "choice", content: "야시장 vs 플리마켓", answerType: "choice", optionA: "야시장 🏮", optionB: "플리마켓 🧺" },
  { id: 2073, category: "choice", content: "스케이트 vs 스키", answerType: "choice", optionA: "스케이트 ⛸️", optionB: "스키 ⛷️" },
  { id: 2074, category: "choice", content: "배달 시켜먹기 vs 직접 해먹기", answerType: "choice", optionA: "배달 🛵", optionB: "직접 요리 🍳" },
  { id: 2075, category: "choice", content: "뮤지컬 vs 콘서트", answerType: "choice", optionA: "뮤지컬 🎭", optionB: "콘서트 🎵" },
  { id: 2076, category: "choice", content: "온천 vs 사우나", answerType: "choice", optionA: "온천 ♨️", optionB: "사우나 🧖" },
  { id: 2077, category: "choice", content: "자전거 vs 킥보드", answerType: "choice", optionA: "자전거 🚲", optionB: "킥보드 🛴" },
  { id: 2078, category: "choice", content: "벚꽃길 vs 단풍길", answerType: "choice", optionA: "벚꽃길 🌸", optionB: "단풍길 🍂" },
  { id: 2079, category: "choice", content: "브런치 vs 디너", answerType: "choice", optionA: "브런치 🥐", optionB: "디너 🕯️" },
  { id: 2080, category: "choice", content: "해돋이 vs 해넘이", answerType: "choice", optionA: "해돋이 🌅", optionB: "해넘이 🌇" },
  // --- 라이프스타일 (2081-2100) ---
  { id: 2081, category: "choice", content: "장바구니 vs 즉흥구매", answerType: "choice", optionA: "장바구니 🛒", optionB: "즉흥구매 💳" },
  { id: 2082, category: "choice", content: "현금 vs 카드", answerType: "choice", optionA: "현금 💵", optionB: "카드 💳" },
  { id: 2083, category: "choice", content: "청소 먼저 vs 나중에", answerType: "choice", optionA: "먼저 🧹", optionB: "나중에 😅" },
  { id: 2084, category: "choice", content: "이어폰 vs 스피커", answerType: "choice", optionA: "이어폰 🎧", optionB: "스피커 🔊" },
  { id: 2085, category: "choice", content: "종이책 vs 전자책", answerType: "choice", optionA: "종이책 📖", optionB: "전자책 📱" },
  { id: 2086, category: "choice", content: "목욕 vs 샤워", answerType: "choice", optionA: "목욕 🛁", optionB: "샤워 🚿" },
  { id: 2087, category: "choice", content: "미니멀 vs 맥시멀", answerType: "choice", optionA: "미니멀 ⬜", optionB: "맥시멀 🌈" },
  { id: 2088, category: "choice", content: "정리정돈 vs 창의적 혼돈", answerType: "choice", optionA: "정리정돈 📐", optionB: "창의적 혼돈 🎨" },
  { id: 2089, category: "choice", content: "운전 vs 대중교통", answerType: "choice", optionA: "운전 🚗", optionB: "대중교통 🚇" },
  { id: 2090, category: "choice", content: "아침밥 vs 아침 거르기", answerType: "choice", optionA: "아침밥 🍚", optionB: "거르기 😶" },
  { id: 2091, category: "choice", content: "알람 1개 vs 알람 10개", answerType: "choice", optionA: "1개 ⏰", optionB: "10개 📱" },
  { id: 2092, category: "choice", content: "밝은 조명 vs 간접 조명", answerType: "choice", optionA: "밝은 조명 💡", optionB: "간접 조명 🕯️" },
  { id: 2093, category: "choice", content: "에어컨 vs 선풍기", answerType: "choice", optionA: "에어컨 ❄️", optionB: "선풍기 🌀" },
  { id: 2094, category: "choice", content: "온라인 쇼핑 vs 오프라인 쇼핑", answerType: "choice", optionA: "온라인 🖥️", optionB: "오프라인 🏬" },
  { id: 2095, category: "choice", content: "저축 vs 투자", answerType: "choice", optionA: "저축 🏦", optionB: "투자 📈" },
  { id: 2096, category: "choice", content: "일기 쓰기 vs 사진 남기기", answerType: "choice", optionA: "일기 📝", optionB: "사진 📷" },
  { id: 2097, category: "choice", content: "멍 때리기 vs 뭐라도 하기", answerType: "choice", optionA: "멍 때리기 😶", optionB: "뭐라도 💨" },
  { id: 2098, category: "choice", content: "늦잠 vs 일찍 일어나기", answerType: "choice", optionA: "늦잠 😴", optionB: "일찍 🌅" },
  { id: 2099, category: "choice", content: "향수 vs 무향", answerType: "choice", optionA: "향수 🌹", optionB: "무향 🍃" },
  { id: 2100, category: "choice", content: "루틴 vs 변화", answerType: "choice", optionA: "루틴 🔄", optionB: "변화 🦋" },
  // --- 연애/관계 (2101-2120) ---
  { id: 2101, category: "choice", content: "먼저 고백 vs 고백 받기", answerType: "choice", optionA: "먼저 고백 💘", optionB: "받기 💌" },
  { id: 2102, category: "choice", content: "질투 표현 vs 쿨하게", answerType: "choice", optionA: "질투 표현 😤", optionB: "쿨하게 😎" },
  { id: 2103, category: "choice", content: "잠들기 전 전화 vs 굿나잇 문자", answerType: "choice", optionA: "전화 📞", optionB: "문자 💬" },
  { id: 2104, category: "choice", content: "함께 장보기 vs 함께 요리하기", answerType: "choice", optionA: "장보기 🛒", optionB: "요리하기 🍳" },
  { id: 2105, category: "choice", content: "크리스마스 vs 밸런타인", answerType: "choice", optionA: "크리스마스 🎄", optionB: "밸런타인 💝" },
  { id: 2106, category: "choice", content: "만남의날 vs 생일", answerType: "choice", optionA: "만남의날 💑", optionB: "생일 🎂" },
  { id: 2107, category: "choice", content: "손잡기 vs 팔짱끼기", answerType: "choice", optionA: "손잡기 🤝", optionB: "팔짱끼기 💪" },
  { id: 2108, category: "choice", content: "영상통화 vs 음성통화", answerType: "choice", optionA: "영상통화 📹", optionB: "음성통화 📞" },
  { id: 2109, category: "choice", content: "쌍으로 반지 vs 쌍으로 팔찌", answerType: "choice", optionA: "반지 💍", optionB: "팔찌 📿" },
  { id: 2110, category: "choice", content: "같은 취미 vs 다른 취미", answerType: "choice", optionA: "같은 취미 🎯", optionB: "다른 취미 🌈" },
  { id: 2111, category: "choice", content: "애교 vs 츤데레", answerType: "choice", optionA: "애교 🥰", optionB: "츤데레 😏" },
  { id: 2112, category: "choice", content: "함께 운동 vs 함께 산책", answerType: "choice", optionA: "운동 🏋️", optionB: "산책 🚶" },
  { id: 2113, category: "choice", content: "바로 답장 vs 여유롭게", answerType: "choice", optionA: "바로 답장 ⚡", optionB: "여유롭게 🐢" },
  { id: 2114, category: "choice", content: "같이 낮잠 vs 같이 영화", answerType: "choice", optionA: "같이 낮잠 😴", optionB: "같이 영화 🎬" },
  { id: 2115, category: "choice", content: "스킨십 많이 vs 적당히", answerType: "choice", optionA: "많이 🫂", optionB: "적당히 👋" },
  { id: 2116, category: "choice", content: "매일 만나기 vs 가끔 만나기", answerType: "choice", optionA: "매일 💕", optionB: "가끔 💎" },
  { id: 2117, category: "choice", content: "짧은 데이트 vs 긴 데이트", answerType: "choice", optionA: "짧은 ⏱️", optionB: "긴 🕰️" },
  { id: 2118, category: "choice", content: "일상 공유 vs 특별한 것만", answerType: "choice", optionA: "일상 공유 📱", optionB: "특별한 것만 ✨" },
  { id: 2119, category: "choice", content: "칭찬 많이 vs 솔직한 피드백", answerType: "choice", optionA: "칭찬 많이 👏", optionB: "솔직 피드백 📢" },
  { id: 2120, category: "choice", content: "다정한 말투 vs 유머 말투", answerType: "choice", optionA: "다정 🥰", optionB: "유머 😂" },
  // --- 가상/상상 (2121-2140) ---
  { id: 2121, category: "choice", content: "과거 여행 vs 미래 여행", answerType: "choice", optionA: "과거 ⏪", optionB: "미래 ⏩" },
  { id: 2122, category: "choice", content: "투명인간 vs 순간이동", answerType: "choice", optionA: "투명인간 👻", optionB: "순간이동 ⚡" },
  { id: 2123, category: "choice", content: "날씨 조종 vs 동물과 대화", answerType: "choice", optionA: "날씨 조종 🌦️", optionB: "동물 대화 🐾" },
  { id: 2124, category: "choice", content: "평생 여름 vs 평생 가을", answerType: "choice", optionA: "평생 여름 ☀️", optionB: "평생 가을 🍂" },
  { id: 2125, category: "choice", content: "기억력 천재 vs 체력 천재", answerType: "choice", optionA: "기억력 🧠", optionB: "체력 💪" },
  { id: 2126, category: "choice", content: "로또 당첨 vs 완벽한 건강", answerType: "choice", optionA: "로또 💰", optionB: "건강 ❤️" },
  { id: 2127, category: "choice", content: "마법사 vs 과학자", answerType: "choice", optionA: "마법사 🧙", optionB: "과학자 🔬" },
  { id: 2128, category: "choice", content: "하늘 날기 vs 물속 숨쉬기", answerType: "choice", optionA: "하늘 날기 🦅", optionB: "물속 숨쉬기 🐬" },
  { id: 2129, category: "choice", content: "작아지기 vs 커지기", answerType: "choice", optionA: "작아지기 🐜", optionB: "커지기 🦕" },
  { id: 2130, category: "choice", content: "100년 전 vs 100년 후", answerType: "choice", optionA: "100년 전 🏛️", optionB: "100년 후 🚀" },
  { id: 2131, category: "choice", content: "읽심술 vs 예지력", answerType: "choice", optionA: "읽심술 🔮", optionB: "예지력 👁️" },
  { id: 2132, category: "choice", content: "무한 체력 vs 무한 창의력", answerType: "choice", optionA: "체력 💪", optionB: "창의력 💡" },
  { id: 2133, category: "choice", content: "맛 천재 vs 음악 천재", answerType: "choice", optionA: "맛 천재 👨‍🍳", optionB: "음악 천재 🎵" },
  { id: 2134, category: "choice", content: "외모 고정 vs 성격 고정", answerType: "choice", optionA: "외모 고정 ✨", optionB: "성격 고정 💖" },
  { id: 2135, category: "choice", content: "1일 왕 vs 1년 평민", answerType: "choice", optionA: "1일 왕 👑", optionB: "1년 평민 🏠" },
  { id: 2136, category: "choice", content: "모든 언어 vs 모든 악기", answerType: "choice", optionA: "모든 언어 🗣️", optionB: "모든 악기 🎹" },
  { id: 2137, category: "choice", content: "시간 멈추기 vs 시간 되돌리기", answerType: "choice", optionA: "멈추기 ⏸️", optionB: "되돌리기 ⏪" },
  { id: 2138, category: "choice", content: "무인도 1명 vs 도시 혼자", answerType: "choice", optionA: "무인도 1명 🏝️", optionB: "도시 혼자 🏙️" },
  { id: 2139, category: "choice", content: "꿈 기억 vs 꿈 조종", answerType: "choice", optionA: "꿈 기억 📝", optionB: "꿈 조종 🎮" },
  { id: 2140, category: "choice", content: "하루 48시간 vs 한달 휴가", answerType: "choice", optionA: "48시간 ⏰", optionB: "한달 휴가 🌴" },
  // --- 팝컬처/취향 (2141-2160) ---
  { id: 2141, category: "choice", content: "로맨스 vs 액션", answerType: "choice", optionA: "로맨스 💕", optionB: "액션 💥" },
  { id: 2142, category: "choice", content: "공포 영화 vs 코미디 영화", answerType: "choice", optionA: "공포 👻", optionB: "코미디 😂" },
  { id: 2143, category: "choice", content: "발라드 vs 힙합", answerType: "choice", optionA: "발라드 🎤", optionB: "힙합 🎧" },
  { id: 2144, category: "choice", content: "K-pop vs 팝송", answerType: "choice", optionA: "K-pop 🇰🇷", optionB: "팝송 🌍" },
  { id: 2145, category: "choice", content: "웹툰 vs 웹소설", answerType: "choice", optionA: "웹툰 📱", optionB: "웹소설 📖" },
  { id: 2146, category: "choice", content: "RPG vs 슈팅 게임", answerType: "choice", optionA: "RPG ⚔️", optionB: "슈팅 🔫" },
  { id: 2147, category: "choice", content: "닌텐도 vs 플스", answerType: "choice", optionA: "닌텐도 🎮", optionB: "플스 🕹️" },
  { id: 2148, category: "choice", content: "애니 vs 실사", answerType: "choice", optionA: "애니 🎌", optionB: "실사 🎬" },
  { id: 2149, category: "choice", content: "판타지 vs SF", answerType: "choice", optionA: "판타지 🧝", optionB: "SF 🤖" },
  { id: 2150, category: "choice", content: "예능 출연 vs 드라마 출연", answerType: "choice", optionA: "예능 😆", optionB: "드라마 🎭" },
  { id: 2151, category: "choice", content: "유행 따라가기 vs 내 스타일", answerType: "choice", optionA: "유행 📈", optionB: "내 스타일 🎨" },
  { id: 2152, category: "choice", content: "인스타 vs 틱톡", answerType: "choice", optionA: "인스타 📸", optionB: "틱톡 🎵" },
  { id: 2153, category: "choice", content: "추리물 vs 멜로물", answerType: "choice", optionA: "추리물 🔍", optionB: "멜로물 💗" },
  { id: 2154, category: "choice", content: "라이브 방송 vs 편집 영상", answerType: "choice", optionA: "라이브 🔴", optionB: "편집 영상 🎞️" },
  { id: 2155, category: "choice", content: "팟캐스트 vs 음악", answerType: "choice", optionA: "팟캐스트 🎙️", optionB: "음악 🎶" },
  { id: 2156, category: "choice", content: "보드게임 vs 카드게임", answerType: "choice", optionA: "보드게임 🎲", optionB: "카드게임 🃏" },
  { id: 2157, category: "choice", content: "일본 여행 vs 유럽 여행", answerType: "choice", optionA: "일본 🇯🇵", optionB: "유럽 🇪🇺" },
  { id: 2158, category: "choice", content: "다큐멘터리 vs 리얼리티", answerType: "choice", optionA: "다큐 🎥", optionB: "리얼리티 📺" },
  { id: 2159, category: "choice", content: "클래식 vs 재즈", answerType: "choice", optionA: "클래식 🎻", optionB: "재즈 🎷" },
  { id: 2160, category: "choice", content: "솔로 게임 vs 멀티 게임", answerType: "choice", optionA: "솔로 🎮", optionB: "멀티 👥" },
];
