import type { Question } from "@/types/question";

/** 점수형 질문 (1~10) — 모든 카테고리 혼합 */
export const SCALE_QUESTIONS: Question[] = [
  { id: 3001, category: "between", content: "오늘 우리 관계 만족도는?", answerType: "scale", scaleMin: "불만 😢", scaleMax: "최고 🥰" },
  { id: 3002, category: "honest", content: "요즘 내가 잘하고 있는 정도는?", answerType: "scale", scaleMin: "노력해 😅", scaleMax: "완벽해 ✨" },
  { id: 3003, category: "between", content: "지금 이 순간 보고 싶은 정도는?", answerType: "scale", scaleMin: "조금 🙂", scaleMax: "미치도록 💕" },
  { id: 3004, category: "tmi", content: "오늘 하루 피곤한 정도는?", answerType: "scale", scaleMin: "멀쩡 💪", scaleMax: "기절 직전 😵" },
  { id: 3005, category: "between", content: "우리 대화 빈도에 만족하는 정도는?", answerType: "scale", scaleMin: "부족해 📵", scaleMax: "딱 좋아 💬" },
  { id: 3006, category: "honest", content: "솔직히 내 요리 실력은?", answerType: "scale", scaleMin: "위험 🔥", scaleMax: "셰프급 👨‍🍳" },
  { id: 3007, category: "tmi", content: "지금 배고픈 정도는?", answerType: "scale", scaleMin: "괜찮아 😊", scaleMax: "곧 쓰러져 🍽️" },
  { id: 3008, category: "between", content: "최근 우리 스킨십에 만족하는 정도는?", answerType: "scale", scaleMin: "더 원해 🙈", scaleMax: "완벽해 🫂" },
  { id: 3009, category: "values", content: "현재 삶의 행복도는?", answerType: "scale", scaleMin: "힘들어 😔", scaleMax: "너무 행복 ☀️" },
  { id: 3010, category: "honest", content: "내 패션 센스 점수는?", answerType: "scale", scaleMin: "많이 부족 👀", scaleMax: "인플루언서급 ✨" },
  { id: 3011, category: "between", content: "나한테 설레는 정도는?", answerType: "scale", scaleMin: "편안해 🧸", scaleMax: "심쿵 💘" },
  { id: 3012, category: "tmi", content: "오늘 기분 좋은 정도는?", answerType: "scale", scaleMin: "별로 😞", scaleMax: "최고 😆" },
  { id: 3013, category: "values", content: "일과 연애 밸런스 만족도는?", answerType: "scale", scaleMin: "불균형 ⚖️", scaleMax: "완벽 균형 🎯" },
  { id: 3014, category: "honest", content: "내 잠버릇 심한 정도는?", answerType: "scale", scaleMin: "천사 😇", scaleMax: "전쟁 ⚔️" },
  { id: 3015, category: "between", content: "우리 여행 궁합은?", answerType: "scale", scaleMin: "안 맞아 😅", scaleMax: "찰떡 🤝" },
  { id: 3016, category: "tmi", content: "지금 잠오는 정도는?", answerType: "scale", scaleMin: "멀쩡 👀", scaleMax: "이미 꿈속 😴" },
  { id: 3017, category: "honest", content: "내 애교 수준은?", answerType: "scale", scaleMin: "츤데레 😤", scaleMax: "애교왕 🥰" },
  { id: 3018, category: "between", content: "우리 음식 취향 맞는 정도는?", answerType: "scale", scaleMin: "완전 다름 🤷", scaleMax: "찰떡 🍽️" },
  { id: 3019, category: "values", content: "지금 자존감 레벨은?", answerType: "scale", scaleMin: "바닥 📉", scaleMax: "하늘 📈" },
  { id: 3020, category: "honest", content: "내 운전 실력은?", answerType: "scale", scaleMin: "무서워 🫣", scaleMax: "프로 🏎️" },
  { id: 3021, category: "between", content: "지금 나한테 화난 정도는?", answerType: "scale", scaleMin: "전혀 😊", scaleMax: "많이 😡" },
  { id: 3022, category: "tmi", content: "오늘 귀찮은 정도는?", answerType: "scale", scaleMin: "의욕 넘침 🔥", scaleMax: "움직이기 싫어 🦥" },
  { id: 3023, category: "between", content: "우리 유머 코드 맞는 정도는?", answerType: "scale", scaleMin: "다른 세계 🌍", scaleMax: "텔레파시 🧠" },
  { id: 3024, category: "honest", content: "내가 집안일 잘하는 정도는?", answerType: "scale", scaleMin: "거의 안 해 😅", scaleMax: "살림꾼 🧹" },
  { id: 3025, category: "tmi", content: "지금 스트레스 레벨은?", answerType: "scale", scaleMin: "평화 🕊️", scaleMax: "폭발 직전 🌋" },
  { id: 3026, category: "between", content: "우리 싸운 후 화해 속도는?", answerType: "scale", scaleMin: "느려 🐢", scaleMax: "빨라 ⚡" },
  { id: 3027, category: "honest", content: "나한테 질투 느끼는 정도는?", answerType: "scale", scaleMin: "전혀 😎", scaleMax: "많이 😤" },
  { id: 3028, category: "values", content: "미래에 대한 불안감 정도는?", answerType: "scale", scaleMin: "없어 🌈", scaleMax: "많아 😰" },
  { id: 3029, category: "between", content: "오늘 나한테 고마운 정도는?", answerType: "scale", scaleMin: "보통 🙂", scaleMax: "너무 감사 🥹" },
  { id: 3030, category: "tmi", content: "지금 카페 가고 싶은 정도는?", answerType: "scale", scaleMin: "괜찮아 🏠", scaleMax: "당장 가자 ☕" },
  { id: 3031, category: "between", content: "나랑 있을 때 편안한 정도는?", answerType: "scale", scaleMin: "긴장 😳", scaleMax: "집처럼 편해 🏠" },
  { id: 3032, category: "honest", content: "최근 나한테 실망한 정도는?", answerType: "scale", scaleMin: "전혀 없어 ☺️", scaleMax: "좀 있어 😔" },
  { id: 3033, category: "values", content: "현재 저축 잘 하고 있는 정도는?", answerType: "scale", scaleMin: "텅장 💸", scaleMax: "알뜰왕 🏦" },
  { id: 3034, category: "between", content: "우리 기념일 챙기는 정도는?", answerType: "scale", scaleMin: "잘 모름 📅", scaleMax: "완벽 🎂" },
  { id: 3035, category: "tmi", content: "지금 여행 가고 싶은 정도는?", answerType: "scale", scaleMin: "집이 좋아 🏠", scaleMax: "당장 떠나자 ✈️" },
];
