import type { Question } from "@/types/question";

/** 추가 점수형 질문 Part 1 (ID 3036~3117) */
export const SCALE_EXTRA_1: Question[] = [
  { id: 3036, category: "honest", content: "내 노래 실력은?", answerType: "scale", scaleMin: "음이탈 🎤", scaleMax: "가수급 🎶" },
  { id: 3037, category: "between", content: "요즘 우리 신뢰도는?", answerType: "scale", scaleMin: "불안해 😟", scaleMax: "완전 믿어 🤝" },
  { id: 3038, category: "tmi", content: "오늘 에너지 레벨은?", answerType: "scale", scaleMin: "방전 🪫", scaleMax: "완충 🔋" },
  { id: 3039, category: "values", content: "현재 건강 만족도는?", answerType: "scale", scaleMin: "관리 필요 🏥", scaleMax: "건강왕 💪" },
  { id: 3040, category: "future", content: "미래가 기대되는 정도는?", answerType: "scale", scaleMin: "걱정 😨", scaleMax: "설레 🌟" },
  { id: 3041, category: "pet", content: "반려동물 보고 싶은 정도는?", answerType: "scale", scaleMin: "조금 🐾", scaleMax: "당장 보고파 😭" },
  { id: 3042, category: "honest", content: "내 춤 실력은?", answerType: "scale", scaleMin: "몸치 🤖", scaleMax: "댄서급 💃" },
  { id: 3043, category: "between", content: "서로 이해하는 정도는?", answerType: "scale", scaleMin: "아직 부족 🤔", scaleMax: "마음을 읽어 🧠" },
  { id: 3044, category: "tmi", content: "오늘 사회성 레벨은?", answerType: "scale", scaleMin: "혼자 있고파 🐚", scaleMax: "사교왕 🥳" },
  { id: 3045, category: "values", content: "내 취미 만족도는?", answerType: "scale", scaleMin: "취미가 없어 😶", scaleMax: "인생 충만 🎨" },
  { id: 3046, category: "future", content: "결혼하고 싶은 정도는?", answerType: "scale", scaleMin: "아직 일러 🙅", scaleMax: "당장이라도 💒" },
  { id: 3047, category: "honest", content: "내 유머 감각은?", answerType: "scale", scaleMin: "재미없어 😐", scaleMax: "개그맨급 🤣" },
  { id: 3048, category: "between", content: "상대방 배려 받는 정도는?", answerType: "scale", scaleMin: "아쉬워 😢", scaleMax: "감동이야 🥹" },
  { id: 3049, category: "tmi", content: "창의력 넘치는 정도는?", answerType: "scale", scaleMin: "바닥 🧱", scaleMax: "천재 💡" },
  { id: 3050, category: "pet", content: "펫 케어 자신감은?", answerType: "scale", scaleMin: "초보 🐣", scaleMax: "전문가 🏆" },
  { id: 3051, category: "values", content: "직장/학교 만족도는?", answerType: "scale", scaleMin: "탈출하고파 😩", scaleMax: "너무 좋아 🏢" },
  { id: 3052, category: "between", content: "우리 데이트 질에 만족도는?", answerType: "scale", scaleMin: "아쉬워 😕", scaleMax: "매번 최고 ✨" },
  { id: 3053, category: "honest", content: "내 인내심 레벨은?", answerType: "scale", scaleMin: "급해 🔥", scaleMax: "부처님 🧘" },
  { id: 3054, category: "tmi", content: "단 것 먹고 싶은 정도는?", answerType: "scale", scaleMin: "괜찮아 🙂", scaleMax: "디저트 폭주 🍰" },
  { id: 3055, category: "future", content: "같이 살고 싶은 정도는?", answerType: "scale", scaleMin: "아직 일러 🤚", scaleMax: "당장 이사 🏠" },
  { id: 3056, category: "between", content: "요즘 연락 만족도는?", answerType: "scale", scaleMin: "더 하고파 📱", scaleMax: "딱 적당해 💌" },
  { id: 3057, category: "honest", content: "내 정리정돈 능력은?", answerType: "scale", scaleMin: "쓰레기장 🗑️", scaleMax: "미니멀리스트 🧹" },
  { id: 3058, category: "tmi", content: "오늘 의욕 레벨은?", answerType: "scale", scaleMin: "제로 🦥", scaleMax: "불타올라 🔥" },
  { id: 3059, category: "values", content: "가족관계 만족도는?", answerType: "scale", scaleMin: "복잡해 😣", scaleMax: "화목해 👨‍👩‍👧‍👦" },
  { id: 3060, category: "pet", content: "동물 좋아하는 정도는?", answerType: "scale", scaleMin: "보통 🙂", scaleMax: "동물 덕후 🐕" },
  { id: 3061, category: "between", content: "서로 응원해주는 정도는?", answerType: "scale", scaleMin: "부족해 😔", scaleMax: "든든해 📣" },
  { id: 3062, category: "honest", content: "내 시간관리 능력은?", answerType: "scale", scaleMin: "만년 지각 🐢", scaleMax: "칼같아 ⏰" },
  { id: 3063, category: "tmi", content: "지금 운동하고 싶은 정도는?", answerType: "scale", scaleMin: "절대 싫어 🛋️", scaleMax: "헬스장 가자 🏋️" },
  { id: 3064, category: "future", content: "여행 계획 세우고 싶은 정도는?", answerType: "scale", scaleMin: "귀찮아 😅", scaleMax: "지금 당장 🗺️" },
  { id: 3065, category: "values", content: "친구관계 만족도는?", answerType: "scale", scaleMin: "외로워 😢", scaleMax: "인싸 🎉" },
  { id: 3066, category: "between", content: "우리 성장하고 있는 정도는?", answerType: "scale", scaleMin: "정체 중 📉", scaleMax: "함께 성장 📈" },
  { id: 3067, category: "honest", content: "내 계획성 레벨은?", answerType: "scale", scaleMin: "즉흥적 🎲", scaleMax: "계획왕 📋" },
  { id: 3068, category: "tmi", content: "지금 치킨 먹고 싶은 정도는?", answerType: "scale", scaleMin: "보통 🙂", scaleMax: "침 흘러 🍗" },
  { id: 3069, category: "between", content: "나한테 의지하는 정도는?", answerType: "scale", scaleMin: "독립적 🧍", scaleMax: "기댈게 🫂" },
  { id: 3070, category: "pet", content: "산책 가고 싶은 정도는?", answerType: "scale", scaleMin: "집이 좋아 🏠", scaleMax: "나가자! 🐕‍🦺" },
  { id: 3071, category: "values", content: "자기계발 열정 정도는?", answerType: "scale", scaleMin: "쉬고 싶어 😴", scaleMax: "열공 모드 📚" },
  { id: 3072, category: "honest", content: "내 눈치 레벨은?", answerType: "scale", scaleMin: "눈치 제로 🤷", scaleMax: "공감왕 🫡" },
  { id: 3073, category: "between", content: "우리 취미 맞는 정도는?", answerType: "scale", scaleMin: "완전 달라 🔀", scaleMax: "같이 즐겨 🎯" },
  { id: 3074, category: "tmi", content: "오늘 게임하고 싶은 정도는?", answerType: "scale", scaleMin: "관심 없어 😶", scaleMax: "밤새 하자 🎮" },
  { id: 3075, category: "future", content: "아이 갖고 싶은 정도는?", answerType: "scale", scaleMin: "아직 먼 일 🤚", scaleMax: "빨리 만나고파 👶" },
  { id: 3076, category: "honest", content: "내 사진 찍는 실력은?", answerType: "scale", scaleMin: "흔들려 📸", scaleMax: "작가급 🖼️" },
  { id: 3077, category: "between", content: "최근 감사한 정도는?", answerType: "scale", scaleMin: "보통 🙂", scaleMax: "매일 감사 🙏" },
  { id: 3078, category: "tmi", content: "넷플릭스 보고 싶은 정도는?", answerType: "scale", scaleMin: "별로 📵", scaleMax: "정주행 각 🍿" },
  { id: 3079, category: "values", content: "환경 보호 실천 정도는?", answerType: "scale", scaleMin: "무관심 😅", scaleMax: "에코 라이프 🌿" },
  { id: 3080, category: "between", content: "서로 존중하는 정도는?", answerType: "scale", scaleMin: "노력 중 😐", scaleMax: "서로 존경 💎" },
  { id: 3081, category: "honest", content: "내 금손 레벨은?", answerType: "scale", scaleMin: "똥손 🫠", scaleMax: "만능 금손 ✋" },
  { id: 3082, category: "tmi", content: "지금 쇼핑하고 싶은 정도는?", answerType: "scale", scaleMin: "절약 모드 💰", scaleMax: "지름신 강림 🛒" },
  { id: 3083, category: "future", content: "반려동물 키우고 싶은 정도는?", answerType: "scale", scaleMin: "아직 먼 일 🤔", scaleMax: "당장 데려와 🐶" },
  { id: 3084, category: "pet", content: "동물 영상 보는 빈도는?", answerType: "scale", scaleMin: "가끔 📱", scaleMax: "매일 본다 🐈" },
  { id: 3085, category: "between", content: "우리 비밀 없는 정도는?", answerType: "scale", scaleMin: "조금 있어 🤫", scaleMax: "다 오픈 🔓" },
  { id: 3086, category: "honest", content: "내 멀티태스킹 능력은?", answerType: "scale", scaleMin: "한 개도 벅차 😵", scaleMax: "척척 해결 🦸" },
  { id: 3087, category: "tmi", content: "주말 기대하는 정도는?", answerType: "scale", scaleMin: "평일과 같아 😑", scaleMax: "벌써 설레 🎊" },
  { id: 3088, category: "values", content: "독서량에 만족하는 정도는?", answerType: "scale", scaleMin: "책 안 읽어 📵", scaleMax: "독서왕 📖" },
  { id: 3089, category: "between", content: "함께 요리하고 싶은 정도는?", answerType: "scale", scaleMin: "각자 먹자 🍱", scaleMax: "같이 만들자 👩‍🍳" },
  { id: 3090, category: "honest", content: "내 방향감각은?", answerType: "scale", scaleMin: "길치 🧭", scaleMax: "내비 필요 없어 🗺️" },
  { id: 3091, category: "future", content: "이직/전직 욕구 정도는?", answerType: "scale", scaleMin: "만족해 😊", scaleMax: "탈출하고파 🚀" },
  { id: 3092, category: "tmi", content: "오늘 커피 당기는 정도는?", answerType: "scale", scaleMin: "필요 없어 🫖", scaleMax: "지금 당장 ☕" },
  { id: 3093, category: "pet", content: "동물과 교감하는 능력은?", answerType: "scale", scaleMin: "서툴러 😅", scaleMax: "동물 통역사 🐾" },
  { id: 3094, category: "between", content: "상대방 칭찬하는 정도는?", answerType: "scale", scaleMin: "쑥스러워 😳", scaleMax: "매일 칭찬 🏅" },
  { id: 3095, category: "values", content: "소확행 느끼는 정도는?", answerType: "scale", scaleMin: "무덤덤 😶", scaleMax: "매일 소확행 🍀" },
  { id: 3096, category: "honest", content: "내 아침형/저녁형 정도는?", answerType: "scale", scaleMin: "올빼미 🦉", scaleMax: "아침형 인간 🌅" },
  { id: 3097, category: "tmi", content: "지금 라면 먹고 싶은 정도는?", answerType: "scale", scaleMin: "괜찮아 🙅", scaleMax: "이미 물 끓여 🍜" },
  { id: 3098, category: "between", content: "서로 표현 잘하는 정도는?", answerType: "scale", scaleMin: "부족해 🤐", scaleMax: "매일 표현 💓" },
  { id: 3099, category: "future", content: "새로운 도전 욕구는?", answerType: "scale", scaleMin: "현재가 좋아 🏠", scaleMax: "모험하고파 🧗" },
  { id: 3100, category: "honest", content: "내 소통 능력은?", answerType: "scale", scaleMin: "말문 막혀 😶", scaleMax: "대화의 달인 🗣️" },
  { id: 3101, category: "pet", content: "펫 사진 찍는 빈도는?", answerType: "scale", scaleMin: "가끔 📷", scaleMax: "하루 100장 🤳" },
  { id: 3102, category: "tmi", content: "오늘 노래 듣고 싶은 정도는?", answerType: "scale", scaleMin: "조용히 🤫", scaleMax: "뮤직 풀볼륨 🎧" },
  { id: 3103, category: "between", content: "우리 추억 많은 정도는?", answerType: "scale", scaleMin: "아직 부족 📸", scaleMax: "앨범 가득 💝" },
  { id: 3104, category: "values", content: "봉사 정신 레벨은?", answerType: "scale", scaleMin: "귀찮아 😅", scaleMax: "봉사왕 🤲" },
  { id: 3105, category: "honest", content: "내 체력 레벨은?", answerType: "scale", scaleMin: "금방 지쳐 🫠", scaleMax: "마라톤 가능 🏃" },
  { id: 3106, category: "between", content: "우리 가치관 맞는 정도는?", answerType: "scale", scaleMin: "많이 달라 🔀", scaleMax: "찰떡 궁합 🎯" },
  { id: 3107, category: "tmi", content: "오늘 SNS 보고 싶은 정도는?", answerType: "scale", scaleMin: "디지털 디톡스 📵", scaleMax: "무한 스크롤 📱" },
  { id: 3108, category: "future", content: "해외여행 가고 싶은 정도는?", answerType: "scale", scaleMin: "국내가 좋아 🇰🇷", scaleMax: "비행기 타자 ✈️" },
  { id: 3109, category: "honest", content: "내 리액션 레벨은?", answerType: "scale", scaleMin: "무표정 😐", scaleMax: "오버 리액션 🤩" },
  { id: 3110, category: "pet", content: "동물 간식 사주고 싶은 정도는?", answerType: "scale", scaleMin: "적당히 🙂", scaleMax: "다 사줄게 🦴" },
  { id: 3111, category: "between", content: "우리 대화 깊이에 만족도는?", answerType: "scale", scaleMin: "피상적 😕", scaleMax: "영혼까지 💫" },
  { id: 3112, category: "values", content: "일상 루틴 만족도는?", answerType: "scale", scaleMin: "변화 필요 🔄", scaleMax: "완벽한 루틴 ✅" },
  { id: 3113, category: "tmi", content: "지금 아이스크림 먹고 싶은 정도는?", answerType: "scale", scaleMin: "추워 🥶", scaleMax: "당장 먹자 🍦" },
  { id: 3114, category: "honest", content: "내 결단력 레벨은?", answerType: "scale", scaleMin: "우유부단 🤷", scaleMax: "칼같은 결정 ⚔️" },
  { id: 3115, category: "between", content: "서로 위로해주는 정도는?", answerType: "scale", scaleMin: "서툴러 😅", scaleMax: "든든한 안식처 🫶" },
  { id: 3116, category: "future", content: "새 기술 배우고 싶은 정도는?", answerType: "scale", scaleMin: "현재 충분 🙂", scaleMax: "배움 욕구 폭발 📚" },
  { id: 3117, category: "tmi", content: "오늘 낮잠 자고 싶은 정도는?", answerType: "scale", scaleMin: "멀쩡해 😊", scaleMax: "눈이 감겨 😪" },
];
