import type { Question } from "@/types/question";

/** 추가 점수형 질문 Part 3 (ID 3201~3300) */
export const SCALE_EXTRA_3: Question[] = [
  { id: 3201, category: "between", content: "오늘 너한테 사랑받는 느낌이야?", answerType: "scale", scaleMin: "조금 아쉬워 😌", scaleMax: "충분해 💖" },
  { id: 3202, category: "honest", content: "요즘 내 표정은 어때?", answerType: "scale", scaleMin: "좀 굳었어 😐", scaleMax: "밝아 😊" },
  { id: 3203, category: "tmi", content: "지금 초콜릿 먹고 싶은 마음은?", answerType: "scale", scaleMin: "괜찮아 🙅", scaleMax: "당장 먹고파 🍫" },
  { id: 3204, category: "values", content: "요즘 돈 관리 잘되고 있어?", answerType: "scale", scaleMin: "좀 새고 있어 💸", scaleMax: "잘하고 있어 💰" },
  { id: 3205, category: "future", content: "우리 10년 후가 기대돼?", answerType: "scale", scaleMin: "잘 모르겠어 🤔", scaleMax: "너무 기대돼 🌟" },
  { id: 3206, category: "pet", content: "강아지랑 산책하는 상상 자주 해?", answerType: "scale", scaleMin: "거의 안 해 🐕", scaleMax: "매일 해 🚶‍♂️" },
  { id: 3207, category: "between", content: "우리 오늘 하루 얼마나 생각했어?", answerType: "scale", scaleMin: "가끔 🙂", scaleMax: "계속 💭" },
  { id: 3208, category: "honest", content: "요즘 내 자존감은 어때?", answerType: "scale", scaleMin: "좀 낮아 🫥", scaleMax: "단단해 🛡️" },
  { id: 3209, category: "tmi", content: "지금 라면 끓이고 싶어?", answerType: "scale", scaleMin: "배 안 고파 🙂", scaleMax: "끓이고파 🍜" },
  { id: 3210, category: "values", content: "나 자신을 아끼는 정도는?", answerType: "scale", scaleMin: "좀 부족해 😔", scaleMax: "잘 챙겨 💝" },
  { id: 3211, category: "future", content: "함께 살 집 구체적으로 그려봤어?", answerType: "scale", scaleMin: "막연해 🏠", scaleMax: "자주 그려 🖼️" },
  { id: 3212, category: "pet", content: "고양이 키우는 건 어때?", answerType: "scale", scaleMin: "별로 🐾", scaleMax: "좋아 😸" },
  { id: 3213, category: "between", content: "서로 눈 마주치는 시간 충분해?", answerType: "scale", scaleMin: "부족해 👀", scaleMax: "충분해 🥰" },
  { id: 3214, category: "honest", content: "오늘 아침 컨디션 어땠어?", answerType: "scale", scaleMin: "별로였어 😵", scaleMax: "상쾌했어 🌞" },
  { id: 3215, category: "tmi", content: "지금 잠자고 싶은 마음은?", answerType: "scale", scaleMin: "안 졸려 😳", scaleMax: "눕고파 🛌" },
  { id: 3216, category: "values", content: "요즘 취미 활동 만족도는?", answerType: "scale", scaleMin: "비어있어 🫙", scaleMax: "재밌어 🎨" },
  { id: 3217, category: "future", content: "같이 여행 계획 세우고 싶어?", answerType: "scale", scaleMin: "나중에 🗺️", scaleMax: "지금 당장 ✈️" },
  { id: 3218, category: "pet", content: "반려동물 관련 영상 자주 봐?", answerType: "scale", scaleMin: "가끔 📺", scaleMax: "매일 봐 🎬" },
  { id: 3219, category: "between", content: "서로에게 솔직한 편이야?", answerType: "scale", scaleMin: "조금 숨겨 🤫", scaleMax: "다 말해 💬" },
  { id: 3220, category: "honest", content: "내가 잘 웃는 편이야?", answerType: "scale", scaleMin: "조용한 편 😶", scaleMax: "잘 웃어 😄" },
  { id: 3221, category: "tmi", content: "지금 스트레스 지수는?", answerType: "scale", scaleMin: "평온해 😌", scaleMax: "폭발 직전 💥" },
  { id: 3222, category: "values", content: "환경 보호에 관심 있어?", answerType: "scale", scaleMin: "조금 🌱", scaleMax: "실천해 ♻️" },
  { id: 3223, category: "future", content: "결혼하고 싶은 마음은 얼마나?", answerType: "scale", scaleMin: "좀 이르다 🌱", scaleMax: "하고 싶어 💍" },
  { id: 3224, category: "pet", content: "동물 알러지 걱정돼?", answerType: "scale", scaleMin: "전혀 🙆", scaleMax: "걱정돼 🤧" },
  { id: 3225, category: "between", content: "오늘 연락 빈도 만족해?", answerType: "scale", scaleMin: "더 하고파 📵", scaleMax: "딱 좋아 📱" },
  { id: 3226, category: "honest", content: "내가 질투 많은 편이야?", answerType: "scale", scaleMin: "쿨해 🧊", scaleMax: "조금 있어 🔥" },
  { id: 3227, category: "tmi", content: "오늘 물 많이 마셨어?", answerType: "scale", scaleMin: "거의 안 마셨어 🏜️", scaleMax: "충분해 💧" },
  { id: 3228, category: "values", content: "예술이나 공연에 관심 있어?", answerType: "scale", scaleMin: "별로 🎭", scaleMax: "많아 🎨" },
  { id: 3229, category: "future", content: "우리 노후 이야기 해보고 싶어?", answerType: "scale", scaleMin: "너무 일러 🍼", scaleMax: "해보고 싶어 👴👵" },
  { id: 3230, category: "pet", content: "반려동물 이름 생각해본 적 있어?", answerType: "scale", scaleMin: "아직 🤔", scaleMax: "몇 개 있어 📝" },
  { id: 3231, category: "between", content: "서로 응원하는 정도는?", answerType: "scale", scaleMin: "조용해 🌫️", scaleMax: "크게 해 📣" },
  { id: 3232, category: "honest", content: "내가 정리정돈 잘해?", answerType: "scale", scaleMin: "어지러워 🌀", scaleMax: "깔끔해 🧹" },
  { id: 3233, category: "tmi", content: "오늘 커피 마셨어?", answerType: "scale", scaleMin: "안 마셨어 🙅", scaleMax: "여러 잔 ☕" },
  { id: 3234, category: "values", content: "자원봉사 해보고 싶은 마음은?", answerType: "scale", scaleMin: "별로 🙈", scaleMax: "해보고 싶어 🙌" },
  { id: 3235, category: "future", content: "유학이나 해외 거주 어때?", answerType: "scale", scaleMin: "한국이 좋아 🇰🇷", scaleMax: "나가고 싶어 🌏" },
  { id: 3236, category: "pet", content: "반려동물 SNS 팔로우해?", answerType: "scale", scaleMin: "안 해 📵", scaleMax: "많이 해 📸" },
  { id: 3237, category: "between", content: "오늘 네가 더 사랑스러워 보여?", answerType: "scale", scaleMin: "평소와 비슷 🙂", scaleMax: "엄청 ✨" },
  { id: 3238, category: "honest", content: "요즘 잠자리 질은 어때?", answerType: "scale", scaleMin: "뒤척여 😵", scaleMax: "푹 자 🛌" },
  { id: 3239, category: "tmi", content: "지금 치킨 먹고 싶어?", answerType: "scale", scaleMin: "아니 🙂", scaleMax: "시키자 🍗" },
  { id: 3240, category: "values", content: "요즘 삶의 재미는?", answerType: "scale", scaleMin: "심심해 😑", scaleMax: "재밌어 🎉" },
  { id: 3241, category: "future", content: "자녀 계획 생각해본 적 있어?", answerType: "scale", scaleMin: "아직 🌱", scaleMax: "생각해봤어 👶" },
  { id: 3242, category: "pet", content: "반려동물 사료 공부 의욕은?", answerType: "scale", scaleMin: "별로 🧐", scaleMax: "해보고 싶어 📖" },
  { id: 3243, category: "between", content: "우리 싸운 뒤 회복 속도는?", answerType: "scale", scaleMin: "좀 오래 걸려 🐢", scaleMax: "빨라 🐇" },
  { id: 3244, category: "honest", content: "내 감정 표현은 어떻게?", answerType: "scale", scaleMin: "숨기는 편 🙊", scaleMax: "잘 표현해 🎭" },
  { id: 3245, category: "tmi", content: "오늘 스트레칭 했어?", answerType: "scale", scaleMin: "안 했어 🙅", scaleMax: "잘했어 🧘" },
  { id: 3246, category: "values", content: "지금 직업 만족도는?", answerType: "scale", scaleMin: "아쉬워 😔", scaleMax: "만족해 💼" },
  { id: 3247, category: "future", content: "창업이나 프리랜서 의향은?", answerType: "scale", scaleMin: "안정이 좋아 🏢", scaleMax: "도전하고 싶어 🚀" },
  { id: 3248, category: "pet", content: "반려동물과 잠자는 상상 해봤어?", answerType: "scale", scaleMin: "별로 🛏️", scaleMax: "매일 해 😍" },
  { id: 3249, category: "between", content: "우리 추억 만들기 만족도는?", answerType: "scale", scaleMin: "좀 아쉬워 😌", scaleMax: "충분해 📸" },
  { id: 3250, category: "honest", content: "오늘 내 인내심은?", answerType: "scale", scaleMin: "바닥 🫠", scaleMax: "넉넉해 🧘" },
  { id: 3251, category: "tmi", content: "지금 샤워하고 싶어?", answerType: "scale", scaleMin: "괜찮아 🙂", scaleMax: "하고파 🚿" },
  { id: 3252, category: "values", content: "새로운 거 배우는 의지는?", answerType: "scale", scaleMin: "귀찮아 😴", scaleMax: "불타 🔥" },
  { id: 3253, category: "future", content: "대도시 계속 살고 싶어?", answerType: "scale", scaleMin: "시골이 좋아 🌾", scaleMax: "도시 좋아 🏙️" },
  { id: 3254, category: "pet", content: "반려동물 훈련 관심 정도는?", answerType: "scale", scaleMin: "귀찮아 🙄", scaleMax: "공부하고파 🎓" },
  { id: 3255, category: "between", content: "둘만의 비밀 많은 편이야?", answerType: "scale", scaleMin: "별로 🤐", scaleMax: "많아 🤫" },
  { id: 3256, category: "honest", content: "내가 약속 잘 지켜?", answerType: "scale", scaleMin: "종종 늦어 ⏰", scaleMax: "칼같이 ⏱️" },
  { id: 3257, category: "tmi", content: "오늘 걷기 얼마나 했어?", answerType: "scale", scaleMin: "거의 안 걸어 🛋️", scaleMax: "많이 걸어 🚶" },
  { id: 3258, category: "values", content: "영적/명상 쪽에 관심 있어?", answerType: "scale", scaleMin: "별로 🤷", scaleMax: "관심 많아 🧘‍♀️" },
  { id: 3259, category: "future", content: "5년 안에 큰 변화 오길 바라?", answerType: "scale", scaleMin: "안정이 좋아 🛋️", scaleMax: "원해 🌊" },
  { id: 3260, category: "pet", content: "반려동물 병원비 걱정돼?", answerType: "scale", scaleMin: "괜찮아 💪", scaleMax: "걱정돼 😰" },
  { id: 3261, category: "between", content: "우리 분위기 전환 잘하는 편?", answerType: "scale", scaleMin: "어색해져 😶", scaleMax: "빨리 풀려 🎈" },
  { id: 3262, category: "honest", content: "내가 운동 좋아하는 편이야?", answerType: "scale", scaleMin: "싫어 🙅", scaleMax: "좋아 💪" },
  { id: 3263, category: "tmi", content: "지금 빙수 먹고 싶어?", answerType: "scale", scaleMin: "별로 🙅", scaleMax: "땡겨 🍧" },
  { id: 3264, category: "values", content: "친구 관계에 만족해?", answerType: "scale", scaleMin: "좀 아쉬워 😔", scaleMax: "풍족해 🤗" },
  { id: 3265, category: "future", content: "반려동물 입양 현실적으로 봐?", answerType: "scale", scaleMin: "꿈에 가까워 🌈", scaleMax: "충분히 가능 📅" },
  { id: 3266, category: "pet", content: "동물 카페 가고 싶어?", answerType: "scale", scaleMin: "별로 🙅", scaleMax: "가자 🐾" },
  { id: 3267, category: "between", content: "상대방 가족에 대한 친밀감은?", answerType: "scale", scaleMin: "어색해 😅", scaleMax: "가까워 👨‍👩‍👧" },
  { id: 3268, category: "honest", content: "내 공감 능력은?", answerType: "scale", scaleMin: "둔한 편 😅", scaleMax: "잘 공감해 🫶" },
  { id: 3269, category: "tmi", content: "지금 아이스크림 땡겨?", answerType: "scale", scaleMin: "별로 🙅", scaleMax: "먹고파 🍦" },
  { id: 3270, category: "values", content: "종교나 신념 있어?", answerType: "scale", scaleMin: "없어 🤷", scaleMax: "확고해 🙏" },
  { id: 3271, category: "future", content: "내 집 마련 목표 강해?", answerType: "scale", scaleMin: "천천히 🏠", scaleMax: "꼭 할래 🏡" },
  { id: 3272, category: "pet", content: "반려동물 여행 동반 욕구는?", answerType: "scale", scaleMin: "집이 낫대 🏠", scaleMax: "같이 가고파 🚗" },
  { id: 3273, category: "between", content: "우리 서로 성장하고 있어?", answerType: "scale", scaleMin: "정체 느낌 🧱", scaleMax: "같이 성장 🌱" },
  { id: 3274, category: "honest", content: "내 계획성은 어때?", answerType: "scale", scaleMin: "즉흥적 🎲", scaleMax: "체계적 📋" },
  { id: 3275, category: "tmi", content: "오늘 독서 시간 있었어?", answerType: "scale", scaleMin: "없었어 🙅", scaleMax: "충분해 📚" },
  { id: 3276, category: "values", content: "건강식 관심도는?", answerType: "scale", scaleMin: "별로 🍔", scaleMax: "많아 🥗" },
  { id: 3277, category: "future", content: "같이 반려식물 키워볼까?", answerType: "scale", scaleMin: "귀찮아 🥀", scaleMax: "좋아 🪴" },
  { id: 3278, category: "pet", content: "반려동물 용품 관심도?", answerType: "scale", scaleMin: "별로 🧸", scaleMax: "구경 자주 해 🛒" },
  { id: 3279, category: "between", content: "서로 칭찬 자주 해?", answerType: "scale", scaleMin: "부족해 😶", scaleMax: "매일 해 👏" },
  { id: 3280, category: "honest", content: "내 시간 약속 감각은?", answerType: "scale", scaleMin: "여유 많아 ⏳", scaleMax: "정확 ⏰" },
  { id: 3281, category: "tmi", content: "지금 단 거 땡겨?", answerType: "scale", scaleMin: "짠 거 생각나 🧂", scaleMax: "단 거 최고 🍭" },
  { id: 3282, category: "values", content: "사회 이슈에 관심 많아?", answerType: "scale", scaleMin: "별로 🤷", scaleMax: "많아 📰" },
  { id: 3283, category: "future", content: "공동 명의 자산 생각해봤어?", answerType: "scale", scaleMin: "아직 🫣", scaleMax: "고민 중 💰" },
  { id: 3284, category: "pet", content: "강아지 vs 고양이 선호?", answerType: "scale", scaleMin: "고양이파 😺", scaleMax: "강아지파 🐶" },
  { id: 3285, category: "between", content: "우리 장난 치는 빈도는?", answerType: "scale", scaleMin: "적어 🤏", scaleMax: "매일 🥳" },
  { id: 3286, category: "honest", content: "내 감정 조절 점수는?", answerType: "scale", scaleMin: "기복 있어 🎢", scaleMax: "안정적 🧘" },
  { id: 3287, category: "tmi", content: "오늘 SNS 많이 봤어?", answerType: "scale", scaleMin: "안 봤어 📵", scaleMax: "많이 봤어 📱" },
  { id: 3288, category: "values", content: "기부나 후원 참여 의향은?", answerType: "scale", scaleMin: "아직 😅", scaleMax: "해보고 싶어 💝" },
  { id: 3289, category: "future", content: "이직/전직 마음 있어?", answerType: "scale", scaleMin: "지금이 좋아 💼", scaleMax: "고민 중 🌀" },
  { id: 3290, category: "pet", content: "반려동물 미용 관심은?", answerType: "scale", scaleMin: "별로 ✂️", scaleMax: "꾸며주고파 💇" },
  { id: 3291, category: "between", content: "서로 혼자 시간 존중해?", answerType: "scale", scaleMin: "아쉬워 🙁", scaleMax: "잘 존중해 🫶" },
  { id: 3292, category: "honest", content: "내 도전 의식은?", answerType: "scale", scaleMin: "안전 우선 🛡️", scaleMax: "도전 🌊" },
  { id: 3293, category: "tmi", content: "지금 산책 가고 싶어?", answerType: "scale", scaleMin: "집 좋아 🛋️", scaleMax: "나가자 🚶" },
  { id: 3294, category: "values", content: "가족 관계 만족도는?", answerType: "scale", scaleMin: "복잡해 😔", scaleMax: "좋아 👨‍👩‍👧" },
  { id: 3295, category: "future", content: "은퇴 후 삶 구체적으로?", answerType: "scale", scaleMin: "막연 🌫️", scaleMax: "구체적 🗺️" },
  { id: 3296, category: "pet", content: "고양이 종 중 선호 있어?", answerType: "scale", scaleMin: "딱히 🐱", scaleMax: "있어 😻" },
  { id: 3297, category: "between", content: "우리 서로 비밀 공유 편하지?", answerType: "scale", scaleMin: "조심스러워 😶", scaleMax: "편해 💬" },
  { id: 3298, category: "honest", content: "내가 부지런한 편?", answerType: "scale", scaleMin: "좀 늘어져 🦥", scaleMax: "부지런해 🐜" },
  { id: 3299, category: "tmi", content: "지금 영화 보고 싶어?", answerType: "scale", scaleMin: "안 땡겨 🙅", scaleMax: "보자 🎬" },
  { id: 3300, category: "values", content: "자기계발 시간 만족해?", answerType: "scale", scaleMin: "부족해 📉", scaleMax: "충분해 📈" },
];
