import type { Question } from "@/types/question";

/** 점수형 질문 (1~10) — 모든 카테고리 혼합 */
export const SCALE_QUESTIONS: Question[] = [
  { id: 3001, category: "between", content: "오늘 우리 사이는 어때?", answerType: "scale", scaleMin: "아쉬워 😢", scaleMax: "너무 좋아 🥰" },
  { id: 3002, category: "honest", content: "요즘 내가 잘하고 있어?", answerType: "scale", scaleMin: "조금만 더 😅", scaleMax: "충분해 ✨" },
  { id: 3003, category: "between", content: "지금 보고 싶은 마음은?", answerType: "scale", scaleMin: "조금 🙂", scaleMax: "너무 보고파 💕" },
  { id: 3004, category: "tmi", content: "오늘 하루 피곤했어?", answerType: "scale", scaleMin: "멀쩡해 💪", scaleMax: "푹 쉬고 싶어 😵" },
  { id: 3005, category: "between", content: "우리 대화 빈도는 어때?", answerType: "scale", scaleMin: "더 하고파 📵", scaleMax: "딱 좋아 💬" },
  { id: 3006, category: "honest", content: "내 요리 솜씨는 어때?", answerType: "scale", scaleMin: "조금 걱정 🔥", scaleMax: "맛있어 👨‍🍳" },
  { id: 3007, category: "tmi", content: "지금 배고픈 정도는?", answerType: "scale", scaleMin: "괜찮아 😊", scaleMax: "빨리 먹자 🍽️" },
  { id: 3008, category: "between", content: "요즘 우리 스킨십은 어때?", answerType: "scale", scaleMin: "더 하고파 🙈", scaleMax: "딱 좋아 🫂" },
  { id: 3009, category: "values", content: "요즘 행복하게 지내고 있어?", answerType: "scale", scaleMin: "좀 지쳐 😔", scaleMax: "너무 행복해 ☀️" },
  { id: 3010, category: "honest", content: "내 패션 감각은 어때?", answerType: "scale", scaleMin: "조금만 더 👀", scaleMax: "멋져 ✨" },
  { id: 3011, category: "between", content: "나한테 아직 설레?", answerType: "scale", scaleMin: "편안해 🧸", scaleMax: "심쿵해 💘" },
  { id: 3012, category: "tmi", content: "오늘 기분은 어때?", answerType: "scale", scaleMin: "그저 그래 😞", scaleMax: "기분 좋아 😆" },
  { id: 3013, category: "values", content: "일과 연애 균형은 어때?", answerType: "scale", scaleMin: "좀 아쉬워 ⚖️", scaleMax: "잘 맞아 🎯" },
  { id: 3014, category: "honest", content: "내 잠버릇은 어떤 편이야?", answerType: "scale", scaleMin: "천사 😇", scaleMax: "좀 심해 ⚔️" },
  { id: 3015, category: "between", content: "우리 여행 궁합은 어때?", answerType: "scale", scaleMin: "좀 달라 😅", scaleMax: "찰떡이야 🤝" },
  { id: 3016, category: "tmi", content: "지금 졸린 정도는?", answerType: "scale", scaleMin: "멀쩡해 👀", scaleMax: "이미 꿈속 😴" },
  { id: 3017, category: "honest", content: "내 애교는 어떤 편이야?", answerType: "scale", scaleMin: "츤데레 😤", scaleMax: "애교 가득 🥰" },
  { id: 3018, category: "between", content: "우리 음식 취향은 어때?", answerType: "scale", scaleMin: "좀 달라 🤷", scaleMax: "찰떡이야 🍽️" },
  { id: 3019, category: "values", content: "요즘 자존감은 어때?", answerType: "scale", scaleMin: "좀 낮아 📉", scaleMax: "괜찮아 📈" },
  { id: 3020, category: "honest", content: "내 운전 솜씨는 어때?", answerType: "scale", scaleMin: "좀 조심해 🫣", scaleMax: "든든해 🏎️" },
  { id: 3021, category: "between", content: "나한테 서운한 거 있어?", answerType: "scale", scaleMin: "전혀 없어 😊", scaleMax: "조금 있어 😔" },
  { id: 3022, category: "tmi", content: "오늘 귀찮은 정도는?", answerType: "scale", scaleMin: "의욕 넘쳐 🔥", scaleMax: "쉬고 싶어 🦥" },
  { id: 3023, category: "between", content: "우리 유머 코드는 어때?", answerType: "scale", scaleMin: "좀 달라 🌍", scaleMax: "딱 맞아 🧠" },
  { id: 3024, category: "honest", content: "내가 집안일 잘하는 편이야?", answerType: "scale", scaleMin: "조금만 더 😅", scaleMax: "잘해 🧹" },
  { id: 3025, category: "tmi", content: "요즘 스트레스는 어때?", answerType: "scale", scaleMin: "평화로워 🕊️", scaleMax: "좀 힘들어 🌋" },
  { id: 3026, category: "between", content: "우리 화해하는 속도는 어때?", answerType: "scale", scaleMin: "느긋해 🐢", scaleMax: "금방이야 ⚡" },
  { id: 3027, category: "honest", content: "나한테 질투 느낄 때 있어?", answerType: "scale", scaleMin: "전혀 없어 😎", scaleMax: "가끔 있어 😤" },
  { id: 3028, category: "values", content: "미래가 걱정될 때 있어?", answerType: "scale", scaleMin: "별로 없어 🌈", scaleMax: "가끔 그래 😰" },
  { id: 3029, category: "between", content: "오늘 나한테 고마웠어?", answerType: "scale", scaleMin: "보통이야 🙂", scaleMax: "너무 고마워 🥹" },
  { id: 3030, category: "tmi", content: "카페 가고 싶은 마음은?", answerType: "scale", scaleMin: "괜찮아 🏠", scaleMax: "가고 싶어 ☕" },
  { id: 3031, category: "between", content: "나랑 있으면 편안해?", answerType: "scale", scaleMin: "좀 긴장돼 😳", scaleMax: "집처럼 편해 🏠" },
  { id: 3032, category: "honest", content: "최근 나한테 아쉬웠던 거 있어?", answerType: "scale", scaleMin: "전혀 없어 ☺️", scaleMax: "조금 있어 😔" },
  { id: 3033, category: "values", content: "요즘 저축 잘 하고 있어?", answerType: "scale", scaleMin: "좀 부족해 💸", scaleMax: "잘하고 있어 🏦" },
  { id: 3034, category: "between", content: "우리 기념일 잘 챙기고 있어?", answerType: "scale", scaleMin: "좀 부족해 📅", scaleMax: "잘 챙겨 🎂" },
  { id: 3035, category: "tmi", content: "여행 떠나고 싶은 마음은?", answerType: "scale", scaleMin: "집이 좋아 🏠", scaleMax: "떠나고 싶어 ✈️" },
];
