import type { Question } from "@/types/question";

/** 추가 점수형 질문 Part 1 (ID 3036~3117) */
export const SCALE_EXTRA_1: Question[] = [
  { id: 3036, category: "honest", content: "내 노래 실력은 어때?", answerType: "scale", scaleMin: "좀 아쉬워 🎤", scaleMax: "잘해 🎶" },
  { id: 3037, category: "between", content: "요즘 우리 서로 믿는 정도는?", answerType: "scale", scaleMin: "좀 걱정돼 😟", scaleMax: "완전 믿어 🤝" },
  { id: 3038, category: "tmi", content: "오늘 에너지는 어때?", answerType: "scale", scaleMin: "방전 🪫", scaleMax: "완충 🔋" },
  { id: 3039, category: "values", content: "요즘 건강은 어때?", answerType: "scale", scaleMin: "좀 챙겨야 해 🏥", scaleMax: "건강해 💪" },
  { id: 3040, category: "future", content: "미래가 기대돼?", answerType: "scale", scaleMin: "좀 걱정돼 😨", scaleMax: "설레 🌟" },
  { id: 3041, category: "pet", content: "반려동물 보고 싶은 마음은?", answerType: "scale", scaleMin: "조금 🐾", scaleMax: "당장 보고파 😭" },
  { id: 3042, category: "honest", content: "내 춤 실력은 어때?", answerType: "scale", scaleMin: "귀여워 🤖", scaleMax: "잘 춰 💃" },
  { id: 3043, category: "between", content: "서로 이해하는 편이야?", answerType: "scale", scaleMin: "조금 더 노력 🤔", scaleMax: "마음을 읽어 🧠" },
  { id: 3044, category: "tmi", content: "오늘 사람 만나고 싶어?", answerType: "scale", scaleMin: "혼자 있고파 🐚", scaleMax: "사람이 좋아 🥳" },
  { id: 3045, category: "values", content: "요즘 취미 만족해?", answerType: "scale", scaleMin: "뭔가 아쉬워 😶", scaleMax: "즐거워 🎨" },
  { id: 3046, category: "future", content: "결혼 생각해본 적 있어?", answerType: "scale", scaleMin: "아직 천천히 🙅", scaleMax: "같이 가고 싶어 💒" },
  { id: 3047, category: "honest", content: "내 유머 감각은 어때?", answerType: "scale", scaleMin: "좀 아쉬워 😐", scaleMax: "웃겨 🤣" },
  { id: 3048, category: "between", content: "요즘 배려 받고 있다고 느껴?", answerType: "scale", scaleMin: "좀 아쉬워 😢", scaleMax: "감동이야 🥹" },
  { id: 3049, category: "tmi", content: "요즘 창의력은 어때?", answerType: "scale", scaleMin: "좀 낮아 🧱", scaleMax: "넘쳐 💡" },
  { id: 3050, category: "pet", content: "펫 돌보는 자신감은?", answerType: "scale", scaleMin: "아직 배우는 중 🐣", scaleMax: "잘할 수 있어 🏆" },
  { id: 3051, category: "values", content: "직장/학교 생활은 어때?", answerType: "scale", scaleMin: "좀 힘들어 😩", scaleMax: "괜찮아 🏢" },
  { id: 3052, category: "between", content: "우리 데이트 만족스러워?", answerType: "scale", scaleMin: "좀 아쉬워 😕", scaleMax: "매번 좋아 ✨" },
  { id: 3053, category: "honest", content: "내 인내심은 어떤 편이야?", answerType: "scale", scaleMin: "좀 급해 🔥", scaleMax: "잘 기다려 🧘" },
  { id: 3054, category: "tmi", content: "단 거 먹고 싶은 마음은?", answerType: "scale", scaleMin: "괜찮아 🙂", scaleMax: "디저트 가자 🍰" },
  { id: 3055, category: "future", content: "같이 살고 싶은 마음은?", answerType: "scale", scaleMin: "아직 천천히 🤚", scaleMax: "같이 살래 🏠" },
  { id: 3056, category: "between", content: "요즘 연락 빈도는 어때?", answerType: "scale", scaleMin: "더 하고파 📱", scaleMax: "딱 좋아 💌" },
  { id: 3057, category: "honest", content: "내 정리정돈 어떤 편이야?", answerType: "scale", scaleMin: "좀 아쉬워 🗑️", scaleMax: "깔끔해 🧹" },
  { id: 3058, category: "tmi", content: "오늘 의욕은 어때?", answerType: "scale", scaleMin: "좀 없어 🦥", scaleMax: "넘쳐 🔥" },
  { id: 3059, category: "values", content: "가족관계는 어때?", answerType: "scale", scaleMin: "좀 어려워 😣", scaleMax: "화목해 👨‍👩‍👧‍👦" },
  { id: 3060, category: "pet", content: "동물 좋아하는 편이야?", answerType: "scale", scaleMin: "보통 🙂", scaleMax: "진짜 좋아해 🐕" },
  { id: 3061, category: "between", content: "서로 응원해주고 있어?", answerType: "scale", scaleMin: "좀 더 해주면 😔", scaleMax: "든든해 📣" },
  { id: 3062, category: "honest", content: "내 시간관리 어떤 편이야?", answerType: "scale", scaleMin: "좀 느긋해 🐢", scaleMax: "잘해 ⏰" },
  { id: 3063, category: "tmi", content: "운동하고 싶은 마음은?", answerType: "scale", scaleMin: "쉬고 싶어 🛋️", scaleMax: "움직이자 🏋️" },
  { id: 3064, category: "future", content: "여행 계획 세우고 싶어?", answerType: "scale", scaleMin: "나중에 😅", scaleMax: "지금 같이 🗺️" },
  { id: 3065, category: "values", content: "요즘 친구관계는 어때?", answerType: "scale", scaleMin: "좀 외로워 😢", scaleMax: "좋아 🎉" },
  { id: 3066, category: "between", content: "우리 함께 성장하고 있어?", answerType: "scale", scaleMin: "좀 멈춘 느낌 📉", scaleMax: "함께 성장해 📈" },
  { id: 3067, category: "honest", content: "내 계획성은 어때?", answerType: "scale", scaleMin: "즉흥적이야 🎲", scaleMax: "잘 세워 📋" },
  { id: 3068, category: "tmi", content: "치킨 먹고 싶은 마음은?", answerType: "scale", scaleMin: "보통 🙂", scaleMax: "당장 시키자 🍗" },
  { id: 3069, category: "between", content: "나한테 의지가 돼?", answerType: "scale", scaleMin: "독립적이야 🧍", scaleMax: "기댈게 🫂" },
  { id: 3070, category: "pet", content: "산책 가고 싶은 마음은?", answerType: "scale", scaleMin: "집이 좋아 🏠", scaleMax: "나가자 🐕‍🦺" },
  { id: 3071, category: "values", content: "자기계발 열정은 어때?", answerType: "scale", scaleMin: "좀 쉬고 싶어 😴", scaleMax: "열심히 하고파 📚" },
  { id: 3072, category: "honest", content: "내 눈치는 어떤 편이야?", answerType: "scale", scaleMin: "좀 서툴러 🤷", scaleMax: "잘 챙겨 🫡" },
  { id: 3073, category: "between", content: "우리 취미 잘 맞아?", answerType: "scale", scaleMin: "좀 달라 🔀", scaleMax: "같이 즐겨 🎯" },
  { id: 3074, category: "tmi", content: "오늘 게임하고 싶어?", answerType: "scale", scaleMin: "별로 😶", scaleMax: "같이 하자 🎮" },
  { id: 3075, category: "future", content: "아이 갖고 싶은 마음은?", answerType: "scale", scaleMin: "아직 천천히 🤚", scaleMax: "같이 키우고파 👶" },
  { id: 3076, category: "honest", content: "내 사진 찍는 솜씨는?", answerType: "scale", scaleMin: "좀 연습해 📸", scaleMax: "잘 찍어 🖼️" },
  { id: 3077, category: "between", content: "요즘 서로 감사하는 마음은?", answerType: "scale", scaleMin: "보통 🙂", scaleMax: "매일 감사해 🙏" },
  { id: 3078, category: "tmi", content: "넷플릭스 보고 싶은 마음은?", answerType: "scale", scaleMin: "별로 📵", scaleMax: "같이 보자 🍿" },
  { id: 3079, category: "values", content: "환경 보호 실천하고 있어?", answerType: "scale", scaleMin: "좀 부족해 😅", scaleMax: "잘하고 있어 🌿" },
  { id: 3080, category: "between", content: "서로 존중하고 있어?", answerType: "scale", scaleMin: "더 노력할게 😐", scaleMax: "잘하고 있어 💎" },
  { id: 3081, category: "honest", content: "내 손재주는 어때?", answerType: "scale", scaleMin: "좀 서툴러 🫠", scaleMax: "잘해 ✋" },
  { id: 3082, category: "tmi", content: "쇼핑하고 싶은 마음은?", answerType: "scale", scaleMin: "절약할래 💰", scaleMax: "사고 싶어 🛒" },
  { id: 3083, category: "future", content: "반려동물 키우고 싶어?", answerType: "scale", scaleMin: "아직 천천히 🤔", scaleMax: "같이 키우자 🐶" },
  { id: 3084, category: "pet", content: "동물 영상 자주 봐?", answerType: "scale", scaleMin: "가끔 📱", scaleMax: "매일 봐 🐈" },
  { id: 3085, category: "between", content: "우리 사이에 비밀 없지?", answerType: "scale", scaleMin: "조금 있어 🤫", scaleMax: "다 말해 🔓" },
  { id: 3086, category: "honest", content: "내 멀티태스킹은 어때?", answerType: "scale", scaleMin: "좀 어려워 😵", scaleMax: "잘해 🦸" },
  { id: 3087, category: "tmi", content: "주말이 기대돼?", answerType: "scale", scaleMin: "별 차이 없어 😑", scaleMax: "벌써 설레 🎊" },
  { id: 3088, category: "values", content: "요즘 책 읽고 있어?", answerType: "scale", scaleMin: "좀 안 읽어 📵", scaleMax: "열심히 읽어 📖" },
  { id: 3089, category: "between", content: "같이 요리하고 싶어?", answerType: "scale", scaleMin: "각자 먹어도 돼 🍱", scaleMax: "같이 만들자 👩‍🍳" },
  { id: 3090, category: "honest", content: "내 방향감각은 어때?", answerType: "scale", scaleMin: "좀 서툴러 🧭", scaleMax: "잘 찾아다녀 🗺️" },
  { id: 3091, category: "future", content: "이직 생각해본 적 있어?", answerType: "scale", scaleMin: "괜찮아 😊", scaleMax: "새로운 길 가고파 🚀" },
  { id: 3092, category: "tmi", content: "오늘 커피 마시고 싶어?", answerType: "scale", scaleMin: "괜찮아 🫖", scaleMax: "마시고 싶어 ☕" },
  { id: 3093, category: "pet", content: "동물과 교감 잘해?", answerType: "scale", scaleMin: "좀 서툴러 😅", scaleMax: "잘 통해 🐾" },
  { id: 3094, category: "between", content: "상대방한테 칭찬 잘 해?", answerType: "scale", scaleMin: "쑥스러워 😳", scaleMax: "매일 해 🏅" },
  { id: 3095, category: "values", content: "소소한 행복 느끼는 편이야?", answerType: "scale", scaleMin: "좀 덤덤해 😶", scaleMax: "자주 느껴 🍀" },
  { id: 3096, category: "honest", content: "아침형이야 저녁형이야?", answerType: "scale", scaleMin: "올빼미 🦉", scaleMax: "아침형 🌅" },
  { id: 3097, category: "tmi", content: "라면 먹고 싶은 마음은?", answerType: "scale", scaleMin: "괜찮아 🙅", scaleMax: "끓이고 싶어 🍜" },
  { id: 3098, category: "between", content: "서로 표현 잘하는 편이야?", answerType: "scale", scaleMin: "좀 부족해 🤐", scaleMax: "잘 표현해 💓" },
  { id: 3099, category: "future", content: "새로운 도전 해보고 싶어?", answerType: "scale", scaleMin: "지금이 좋아 🏠", scaleMax: "해보고 싶어 🧗" },
  { id: 3100, category: "honest", content: "내 소통 능력은 어때?", answerType: "scale", scaleMin: "좀 부족해 😶", scaleMax: "잘해 🗣️" },
  { id: 3101, category: "pet", content: "펫 사진 자주 찍어?", answerType: "scale", scaleMin: "가끔 📷", scaleMax: "엄청 많이 🤳" },
  { id: 3102, category: "tmi", content: "노래 듣고 싶은 마음은?", answerType: "scale", scaleMin: "조용히 있을래 🤫", scaleMax: "음악 듣자 🎧" },
  { id: 3103, category: "between", content: "우리 추억 많이 쌓았어?", answerType: "scale", scaleMin: "더 만들자 📸", scaleMax: "가득해 💝" },
  { id: 3104, category: "values", content: "봉사에 관심 있어?", answerType: "scale", scaleMin: "아직은 😅", scaleMax: "해보고 싶어 🤲" },
  { id: 3105, category: "honest", content: "내 체력은 어떤 편이야?", answerType: "scale", scaleMin: "좀 약해 🫠", scaleMax: "튼튼해 🏃" },
  { id: 3106, category: "between", content: "우리 가치관 잘 맞아?", answerType: "scale", scaleMin: "좀 달라 🔀", scaleMax: "잘 맞아 🎯" },
  { id: 3107, category: "tmi", content: "오늘 SNS 보고 싶어?", answerType: "scale", scaleMin: "쉬고 싶어 📵", scaleMax: "좀 볼래 📱" },
  { id: 3108, category: "future", content: "해외여행 가고 싶어?", answerType: "scale", scaleMin: "국내가 좋아 🇰🇷", scaleMax: "같이 가자 ✈️" },
  { id: 3109, category: "honest", content: "내 리액션은 어때?", answerType: "scale", scaleMin: "좀 조용해 😐", scaleMax: "풍부해 🤩" },
  { id: 3110, category: "pet", content: "동물 간식 사주고 싶어?", answerType: "scale", scaleMin: "적당히 🙂", scaleMax: "다 사줄게 🦴" },
  { id: 3111, category: "between", content: "우리 대화 깊이는 어때?", answerType: "scale", scaleMin: "좀 아쉬워 😕", scaleMax: "깊어서 좋아 💫" },
  { id: 3112, category: "values", content: "일상 루틴 만족해?", answerType: "scale", scaleMin: "좀 바꾸고파 🔄", scaleMax: "만족해 ✅" },
  { id: 3113, category: "tmi", content: "아이스크림 먹고 싶어?", answerType: "scale", scaleMin: "괜찮아 🥶", scaleMax: "먹고 싶어 🍦" },
  { id: 3114, category: "honest", content: "내 결단력은 어때?", answerType: "scale", scaleMin: "좀 고민해 🤷", scaleMax: "잘 결정해 ⚔️" },
  { id: 3115, category: "between", content: "서로 잘 위로해주고 있어?", answerType: "scale", scaleMin: "좀 서툴러 😅", scaleMax: "든든한 안식처 🫶" },
  { id: 3116, category: "future", content: "새로운 거 배우고 싶어?", answerType: "scale", scaleMin: "지금 충분해 🙂", scaleMax: "배워보고 싶어 📚" },
  { id: 3117, category: "tmi", content: "낮잠 자고 싶은 마음은?", answerType: "scale", scaleMin: "멀쩡해 😊", scaleMax: "눈이 감겨 😪" },
];
