import type { Question } from "@/types/question";

/** 추가 점수형 질문 Part 2 (ID 3118~3200) */
export const SCALE_EXTRA_2: Question[] = [
  { id: 3118, category: "between", content: "우리 연애 안정감은 어때?", answerType: "scale", scaleMin: "좀 걱정돼 😰", scaleMax: "든든해 🏔️" },
  { id: 3119, category: "honest", content: "내 집중력은 어때?", answerType: "scale", scaleMin: "좀 산만해 🐟", scaleMax: "잘 집중해 🔬" },
  { id: 3120, category: "tmi", content: "오늘 빵 먹고 싶어?", answerType: "scale", scaleMin: "괜찮아 🙂", scaleMax: "먹고 싶어 🥐" },
  { id: 3121, category: "values", content: "요즘 잠은 잘 자?", answerType: "scale", scaleMin: "좀 부족해 😵", scaleMax: "잘 자 🛌" },
  { id: 3122, category: "future", content: "집 꾸미고 싶은 마음은?", answerType: "scale", scaleMin: "별로 😶", scaleMax: "꾸미고 싶어 🏡" },
  { id: 3123, category: "pet", content: "동물 옷 입히고 싶어?", answerType: "scale", scaleMin: "자연이 좋아 🌱", scaleMax: "입혀보고 싶어 👗" },
  { id: 3124, category: "between", content: "서로 잘 웃기는 편이야?", answerType: "scale", scaleMin: "가끔 😐", scaleMax: "매일 웃겨 😂" },
  { id: 3125, category: "honest", content: "내 도전 정신은 어때?", answerType: "scale", scaleMin: "안전한 게 좋아 🛡️", scaleMax: "도전 좋아해 ⛰️" },
  { id: 3126, category: "tmi", content: "초콜릿 당기는 정도는?", answerType: "scale", scaleMin: "안 땡겨 🙅", scaleMax: "먹고 싶어 🍫" },
  { id: 3127, category: "values", content: "요즘 피부 상태는 어때?", answerType: "scale", scaleMin: "좀 신경 쓰여 😫", scaleMax: "괜찮아 ✨" },
  { id: 3128, category: "between", content: "서로 선물 잘 골라?", answerType: "scale", scaleMin: "좀 고민돼 🤔", scaleMax: "잘 맞아 🎁" },
  { id: 3129, category: "honest", content: "내 요리 레퍼토리는 어때?", answerType: "scale", scaleMin: "좀 적어 🍜", scaleMax: "다양해 🧑‍🍳" },
  { id: 3130, category: "future", content: "자격증 따보고 싶어?", answerType: "scale", scaleMin: "아직은 🙅", scaleMax: "도전해볼래 📝" },
  { id: 3131, category: "tmi", content: "비 오면 좋겠어?", answerType: "scale", scaleMin: "맑았으면 ☀️", scaleMax: "비 와도 좋아 🌧️" },
  { id: 3132, category: "pet", content: "동물 이름 짓는 센스는?", answerType: "scale", scaleMin: "보통 😅", scaleMax: "잘 지어 🏷️" },
  { id: 3133, category: "between", content: "우리 사진 충분히 찍어?", answerType: "scale", scaleMin: "더 찍자 📷", scaleMax: "충분해 🖼️" },
  { id: 3134, category: "values", content: "요즘 감성 충만해?", answerType: "scale", scaleMin: "좀 메말라 🏜️", scaleMax: "감성 가득 🌸" },
  { id: 3135, category: "honest", content: "내 절약 습관은 어때?", answerType: "scale", scaleMin: "좀 아쉬워 💸", scaleMax: "잘해 🐜" },
  { id: 3136, category: "tmi", content: "피자 먹고 싶은 마음은?", answerType: "scale", scaleMin: "보통 🙂", scaleMax: "먹고 싶어 🍕" },
  { id: 3137, category: "between", content: "서로 안아주는 빈도는 어때?", answerType: "scale", scaleMin: "더 안아줘 🥺", scaleMax: "충분해 🤗" },
  { id: 3138, category: "future", content: "운동 습관 만들고 싶어?", answerType: "scale", scaleMin: "좀 쉴래 🦥", scaleMax: "같이 해보자 💪" },
  { id: 3139, category: "honest", content: "내 공감 능력은 어때?", answerType: "scale", scaleMin: "좀 부족해 😅", scaleMax: "잘해줘 🧚" },
  { id: 3140, category: "pet", content: "동물 유치원 보내고 싶어?", answerType: "scale", scaleMin: "집이 좋아 🏠", scaleMax: "보내보고 싶어 🎓" },
  { id: 3141, category: "tmi", content: "오늘 사진 찍고 싶어?", answerType: "scale", scaleMin: "오늘은 쉴래 🙈", scaleMax: "찍고 싶어 📸" },
  { id: 3142, category: "between", content: "우리 잠드는 시간 맞아?", answerType: "scale", scaleMin: "좀 달라 🌙", scaleMax: "같이 잠들어 💤" },
  { id: 3143, category: "values", content: "요즘 운동량은 어때?", answerType: "scale", scaleMin: "좀 부족해 🫠", scaleMax: "잘하고 있어 🏃" },
  { id: 3144, category: "honest", content: "내 요리 맛에 자신 있어?", answerType: "scale", scaleMin: "좀 걱정돼 😬", scaleMax: "맛있어 👨‍🍳" },
  { id: 3145, category: "between", content: "서로 말투 편안해?", answerType: "scale", scaleMin: "좀 어색해 😳", scaleMax: "편해 👌" },
  { id: 3146, category: "future", content: "드라이브 가고 싶어?", answerType: "scale", scaleMin: "집이 좋아 🏠", scaleMax: "같이 가자 🚗" },
  { id: 3147, category: "tmi", content: "오늘 요리하고 싶어?", answerType: "scale", scaleMin: "배달 시키자 📦", scaleMax: "직접 만들자 🍳" },
  { id: 3148, category: "pet", content: "반려동물 생일 챙기는 편이야?", answerType: "scale", scaleMin: "좀 잊어 🤔", scaleMax: "잘 챙겨 🎂" },
  { id: 3149, category: "honest", content: "내 긍정적인 편이야?", answerType: "scale", scaleMin: "좀 걱정이 많아 😞", scaleMax: "밝은 편이야 🌞" },
  { id: 3150, category: "between", content: "우리 서프라이즈 잘해?", answerType: "scale", scaleMin: "좀 서툴러 😅", scaleMax: "잘해 🎉" },
  { id: 3151, category: "values", content: "뉴스 자주 보는 편이야?", answerType: "scale", scaleMin: "잘 안 봐 🙈", scaleMax: "챙겨봐 📰" },
  { id: 3152, category: "tmi", content: "떡볶이 먹고 싶은 마음은?", answerType: "scale", scaleMin: "괜찮아 🙂", scaleMax: "먹고 싶어 🌶️" },
  { id: 3153, category: "between", content: "서로 잘 들어주는 편이야?", answerType: "scale", scaleMin: "좀 더 들어줘 😕", scaleMax: "잘 들어줘 👂" },
  { id: 3154, category: "honest", content: "내 스트레스 해소 잘해?", answerType: "scale", scaleMin: "좀 쌓여 😤", scaleMax: "잘 풀어 🧘" },
  { id: 3155, category: "future", content: "새 취미 시작하고 싶어?", answerType: "scale", scaleMin: "지금 충분해 😌", scaleMax: "해보고 싶어 🎯" },
  { id: 3156, category: "pet", content: "동물 봉사에 관심 있어?", answerType: "scale", scaleMin: "아직은 🤔", scaleMax: "해보고 싶어 🐕" },
  { id: 3157, category: "between", content: "우리 톤앤매너 맞는 편이야?", answerType: "scale", scaleMin: "가끔 어긋나 😅", scaleMax: "잘 맞아 🧠" },
  { id: 3158, category: "honest", content: "내가 운이 좋은 편이야?", answerType: "scale", scaleMin: "좀 아쉬워 😢", scaleMax: "운 좋은 편 🍀" },
  { id: 3159, category: "tmi", content: "오늘 청소하고 싶어?", answerType: "scale", scaleMin: "내일 할래 🙃", scaleMax: "깨끗이 하자 🧽" },
  { id: 3160, category: "values", content: "요즘 식습관은 어때?", answerType: "scale", scaleMin: "좀 아쉬워 🍟", scaleMax: "잘 먹고 있어 🥗" },
  { id: 3161, category: "between", content: "우리 다투는 빈도는 어때?", answerType: "scale", scaleMin: "좀 자주야 😣", scaleMax: "거의 안 싸워 ☮️" },
  { id: 3162, category: "honest", content: "내가 어른스러운 편이야?", answerType: "scale", scaleMin: "아직 어려 🧒", scaleMax: "의젓해 🧓" },
  { id: 3163, category: "future", content: "저축 열심히 하고 싶어?", answerType: "scale", scaleMin: "좀 쓸래 💳", scaleMax: "모을래 🏦" },
  { id: 3164, category: "tmi", content: "오늘 책 읽고 싶어?", answerType: "scale", scaleMin: "영상이 좋아 📺", scaleMax: "읽고 싶어 📖" },
  { id: 3165, category: "pet", content: "반려동물 훈련 자신 있어?", answerType: "scale", scaleMin: "아직 배우는 중 🐣", scaleMax: "잘할 수 있어 🎓" },
  { id: 3166, category: "between", content: "우리 미래 계획 맞아?", answerType: "scale", scaleMin: "좀 달라 🔀", scaleMax: "같은 방향 ➡️" },
  { id: 3167, category: "honest", content: "내 적응력은 어때?", answerType: "scale", scaleMin: "좀 느려 😖", scaleMax: "잘 적응해 🦎" },
  { id: 3168, category: "tmi", content: "맥주 마시고 싶은 마음은?", answerType: "scale", scaleMin: "안 땡겨 🙅", scaleMax: "같이 마시자 🍺" },
  { id: 3169, category: "values", content: "요즘 외모 자신감은 어때?", answerType: "scale", scaleMin: "좀 아쉬워 😔", scaleMax: "괜찮아 💅" },
  { id: 3170, category: "between", content: "서로 잘 기다려주는 편이야?", answerType: "scale", scaleMin: "좀 급해 ⏩", scaleMax: "잘 기다려 🕰️" },
  { id: 3171, category: "honest", content: "내 약속 잘 지키는 편이야?", answerType: "scale", scaleMin: "가끔 까먹어 😅", scaleMax: "잘 지켜 🤞" },
  { id: 3172, category: "future", content: "외국어 배우고 싶어?", answerType: "scale", scaleMin: "지금 괜찮아 🇰🇷", scaleMax: "배워보고 싶어 🌍" },
  { id: 3173, category: "tmi", content: "유튜브 보고 싶은 마음은?", answerType: "scale", scaleMin: "별로 😶", scaleMax: "보고 싶어 📱" },
  { id: 3174, category: "pet", content: "동물 카페 가고 싶어?", answerType: "scale", scaleMin: "보통 🙂", scaleMax: "같이 가자 🐱" },
  { id: 3175, category: "between", content: "서로 잘 챙기고 있어?", answerType: "scale", scaleMin: "좀 더 챙겨줘 😕", scaleMax: "잘하고 있어 💝" },
  { id: 3176, category: "values", content: "요즘 멘탈 괜찮아?", answerType: "scale", scaleMin: "좀 흔들려 🌊", scaleMax: "괜찮아 🛡️" },
  { id: 3177, category: "honest", content: "내 비밀 많은 편이야?", answerType: "scale", scaleMin: "다 보여줘 📖", scaleMax: "좀 있어 🕵️" },
  { id: 3178, category: "tmi", content: "족발 먹고 싶은 마음은?", answerType: "scale", scaleMin: "괜찮아 🙂", scaleMax: "먹고 싶어 🥩" },
  { id: 3179, category: "between", content: "우리 만나는 빈도 어때?", answerType: "scale", scaleMin: "더 보고 싶어 🥺", scaleMax: "딱 좋아 💕" },
  { id: 3180, category: "future", content: "봉사활동 해보고 싶어?", answerType: "scale", scaleMin: "아직 여유가 😅", scaleMax: "같이 하자 🤝" },
  { id: 3181, category: "honest", content: "내 뒷정리 잘하는 편이야?", answerType: "scale", scaleMin: "좀 남겨둬 😬", scaleMax: "깔끔해 ✨" },
  { id: 3182, category: "pet", content: "동물병원 부지런히 가?", answerType: "scale", scaleMin: "좀 미뤄 😅", scaleMax: "잘 챙겨 🏥" },
  { id: 3183, category: "tmi", content: "산책하고 싶은 마음은?", answerType: "scale", scaleMin: "소파가 좋아 🛋️", scaleMax: "걷고 싶어 🚶" },
  { id: 3184, category: "between", content: "서로 연락 속도는 어때?", answerType: "scale", scaleMin: "좀 느려 🤿", scaleMax: "빨라서 좋아 ⚡" },
  { id: 3185, category: "values", content: "요즘 삶의 균형은 어때?", answerType: "scale", scaleMin: "좀 치우쳐 ⚖️", scaleMax: "잘 맞아 🎯" },
  { id: 3186, category: "honest", content: "내 용기 있는 편이야?", answerType: "scale", scaleMin: "좀 조심해 🐭", scaleMax: "용감해 🦁" },
  { id: 3187, category: "future", content: "창업에 관심 있어?", answerType: "scale", scaleMin: "안정이 좋아 🏢", scaleMax: "해보고 싶어 💼" },
  { id: 3188, category: "tmi", content: "노래방 가고 싶은 마음은?", answerType: "scale", scaleMin: "조용히 쉴래 🤫", scaleMax: "노래 부르자 🎤" },
  { id: 3189, category: "between", content: "우리 눈빛으로 통해?", answerType: "scale", scaleMin: "아직 연습 중 👀", scaleMax: "잘 통해 👁️" },
  { id: 3190, category: "pet", content: "반려동물한테 말 자주 해?", answerType: "scale", scaleMin: "가끔 🗣️", scaleMax: "매일 대화해 💬" },
  { id: 3191, category: "honest", content: "내 센스는 어때?", answerType: "scale", scaleMin: "좀 서툴러 🧱", scaleMax: "센스 좋아 💫" },
  { id: 3192, category: "values", content: "디지털 쉼이 필요해?", answerType: "scale", scaleMin: "괜찮아 📱", scaleMax: "좀 쉬고 싶어 🌿" },
  { id: 3193, category: "tmi", content: "빙수 먹고 싶은 마음은?", answerType: "scale", scaleMin: "안 땡겨 🙅", scaleMax: "먹으러 가자 🍧" },
  { id: 3194, category: "between", content: "우리 대화 재밌어?", answerType: "scale", scaleMin: "좀 심심해 😶", scaleMax: "시간 가는 줄 몰라 🗣️" },
  { id: 3195, category: "future", content: "요리 같이 배워볼래?", answerType: "scale", scaleMin: "사먹는 게 좋아 🛵", scaleMax: "같이 배우자 👨‍🍳" },
  { id: 3196, category: "honest", content: "내 꾸미는 감각은 어때?", answerType: "scale", scaleMin: "편한 게 좋아 🧢", scaleMax: "잘 꾸며 💄" },
  { id: 3197, category: "pet", content: "동물 입양 생각해봤어?", answerType: "scale", scaleMin: "아직 천천히 🤔", scaleMax: "진지하게 고민 중 🐾" },
  { id: 3198, category: "between", content: "서로 자랑스러워?", answerType: "scale", scaleMin: "보통 🙂", scaleMax: "자랑하고 다녀 🏆" },
  { id: 3199, category: "tmi", content: "집콕하고 싶은 마음은?", answerType: "scale", scaleMin: "나가고 싶어 🚪", scaleMax: "집이 최고 🛏️" },
  { id: 3200, category: "values", content: "감사일기 써보고 싶어?", answerType: "scale", scaleMin: "아직은 😅", scaleMax: "써보고 싶어 📓" },
];
