import type { Question } from "@/types/question";

/** 추가 점수형 질문 Part 2 (ID 3118~3200) */
export const SCALE_EXTRA_2: Question[] = [
  { id: 3118, category: "between", content: "우리 연애 안정감은?", answerType: "scale", scaleMin: "불안해 😰", scaleMax: "반석 위 🏔️" },
  { id: 3119, category: "honest", content: "내 집중력 레벨은?", answerType: "scale", scaleMin: "금붕어 🐟", scaleMax: "레이저 집중 🔬" },
  { id: 3120, category: "tmi", content: "오늘 빵 먹고 싶은 정도는?", answerType: "scale", scaleMin: "괜찮아 🙂", scaleMax: "빵순이 모드 🥐" },
  { id: 3121, category: "values", content: "현재 수면 만족도는?", answerType: "scale", scaleMin: "만성 수면 부족 😵", scaleMax: "꿀잠 🛌" },
  { id: 3122, category: "future", content: "집 꾸미고 싶은 정도는?", answerType: "scale", scaleMin: "관심 없어 😶", scaleMax: "인테리어 욕구 🏡" },
  { id: 3123, category: "pet", content: "동물 옷 입히고 싶은 정도는?", answerType: "scale", scaleMin: "자연이 좋아 🌱", scaleMax: "코스프레 가자 👗" },
  { id: 3124, category: "between", content: "서로 잘 웃기는 정도는?", answerType: "scale", scaleMin: "드물어 😐", scaleMax: "매일 빵터져 😂" },
  { id: 3125, category: "honest", content: "내 도전 정신 레벨은?", answerType: "scale", scaleMin: "안전제일 🛡️", scaleMax: "모험가 ⛰️" },
  { id: 3126, category: "tmi", content: "지금 초콜릿 당기는 정도는?", answerType: "scale", scaleMin: "안 땡겨 🙅", scaleMax: "초코 중독 🍫" },
  { id: 3127, category: "values", content: "현재 피부 상태 만족도는?", answerType: "scale", scaleMin: "트러블 😫", scaleMax: "꿀피부 ✨" },
  { id: 3128, category: "between", content: "서로 선물 센스는?", answerType: "scale", scaleMin: "고민 많아 🤔", scaleMax: "찰떡 선물 🎁" },
  { id: 3129, category: "honest", content: "내 요리 레퍼토리 다양성은?", answerType: "scale", scaleMin: "라면만 🍜", scaleMax: "만능 요리사 🧑‍🍳" },
  { id: 3130, category: "future", content: "자격증 따고 싶은 욕구는?", answerType: "scale", scaleMin: "없어 🙅", scaleMax: "공부 시작 📝" },
  { id: 3131, category: "tmi", content: "오늘 비 오면 좋겠는 정도는?", answerType: "scale", scaleMin: "맑았으면 ☀️", scaleMax: "비 와라 🌧️" },
  { id: 3132, category: "pet", content: "동물 이름 지어주는 센스는?", answerType: "scale", scaleMin: "평범해 😅", scaleMax: "작명 천재 🏷️" },
  { id: 3133, category: "between", content: "우리 사진 찍는 빈도 만족도는?", answerType: "scale", scaleMin: "더 찍자 📷", scaleMax: "충분해 🖼️" },
  { id: 3134, category: "values", content: "요즘 감성 충만한 정도는?", answerType: "scale", scaleMin: "메마른 사막 🏜️", scaleMax: "감성 폭발 🌸" },
  { id: 3135, category: "honest", content: "내 절약 능력은?", answerType: "scale", scaleMin: "통장 텅텅 💸", scaleMax: "절약왕 🐜" },
  { id: 3136, category: "tmi", content: "피자 먹고 싶은 정도는?", answerType: "scale", scaleMin: "보통 🙂", scaleMax: "피자 소환 🍕" },
  { id: 3137, category: "between", content: "서로 안아주는 빈도 만족도는?", answerType: "scale", scaleMin: "더 안아줘 🥺", scaleMax: "충분해 🤗" },
  { id: 3138, category: "future", content: "운동 습관 만들고 싶은 정도는?", answerType: "scale", scaleMin: "귀찮아 🦥", scaleMax: "헬창 되겠어 💪" },
  { id: 3139, category: "honest", content: "내 공감 능력은?", answerType: "scale", scaleMin: "부족해 😅", scaleMax: "공감 요정 🧚" },
  { id: 3140, category: "pet", content: "동물 유치원 보내고 싶은 정도는?", answerType: "scale", scaleMin: "집이 좋아 🏠", scaleMax: "사회성 키우자 🎓" },
  { id: 3141, category: "tmi", content: "오늘 사진 찍고 싶은 정도는?", answerType: "scale", scaleMin: "카메라 치워 🙈", scaleMax: "인생샷 각 📸" },
  { id: 3142, category: "between", content: "우리 잠자리 시간 맞는 정도는?", answerType: "scale", scaleMin: "완전 달라 🌙", scaleMax: "같이 잠들어 💤" },
  { id: 3143, category: "values", content: "현재 운동량 만족도는?", answerType: "scale", scaleMin: "운동 부족 🫠", scaleMax: "매일 운동 🏃" },
  { id: 3144, category: "honest", content: "내 요리 맛 자신감은?", answerType: "scale", scaleMin: "맛 보장 불가 😬", scaleMax: "맛집 수준 👨‍🍳" },
  { id: 3145, category: "between", content: "서로 존댓말/반말 밸런스는?", answerType: "scale", scaleMin: "어색해 😳", scaleMax: "완벽해 👌" },
  { id: 3146, category: "future", content: "드라이브 가고 싶은 정도는?", answerType: "scale", scaleMin: "집이 좋아 🏠", scaleMax: "당장 출발 🚗" },
  { id: 3147, category: "tmi", content: "오늘 요리하고 싶은 정도는?", answerType: "scale", scaleMin: "배달 시키자 📦", scaleMax: "직접 만들자 🍳" },
  { id: 3148, category: "pet", content: "반려동물 생일 챙기는 정도는?", answerType: "scale", scaleMin: "잘 모름 🤔", scaleMax: "케이크 준비 🎂" },
  { id: 3149, category: "honest", content: "내 긍정 마인드 레벨은?", answerType: "scale", scaleMin: "비관적 😞", scaleMax: "해피바이러스 🌞" },
  { id: 3150, category: "between", content: "우리 서프라이즈 능력은?", answerType: "scale", scaleMin: "서투른 편 😅", scaleMax: "깜짝 장인 🎉" },
  { id: 3151, category: "values", content: "뉴스 보는 빈도 만족도는?", answerType: "scale", scaleMin: "세상 몰라 🙈", scaleMax: "시사 통달 📰" },
  { id: 3152, category: "tmi", content: "지금 떡볶이 먹고 싶은 정도는?", answerType: "scale", scaleMin: "괜찮아 🙂", scaleMax: "매운 것 폭주 🌶️" },
  { id: 3153, category: "between", content: "서로 잘 들어주는 정도는?", answerType: "scale", scaleMin: "좀 부족 😕", scaleMax: "경청왕 👂" },
  { id: 3154, category: "honest", content: "내 스트레스 해소 능력은?", answerType: "scale", scaleMin: "쌓이기만 해 😤", scaleMax: "해소 달인 🧘" },
  { id: 3155, category: "future", content: "새 취미 시작하고 싶은 정도는?", answerType: "scale", scaleMin: "현재 충분 😌", scaleMax: "도전하자 🎯" },
  { id: 3156, category: "pet", content: "동물 관련 봉사 관심도는?", answerType: "scale", scaleMin: "아직 먼 일 🤔", scaleMax: "참여하고파 🐕" },
  { id: 3157, category: "between", content: "우리 톤앤매너 맞는 정도는?", answerType: "scale", scaleMin: "자주 어긋나 😅", scaleMax: "텔레파시 🧠" },
  { id: 3158, category: "honest", content: "내 운 좋은 정도는?", answerType: "scale", scaleMin: "불운 체질 😢", scaleMax: "행운의 사나이 🍀" },
  { id: 3159, category: "tmi", content: "오늘 청소하고 싶은 정도는?", answerType: "scale", scaleMin: "내일 하자 🙃", scaleMax: "대청소 각 🧽" },
  { id: 3160, category: "values", content: "현재 식습관 만족도는?", answerType: "scale", scaleMin: "엉망 🍟", scaleMax: "건강식 🥗" },
  { id: 3161, category: "between", content: "우리 싸움 빈도 만족도는?", answerType: "scale", scaleMin: "너무 자주 😣", scaleMax: "거의 안 싸워 ☮️" },
  { id: 3162, category: "honest", content: "내 어른스러운 정도는?", answerType: "scale", scaleMin: "아직 어린이 🧒", scaleMax: "어른 인정 🧓" },
  { id: 3163, category: "future", content: "저축 목표 의지 정도는?", answerType: "scale", scaleMin: "쓸 거야 💳", scaleMax: "모으겠어 🏦" },
  { id: 3164, category: "tmi", content: "오늘 독서하고 싶은 정도는?", answerType: "scale", scaleMin: "유튜브가 좋아 📺", scaleMax: "책 펼치자 📖" },
  { id: 3165, category: "pet", content: "반려동물 훈련 자신감은?", answerType: "scale", scaleMin: "초보 🐣", scaleMax: "훈련사급 🎓" },
  { id: 3166, category: "between", content: "우리 미래 계획 맞는 정도는?", answerType: "scale", scaleMin: "많이 달라 🔀", scaleMax: "한 방향 ➡️" },
  { id: 3167, category: "honest", content: "내 적응력 레벨은?", answerType: "scale", scaleMin: "변화 싫어 😖", scaleMax: "어디든 적응 🦎" },
  { id: 3168, category: "tmi", content: "지금 맥주 마시고 싶은 정도는?", answerType: "scale", scaleMin: "안 땡겨 🙅", scaleMax: "치맥 가자 🍺" },
  { id: 3169, category: "values", content: "현재 외모 자신감은?", answerType: "scale", scaleMin: "자신 없어 😔", scaleMax: "자신 만만 💅" },
  { id: 3170, category: "between", content: "서로 기다려주는 정도는?", answerType: "scale", scaleMin: "급해 ⏩", scaleMax: "천천히 기다려 🕰️" },
  { id: 3171, category: "honest", content: "내 약속 잘 지키는 정도는?", answerType: "scale", scaleMin: "종종 까먹어 😅", scaleMax: "철벽 약속 🤞" },
  { id: 3172, category: "future", content: "외국어 배우고 싶은 정도는?", answerType: "scale", scaleMin: "한국어면 충분 🇰🇷", scaleMax: "다국어 마스터 🌍" },
  { id: 3173, category: "tmi", content: "오늘 유튜브 보고 싶은 정도는?", answerType: "scale", scaleMin: "볼 거 없어 😶", scaleMax: "알고리즘 빠져 📱" },
  { id: 3174, category: "pet", content: "동물 카페 가고 싶은 정도는?", answerType: "scale", scaleMin: "보통 🙂", scaleMax: "당장 가자 🐱" },
  { id: 3175, category: "between", content: "서로 잘 챙기는 정도는?", answerType: "scale", scaleMin: "좀 부족 😕", scaleMax: "완벽 케어 💝" },
  { id: 3176, category: "values", content: "현재 멘탈 관리 레벨은?", answerType: "scale", scaleMin: "멘탈 흔들 🌊", scaleMax: "강철 멘탈 🛡️" },
  { id: 3177, category: "honest", content: "내 비밀 많은 정도는?", answerType: "scale", scaleMin: "오픈북 📖", scaleMax: "미스터리 🕵️" },
  { id: 3178, category: "tmi", content: "지금 족발 먹고 싶은 정도는?", answerType: "scale", scaleMin: "괜찮아 🙂", scaleMax: "보쌈도 추가 🥩" },
  { id: 3179, category: "between", content: "우리 데이트 빈도 만족도는?", answerType: "scale", scaleMin: "더 만나자 🥺", scaleMax: "딱 좋아 💕" },
  { id: 3180, category: "future", content: "봉사활동 하고 싶은 정도는?", answerType: "scale", scaleMin: "아직 여유 없어 😅", scaleMax: "함께 하자 🤝" },
  { id: 3181, category: "honest", content: "내 뒷정리 잘하는 정도는?", answerType: "scale", scaleMin: "흔적 남김 😬", scaleMax: "깔끔 마무리 ✨" },
  { id: 3182, category: "pet", content: "동물병원 가는 부지런함은?", answerType: "scale", scaleMin: "미루는 편 😅", scaleMax: "정기 검진 🏥" },
  { id: 3183, category: "tmi", content: "오늘 산책하고 싶은 정도는?", answerType: "scale", scaleMin: "소파가 좋아 🛋️", scaleMax: "걷고 싶어 🚶" },
  { id: 3184, category: "between", content: "서로 연락 속도 만족도는?", answerType: "scale", scaleMin: "잠수 탄다 🤿", scaleMax: "즉답 도착 ⚡" },
  { id: 3185, category: "values", content: "현재 삶의 균형 만족도는?", answerType: "scale", scaleMin: "한쪽 치우침 ⚖️", scaleMax: "완벽 균형 🎯" },
  { id: 3186, category: "honest", content: "내 패기 레벨은?", answerType: "scale", scaleMin: "소심 🐭", scaleMax: "대담 🦁" },
  { id: 3187, category: "future", content: "창업 욕구 정도는?", answerType: "scale", scaleMin: "안정이 좋아 🏢", scaleMax: "사장님 되겠어 💼" },
  { id: 3188, category: "tmi", content: "오늘 노래방 가고 싶은 정도는?", answerType: "scale", scaleMin: "조용히 🤫", scaleMax: "18번 부르자 🎤" },
  { id: 3189, category: "between", content: "우리 눈빛 통하는 정도는?", answerType: "scale", scaleMin: "아직 서툴러 👀", scaleMax: "완벽 아이컨택 👁️" },
  { id: 3190, category: "pet", content: "반려동물에게 말하는 빈도는?", answerType: "scale", scaleMin: "가끔 🗣️", scaleMax: "하루종일 대화 💬" },
  { id: 3191, category: "honest", content: "내 센스 레벨은?", answerType: "scale", scaleMin: "둔해 🧱", scaleMax: "센스쟁이 💫" },
  { id: 3192, category: "values", content: "디지털 디톡스 필요한 정도는?", answerType: "scale", scaleMin: "괜찮아 📱", scaleMax: "폰 놓고 싶어 🌿" },
  { id: 3193, category: "tmi", content: "지금 빙수 먹고 싶은 정도는?", answerType: "scale", scaleMin: "안 땡겨 🙅", scaleMax: "팥빙수 가자 🍧" },
  { id: 3194, category: "between", content: "우리 대화 재미있는 정도는?", answerType: "scale", scaleMin: "심심해 😶", scaleMax: "시간 가는 줄 몰라 🗣️" },
  { id: 3195, category: "future", content: "요리 클래스 가고 싶은 정도는?", answerType: "scale", scaleMin: "배달이 좋아 🛵", scaleMax: "같이 배우자 👨‍🍳" },
  { id: 3196, category: "honest", content: "내 꾸미는 능력은?", answerType: "scale", scaleMin: "무꾸 최고 🧢", scaleMax: "스타일리스트급 💄" },
  { id: 3197, category: "pet", content: "동물 입양 고민 정도는?", answerType: "scale", scaleMin: "아직 먼 일 🤔", scaleMax: "진지하게 고민 🐾" },
  { id: 3198, category: "between", content: "서로 자랑스러운 정도는?", answerType: "scale", scaleMin: "보통 🙂", scaleMax: "자랑하고 다녀 🏆" },
  { id: 3199, category: "tmi", content: "지금 집콕하고 싶은 정도는?", answerType: "scale", scaleMin: "밖에 나가자 🚪", scaleMax: "이불 밖은 위험 🛏️" },
  { id: 3200, category: "values", content: "현재 감사일기 쓰고 싶은 정도는?", answerType: "scale", scaleMin: "귀찮아 😅", scaleMax: "매일 쓸래 📓" },
];
