import type { Question } from "@/types/question";

/** 추가 점수형 질문 Part 4 (ID 3301~3400) */
export const SCALE_EXTRA_4: Question[] = [
  { id: 3301, category: "between", content: "오늘 우리 공감대 얼마나?", answerType: "scale", scaleMin: "적어 😶", scaleMax: "잘 통해 💞" },
  { id: 3302, category: "honest", content: "내 시간 관리 점수는?", answerType: "scale", scaleMin: "허둥대 🏃", scaleMax: "체계적 📅" },
  { id: 3303, category: "tmi", content: "오늘 햇빛 많이 봤어?", answerType: "scale", scaleMin: "실내만 🏠", scaleMax: "충분해 ☀️" },
  { id: 3304, category: "values", content: "요즘 독서량은?", answerType: "scale", scaleMin: "거의 없어 📕", scaleMax: "매일 읽어 📖" },
  { id: 3305, category: "future", content: "둘만의 취미 만들고 싶어?", answerType: "scale", scaleMin: "각자도 좋아 🙂", scaleMax: "만들자 🎨" },
  { id: 3306, category: "pet", content: "반려동물 간식 만들어주고 싶어?", answerType: "scale", scaleMin: "귀찮아 🙅", scaleMax: "만들자 🍪" },
  { id: 3307, category: "between", content: "우리 데이트 설렘 정도?", answerType: "scale", scaleMin: "익숙해 🙂", scaleMax: "두근두근 💓" },
  { id: 3308, category: "honest", content: "오늘 내 표현력은?", answerType: "scale", scaleMin: "말 없었어 😶", scaleMax: "활발 🗣️" },
  { id: 3309, category: "tmi", content: "지금 피자 땡겨?", answerType: "scale", scaleMin: "별로 🙅", scaleMax: "시키자 🍕" },
  { id: 3310, category: "values", content: "자연과 시간 보내는 빈도는?", answerType: "scale", scaleMin: "드물어 🏙️", scaleMax: "자주 🌳" },
  { id: 3311, category: "future", content: "꿈꾸던 여행지 실행 의지는?", answerType: "scale", scaleMin: "언젠가 🌫️", scaleMax: "곧 실행 ✈️" },
  { id: 3312, category: "pet", content: "반려동물과 놀이 시간 충분?", answerType: "scale", scaleMin: "부족해 ⏰", scaleMax: "넉넉 🎾" },
  { id: 3313, category: "between", content: "우리 밸런스 만족도?", answerType: "scale", scaleMin: "한쪽 기울어 🫤", scaleMax: "균형 잡혀 ⚖️" },
  { id: 3314, category: "honest", content: "나는 기억력 좋은 편?", answerType: "scale", scaleMin: "자주 까먹어 🫠", scaleMax: "잘 기억해 🧠" },
  { id: 3315, category: "tmi", content: "오늘 음악 들은 시간은?", answerType: "scale", scaleMin: "안 들었어 🙉", scaleMax: "많이 🎧" },
  { id: 3316, category: "values", content: "문화 체험 욕구는?", answerType: "scale", scaleMin: "집이 좋아 🛋️", scaleMax: "체험 좋아 🎭" },
  { id: 3317, category: "future", content: "반려동물과 함께할 집 꿈?", answerType: "scale", scaleMin: "막연해 🌫️", scaleMax: "구체적 🏡" },
  { id: 3318, category: "pet", content: "반려동물 사진 찍는 빈도는?", answerType: "scale", scaleMin: "적어 📷", scaleMax: "매일 📸" },
  { id: 3319, category: "between", content: "서로 꿈 응원 많이 해?", answerType: "scale", scaleMin: "부족해 🌫️", scaleMax: "많이 해 🙌" },
  { id: 3320, category: "honest", content: "내가 체력 좋은 편?", answerType: "scale", scaleMin: "쉽게 지쳐 😮‍💨", scaleMax: "튼튼해 💪" },
  { id: 3321, category: "tmi", content: "오늘 웃음 횟수는?", answerType: "scale", scaleMin: "거의 없었어 😑", scaleMax: "많이 😂" },
  { id: 3322, category: "values", content: "재테크 공부 관심은?", answerType: "scale", scaleMin: "별로 💤", scaleMax: "많아 📊" },
  { id: 3323, category: "future", content: "노후 자금 준비 마음가짐?", answerType: "scale", scaleMin: "멀게 느껴 🙃", scaleMax: "준비 중 💰" },
  { id: 3324, category: "pet", content: "반려동물 앞에서 애교 많이 해?", answerType: "scale", scaleMin: "쑥스러워 🙈", scaleMax: "팡팡 🥰" },
  { id: 3325, category: "between", content: "최근 2주 우리 관계 점수?", answerType: "scale", scaleMin: "조금 아쉬워 😌", scaleMax: "너무 좋았어 🎉" },
  { id: 3326, category: "honest", content: "내 낙천성은 어때?", answerType: "scale", scaleMin: "걱정 많아 😟", scaleMax: "긍정적 ☀️" },
  { id: 3327, category: "tmi", content: "오늘 기온 체감 만족도는?", answerType: "scale", scaleMin: "불편해 🥶", scaleMax: "딱 좋아 😌" },
  { id: 3328, category: "values", content: "예절/매너 중요시하는 정도?", answerType: "scale", scaleMin: "자유로움 🤷", scaleMax: "중요 🎩" },
  { id: 3329, category: "future", content: "은퇴 후 시골/해외 살기?", answerType: "scale", scaleMin: "도시가 좋아 🏙️", scaleMax: "떠나고파 🏞️" },
  { id: 3330, category: "pet", content: "반려동물 유치원 보낼래?", answerType: "scale", scaleMin: "안 보낼래 🏠", scaleMax: "보낼 생각 🎓" },
  { id: 3331, category: "between", content: "우리 데이트 다양성은?", answerType: "scale", scaleMin: "비슷해 🔁", scaleMax: "다양해 🎡" },
  { id: 3332, category: "honest", content: "내 고집 있는 편?", answerType: "scale", scaleMin: "유연 🌬️", scaleMax: "고집 있어 🗿" },
  { id: 3333, category: "tmi", content: "지금 요리해보고 싶어?", answerType: "scale", scaleMin: "배달 🛵", scaleMax: "직접 👨‍🍳" },
  { id: 3334, category: "values", content: "사적인 시간 비중 만족?", answerType: "scale", scaleMin: "부족해 😮‍💨", scaleMax: "충분해 🛋️" },
  { id: 3335, category: "future", content: "자녀 교육관 미리 맞추고파?", answerType: "scale", scaleMin: "나중에 🫣", scaleMax: "지금 맞추자 📚" },
  { id: 3336, category: "pet", content: "반려동물 응급키트 준비 필요?", answerType: "scale", scaleMin: "나중에 🙂", scaleMax: "필요해 🩹" },
  { id: 3337, category: "between", content: "서로 말투 만족도?", answerType: "scale", scaleMin: "날카로워 😬", scaleMax: "따뜻해 🌸" },
  { id: 3338, category: "honest", content: "나 스스로 좋아하는 점 많아?", answerType: "scale", scaleMin: "별로 🫥", scaleMax: "많아 💖" },
  { id: 3339, category: "tmi", content: "오늘 날씨 기분에 영향 줬어?", answerType: "scale", scaleMin: "별로 🌤️", scaleMax: "많이 🌦️" },
  { id: 3340, category: "values", content: "정치/시사 대화 즐겨?", answerType: "scale", scaleMin: "피해 🙅", scaleMax: "관심 📺" },
  { id: 3341, category: "future", content: "반려동물 보험 가입 의향?", answerType: "scale", scaleMin: "아직 🙂", scaleMax: "해야해 📄" },
  { id: 3342, category: "pet", content: "반려동물 얼굴 닮고 싶어?", answerType: "scale", scaleMin: "별로 🙈", scaleMax: "너무 귀여워 🐶" },
  { id: 3343, category: "between", content: "오늘 네가 더 예뻐 보여?", answerType: "scale", scaleMin: "평소 그대로 🙂", scaleMax: "빛나 ✨" },
  { id: 3344, category: "honest", content: "내 유머 감각은?", answerType: "scale", scaleMin: "진지 🙂", scaleMax: "웃겨 🤣" },
  { id: 3345, category: "tmi", content: "지금 목욕하고 싶어?", answerType: "scale", scaleMin: "괜찮아 🙂", scaleMax: "담그고파 🛁" },
  { id: 3346, category: "values", content: "오프라인 만남 중요도?", answerType: "scale", scaleMin: "온라인으로 충분 💻", scaleMax: "꼭 만나야 🤝" },
  { id: 3347, category: "future", content: "둘이서 큰 프로젝트 해보자?", answerType: "scale", scaleMin: "부담돼 😅", scaleMax: "재밌겠어 🎯" },
  { id: 3348, category: "pet", content: "반려동물 나이들수록 걱정?", answerType: "scale", scaleMin: "아직 🙂", scaleMax: "많이 😢" },
  { id: 3349, category: "between", content: "우리 사진 자주 찍어?", answerType: "scale", scaleMin: "가끔 📷", scaleMax: "자주 📸" },
  { id: 3350, category: "honest", content: "내가 약속 지키려 노력해?", answerType: "scale", scaleMin: "느슨해 🙂", scaleMax: "철저 ⏱️" },
  { id: 3351, category: "tmi", content: "지금 떡볶이 먹고파?", answerType: "scale", scaleMin: "별로 🙅", scaleMax: "시키자 🍜" },
  { id: 3352, category: "values", content: "건강검진 신경 쓰는 편?", answerType: "scale", scaleMin: "미뤄 🙁", scaleMax: "챙겨 🏥" },
  { id: 3353, category: "future", content: "내 집 인테리어 꿈 자주 꿔?", answerType: "scale", scaleMin: "별로 🙃", scaleMax: "매일 🏡" },
  { id: 3354, category: "pet", content: "반려동물 교감 느껴본 적 있어?", answerType: "scale", scaleMin: "별로 🙂", scaleMax: "많이 🫶" },
  { id: 3355, category: "between", content: "우리 사이 리듬 잘 맞아?", answerType: "scale", scaleMin: "어긋나 😅", scaleMax: "딱 맞아 🎵" },
  { id: 3356, category: "honest", content: "내 양보하는 정도는?", answerType: "scale", scaleMin: "고집해 🛡️", scaleMax: "잘 양보해 🤲" },
  { id: 3357, category: "tmi", content: "오늘 새로운 거 시도했어?", answerType: "scale", scaleMin: "평소처럼 🔁", scaleMax: "시도했어 🚀" },
  { id: 3358, category: "values", content: "요즘 감사 자주 느껴?", answerType: "scale", scaleMin: "가끔 🌫️", scaleMax: "많이 🙏" },
  { id: 3359, category: "future", content: "미래 사진관/앨범 만들고파?", answerType: "scale", scaleMin: "별로 🙂", scaleMax: "만들자 📸" },
  { id: 3360, category: "pet", content: "반려동물에게 음악 들려주고파?", answerType: "scale", scaleMin: "별로 🎵", scaleMax: "좋아해 🎶" },
  { id: 3361, category: "between", content: "서로 선물 빈도 만족?", answerType: "scale", scaleMin: "적어 🎁", scaleMax: "충분 🎀" },
  { id: 3362, category: "honest", content: "내 자기관리 점수는?", answerType: "scale", scaleMin: "느슨해 🫠", scaleMax: "철저 💪" },
  { id: 3363, category: "tmi", content: "지금 떠나고 싶은 충동?", answerType: "scale", scaleMin: "없어 🙂", scaleMax: "커 ✈️" },
  { id: 3364, category: "values", content: "글쓰기/일기 습관 있어?", answerType: "scale", scaleMin: "없어 📕", scaleMax: "꾸준 📓" },
  { id: 3365, category: "future", content: "차 바꾸거나 구입 계획?", answerType: "scale", scaleMin: "나중에 🚶", scaleMax: "곧 🚗" },
  { id: 3366, category: "pet", content: "반려동물용 장난감 만들어주고파?", answerType: "scale", scaleMin: "귀찮아 🙅", scaleMax: "만들자 ✂️" },
  { id: 3367, category: "between", content: "우리 애칭 만족도는?", answerType: "scale", scaleMin: "어색해 😅", scaleMax: "사랑스러워 💕" },
  { id: 3368, category: "honest", content: "내 감사 표현 빈도는?", answerType: "scale", scaleMin: "부족해 🤫", scaleMax: "많아 🙏" },
  { id: 3369, category: "tmi", content: "오늘 계단 vs 엘리베이터?", answerType: "scale", scaleMin: "엘리베이터 🛗", scaleMax: "계단 🪜" },
  { id: 3370, category: "values", content: "라이프 밸런스 점수?", answerType: "scale", scaleMin: "기울어 🫤", scaleMax: "균형 ⚖️" },
  { id: 3371, category: "future", content: "우리 결혼식 구체적 상상?", answerType: "scale", scaleMin: "막연 🌫️", scaleMax: "구체적 💒" },
  { id: 3372, category: "pet", content: "반려동물 있을 때 집 꾸밈 생각?", answerType: "scale", scaleMin: "별로 🏠", scaleMax: "많이 🪴" },
  { id: 3373, category: "between", content: "우리 연애 자랑하고파?", answerType: "scale", scaleMin: "조용히 🤐", scaleMax: "자랑 📢" },
  { id: 3374, category: "honest", content: "내 관찰력 점수는?", answerType: "scale", scaleMin: "무뎌 🙂", scaleMax: "예리 👁️" },
  { id: 3375, category: "tmi", content: "오늘 햇살 좋아 나갈까?", answerType: "scale", scaleMin: "집이 좋아 🛋️", scaleMax: "나가자 🌤️" },
  { id: 3376, category: "values", content: "현재 삶에 대한 만족도?", answerType: "scale", scaleMin: "부족해 😔", scaleMax: "행복해 😊" },
  { id: 3377, category: "future", content: "50세 우리 모습 상상 좋아?", answerType: "scale", scaleMin: "걱정돼 😨", scaleMax: "설레 🌅" },
  { id: 3378, category: "pet", content: "반려동물에게 감정 이입 자주?", answerType: "scale", scaleMin: "별로 🙂", scaleMax: "많이 🫂" },
  { id: 3379, category: "between", content: "우리 기념일 챙김 만족도?", answerType: "scale", scaleMin: "부족해 😅", scaleMax: "충분 🎂" },
  { id: 3380, category: "honest", content: "내 결단력 점수는?", answerType: "scale", scaleMin: "고민 많아 🤔", scaleMax: "결단 빠름 ⚡" },
  { id: 3381, category: "tmi", content: "지금 과일 먹고 싶어?", answerType: "scale", scaleMin: "별로 🙅", scaleMax: "먹고파 🍎" },
  { id: 3382, category: "values", content: "최근 행복 지수?", answerType: "scale", scaleMin: "낮아 🌫️", scaleMax: "높아 🌈" },
  { id: 3383, category: "future", content: "우리 둘만의 집 규칙 만들고파?", answerType: "scale", scaleMin: "자유롭게 🙂", scaleMax: "정하자 📜" },
  { id: 3384, category: "pet", content: "반려동물에 생일 파티 해주고파?", answerType: "scale", scaleMin: "과해 🎈", scaleMax: "해주자 🎂" },
  { id: 3385, category: "between", content: "서로 계획 공유 빈도는?", answerType: "scale", scaleMin: "적어 🤫", scaleMax: "많이 🗓️" },
  { id: 3386, category: "honest", content: "내 감각/센스 점수?", answerType: "scale", scaleMin: "투박 🧱", scaleMax: "세련 ✨" },
  { id: 3387, category: "tmi", content: "오늘 햇볕 양 점수?", answerType: "scale", scaleMin: "적어 ☁️", scaleMax: "많아 🌞" },
  { id: 3388, category: "values", content: "타인을 돕는 빈도는?", answerType: "scale", scaleMin: "적어 🤷", scaleMax: "많아 🤝" },
  { id: 3389, category: "future", content: "우리 첫집 꾸밈 의지?", answerType: "scale", scaleMin: "단출히 🏠", scaleMax: "풍성히 🏡" },
  { id: 3390, category: "pet", content: "반려동물과 크리스마스 상상?", answerType: "scale", scaleMin: "별로 🎄", scaleMax: "보고파 🎅" },
  { id: 3391, category: "between", content: "우리 플레이리스트 만들고파?", answerType: "scale", scaleMin: "각자 🎧", scaleMax: "같이 🎶" },
  { id: 3392, category: "honest", content: "내 관계 유지 능력은?", answerType: "scale", scaleMin: "소홀해져 🙃", scaleMax: "꾸준 🤝" },
  { id: 3393, category: "tmi", content: "지금 매운 거 땡겨?", answerType: "scale", scaleMin: "순한 게 좋아 🥛", scaleMax: "매운 거 🌶️" },
  { id: 3394, category: "values", content: "이웃 관계에 대한 관심?", answerType: "scale", scaleMin: "덤덤 🙂", scaleMax: "소중 🏡" },
  { id: 3395, category: "future", content: "가족 모임 자주 만들고파?", answerType: "scale", scaleMin: "부담 😅", scaleMax: "좋아 👨‍👩‍👧" },
  { id: 3396, category: "pet", content: "반려동물과 여행 지역 고려해?", answerType: "scale", scaleMin: "안 해 🙅", scaleMax: "꼼꼼 🗺️" },
  { id: 3397, category: "between", content: "우리 보내고픈 계절 공유?", answerType: "scale", scaleMin: "각자 🌱", scaleMax: "같이 🍁" },
  { id: 3398, category: "honest", content: "내 생활 루틴 점수?", answerType: "scale", scaleMin: "불규칙 🌀", scaleMax: "탄탄 📅" },
  { id: 3399, category: "tmi", content: "오늘 음식 만족도는?", answerType: "scale", scaleMin: "아쉬워 🙁", scaleMax: "만족 😋" },
  { id: 3400, category: "values", content: "내 일과 삶 균형 점수?", answerType: "scale", scaleMin: "기울어 🫤", scaleMax: "균형 ⚖️" },
];
