import type { Question } from "@/types/question";

/** 추가 자유서술 질문 Part 3 (ID 1537-1640) */
export const TEXT_EXTRA_3: Question[] = [
  // --- honest (15) ---
  { id: 1537, category: "honest", content: "내 잠옷 패션 솔직히 어떻게 보여?", answerType: "text" },
  { id: 1538, category: "honest", content: "나 셀카 잘 찍는 편인 것 같아?", answerType: "text" },
  { id: 1539, category: "honest", content: "나한테 살짝 아쉬운 점이 있을까?", answerType: "text" },
  { id: 1540, category: "honest", content: "내가 좀 유치하게 느껴질 때 있어?", answerType: "text" },
  { id: 1541, category: "honest", content: "내가 잘 놀아준다고 느껴지긴 해?", answerType: "text" },
  { id: 1542, category: "honest", content: "나의 제일 큰 장점이 뭐라고 느껴져?", answerType: "text" },
  { id: 1543, category: "honest", content: "내가 모르게 하는 귀여운 행동 있을까?", answerType: "text" },
  { id: 1544, category: "honest", content: "내가 네 이상형에 살짝 부족한 점 있어?", answerType: "text" },
  { id: 1545, category: "honest", content: "나한테 제일 뿌듯했던 순간 떠올라?", answerType: "text" },
  { id: 1546, category: "honest", content: "내가 더 노력하면 좋을 부분이 있을까?", answerType: "text" },
  { id: 1547, category: "honest", content: "솔직히 나 어때? 잘생겼어/예뻐?", answerType: "text" },
  { id: 1548, category: "honest", content: "나한테 살짝 감추고 있는 마음이 있어?", answerType: "text" },
  { id: 1549, category: "honest", content: "내가 제일 어른스럽게 느껴질 때는?", answerType: "text" },
  { id: 1550, category: "honest", content: "내 웃음 포인트가 좀 특이하다고 느껴져?", answerType: "text" },
  { id: 1551, category: "honest", content: "나 힘들 때 잘 기대는 편인 것 같아?", answerType: "text" },
  // --- ifonly (15) ---
  { id: 1552, category: "ifonly", content: "우리가 쌍둥이였다면 어떤 느낌일까?", answerType: "text" },
  { id: 1553, category: "ifonly", content: "나랑 영화를 만든다면 어떤 이야기야?", answerType: "text" },
  { id: 1554, category: "ifonly", content: "하루만 CEO가 된다면 뭘 바꿔볼래?", answerType: "text" },
  { id: 1555, category: "ifonly", content: "나랑 듀엣을 부른다면 어떤 노래가 좋아?", answerType: "text" },
  { id: 1556, category: "ifonly", content: "아무 악기나 연주할 수 있다면 뭐 할래?", answerType: "text" },
  { id: 1557, category: "ifonly", content: "나랑 식당을 연다면 어떤 메뉴가 좋아?", answerType: "text" },
  { id: 1558, category: "ifonly", content: "평행우주 속 우리는 뭐 하고 있을까?", answerType: "text" },
  { id: 1559, category: "ifonly", content: "유령이 될 수 있다면 누구를 따라다닐래?", answerType: "text" },
  { id: 1560, category: "ifonly", content: "나랑 만화 캐릭터가 된다면 누가 떠올라?", answerType: "text" },
  { id: 1561, category: "ifonly", content: "세상에 딱 하나만 발명할 수 있다면?", answerType: "text" },
  { id: 1562, category: "ifonly", content: "나랑 서바이벌에 나가면 어떻게 될까?", answerType: "text" },
  { id: 1563, category: "ifonly", content: "하루만 어린 시절로 돌아갈 수 있다면?", answerType: "text" },
  { id: 1564, category: "ifonly", content: "나랑 브이로그를 찍는다면 어떤 느낌?", answerType: "text" },
  { id: 1565, category: "ifonly", content: "아무 나라 국적을 가질 수 있다면 어디?", answerType: "text" },
  { id: 1566, category: "ifonly", content: "우리 이야기가 노래 가사가 된다면?", answerType: "text" },
  // --- between (15) ---
  { id: 1567, category: "between", content: "나한테 고백했을 때 심장이 어땠어?", answerType: "text" },
  { id: 1568, category: "between", content: "우리가 가장 조용했던 데이트 떠올라?", answerType: "text" },
  { id: 1569, category: "between", content: "내가 너한테 제일 많이 칭찬하는 건?", answerType: "text" },
  { id: 1570, category: "between", content: "우리가 제일 잘 맞는 부분이 뭘까?", answerType: "text" },
  { id: 1571, category: "between", content: "나랑 제일 맛있게 먹은 야식 떠올라?", answerType: "text" },
  { id: 1572, category: "between", content: "우리 사이의 TMI 하나 말해볼래?", answerType: "text" },
  { id: 1573, category: "between", content: "내가 보낸 제일 긴 카톡 기억나?", answerType: "text" },
  { id: 1574, category: "between", content: "우리가 함께 만든 추억 1위는 뭘까?", answerType: "text" },
  { id: 1575, category: "between", content: "나한테 제일 보고 싶었던 순간 떠올라?", answerType: "text" },
  { id: 1576, category: "between", content: "우리만의 화해 방법이 있다면 뭘까?", answerType: "text" },
  { id: 1577, category: "between", content: "나랑 가장 설렜던 여행지 기억나?", answerType: "text" },
  { id: 1578, category: "between", content: "우리가 잘 극복해낸 위기가 있을까?", answerType: "text" },
  { id: 1579, category: "between", content: "나한테 가장 자주 보내는 이모티콘은?", answerType: "text" },
  { id: 1580, category: "between", content: "우리 사이에서 가장 성장한 부분은?", answerType: "text" },
  { id: 1581, category: "between", content: "나랑 함께한 가장 로맨틱한 순간은?", answerType: "text" },
  // --- tmi (15) ---
  { id: 1582, category: "tmi", content: "어릴 때 제일 안 먹던 음식 떠올라?", answerType: "text" },
  { id: 1583, category: "tmi", content: "지금 핸드폰에 사진 몇 장쯤 있을까?", answerType: "text" },
  { id: 1584, category: "tmi", content: "최근에 새벽까지 했던 거 뭐가 있어?", answerType: "text" },
  { id: 1585, category: "tmi", content: "어릴 때 제일 받고 싶었던 선물 떠올라?", answerType: "text" },
  { id: 1586, category: "tmi", content: "기분 전환할 때 꼭 먹는 음식 있어?", answerType: "text" },
  { id: 1587, category: "tmi", content: "인생 최고의 영화 장면이 뭐야?", answerType: "text" },
  { id: 1588, category: "tmi", content: "제일 재밌었던 꿈 내용 떠올라?", answerType: "text" },
  { id: 1589, category: "tmi", content: "사진첩에 가장 많은 카테고리가 뭐야?", answerType: "text" },
  { id: 1590, category: "tmi", content: "중학교 때 나는 어떤 학생이었어?", answerType: "text" },
  { id: 1591, category: "tmi", content: "제일 좋아하는 날씨는 어떤 거야?", answerType: "text" },
  { id: 1592, category: "tmi", content: "내 방에서 가장 소중한 물건이 뭐야?", answerType: "text" },
  { id: 1593, category: "tmi", content: "올해 제일 잘 산 물건 떠올라?", answerType: "text" },
  { id: 1594, category: "tmi", content: "최근에 가장 감동받았던 순간 있을까?", answerType: "text" },
  { id: 1595, category: "tmi", content: "나의 소울푸드가 뭔지 궁금해~", answerType: "text" },
  { id: 1596, category: "tmi", content: "제일 좋아하는 향기가 뭐야?", answerType: "text" },
  // --- future (14) ---
  { id: 1597, category: "future", content: "나랑 같이 가보고 싶은 축제 있을까?", answerType: "text" },
  { id: 1598, category: "future", content: "우리 차를 산다면 어떤 게 어울릴까?", answerType: "text" },
  { id: 1599, category: "future", content: "나랑 같이 찍고 싶은 인생 사진 있어?", answerType: "text" },
  { id: 1600, category: "future", content: "우리 주방에 꼭 있으면 좋겠는 건?", answerType: "text" },
  { id: 1601, category: "future", content: "같이 가입해보고 싶은 모임이 있을까?", answerType: "text" },
  { id: 1602, category: "future", content: "우리 집에 꼭 필요한 공간이 있을까?", answerType: "text" },
  { id: 1603, category: "future", content: "같이 보고 싶은 공연이나 전시 떠올라?", answerType: "text" },
  { id: 1604, category: "future", content: "우리 연차 여행 계획 세워볼래?", answerType: "text" },
  { id: 1605, category: "future", content: "같이 도전해보고 싶은 챌린지 있을까?", answerType: "text" },
  { id: 1606, category: "future", content: "우리만의 아침 루틴을 만들어볼래?", answerType: "text" },
  { id: 1607, category: "future", content: "나랑 같이 만들어보고 싶은 영상 있어?", answerType: "text" },
  { id: 1608, category: "future", content: "우리 첫 집에서 꼭 하고 싶은 건?", answerType: "text" },
  { id: 1609, category: "future", content: "같이 읽어보고 싶은 책이 있을까?", answerType: "text" },
  { id: 1610, category: "future", content: "우리만의 기념일 전통을 만들어볼래?", answerType: "text" },
  // --- values (15) ---
  { id: 1611, category: "values", content: "살면서 가장 큰 깨달음이 뭐였어?", answerType: "text" },
  { id: 1612, category: "values", content: "갈등을 풀 때 제일 중요한 건 뭘까?", answerType: "text" },
  { id: 1613, category: "values", content: "감사한 마음을 어떻게 표현하고 싶어?", answerType: "text" },
  { id: 1614, category: "values", content: "너한테 약속이란 어떤 의미로 다가와?", answerType: "text" },
  { id: 1615, category: "values", content: "제일 소중한 생활 습관이 뭐야?", answerType: "text" },
  { id: 1616, category: "values", content: "너한테 효도란 어떤 마음이야?", answerType: "text" },
  { id: 1617, category: "values", content: "인생에서 꼭 경험하고 싶은 건 뭘까?", answerType: "text" },
  { id: 1618, category: "values", content: "겸손이란 어떤 거라고 느껴져?", answerType: "text" },
  { id: 1619, category: "values", content: "좋은 습관을 기르는 나만의 비결 있어?", answerType: "text" },
  { id: 1620, category: "values", content: "돈을 쓸 때 제일 중요한 기준이 뭐야?", answerType: "text" },
  { id: 1621, category: "values", content: "정직이 왜 소중하다고 느껴져?", answerType: "text" },
  { id: 1622, category: "values", content: "행복하려면 꼭 필요한 관계가 있을까?", answerType: "text" },
  { id: 1623, category: "values", content: "실패에서 배운 가장 큰 게 있을까?", answerType: "text" },
  { id: 1624, category: "values", content: "멋진 노후란 어떤 모습일 것 같아?", answerType: "text" },
  { id: 1625, category: "values", content: "사랑하는 사람에게 꼭 해주고 싶은 말은?", answerType: "text" },
  // --- pet (15) ---
  { id: 1626, category: "pet", content: "밀크의 표정 중 제일 웃긴 게 뭐야?", answerType: "text" },
  { id: 1627, category: "pet", content: "밀크가 노래를 부른다면 어떤 노래일까?", answerType: "text" },
  { id: 1628, category: "pet", content: "밀크가 졸업 앨범에 한마디 쓴다면?", answerType: "text" },
  { id: 1629, category: "pet", content: "밀크의 사랑 표현 방식은 어떤 걸까?", answerType: "text" },
  { id: 1630, category: "pet", content: "밀크가 선물을 준다면 뭘 줄 것 같아?", answerType: "text" },
  { id: 1631, category: "pet", content: "밀크에게 형제가 생긴다면 이름은 뭐야?", answerType: "text" },
  { id: 1632, category: "pet", content: "밀크가 자기 전에 하는 루틴이 있을까?", answerType: "text" },
  { id: 1633, category: "pet", content: "밀크가 화났을 때 어떤 표정을 지을까?", answerType: "text" },
  { id: 1634, category: "pet", content: "밀크의 제일 예쁜 각도가 어딜까?", answerType: "text" },
  { id: 1635, category: "pet", content: "밀크가 일기를 쓴다면 오늘 뭐라 쓸까?", answerType: "text" },
  { id: 1636, category: "pet", content: "밀크가 제일 좋아하는 시간대가 있을까?", answerType: "text" },
  { id: 1637, category: "pet", content: "밀크를 색깔로 표현하면 무슨 색이야?", answerType: "text" },
  { id: 1638, category: "pet", content: "우리 싸울 때 밀크는 무슨 생각할까?", answerType: "text" },
  { id: 1639, category: "pet", content: "밀크한테 제일 고마운 점이 뭐야?", answerType: "text" },
  { id: 1640, category: "pet", content: "밀크와 마지막으로 하고 싶은 건 뭘까?", answerType: "text" },
];
