import type { Question } from "@/types/question";

/** 추가 자유서술 질문 Part 1 (ID 1329-1432) */
export const TEXT_EXTRA_1: Question[] = [
  // --- honest (15) ---
  { id: 1329, category: "honest", content: "내가 잘 때 어떻게 보여? 솔직히~", answerType: "text" },
  { id: 1330, category: "honest", content: "나한테 제일 질투났던 순간 떠올라?", answerType: "text" },
  { id: 1331, category: "honest", content: "내 패션 센스 솔직히 어떤 것 같아?", answerType: "text" },
  { id: 1332, category: "honest", content: "나 없을 때 친구한테 내 얘기 해?", answerType: "text" },
  { id: 1333, category: "honest", content: "내가 고치면 좋을 습관 하나 있을까?", answerType: "text" },
  { id: 1334, category: "honest", content: "우리 연애에 점수를 매겨본다면?", answerType: "text" },
  { id: 1335, category: "honest", content: "내 요리 실력 솔직히 어떤 것 같아?", answerType: "text" },
  { id: 1336, category: "honest", content: "나랑 있을 때 좀 지루했던 적 있어?", answerType: "text" },
  { id: 1337, category: "honest", content: "내가 너무 집착한다고 느낀 적 있을까?", answerType: "text" },
  { id: 1338, category: "honest", content: "나의 어떤 점이 가끔 답답하게 느껴져?", answerType: "text" },
  { id: 1339, category: "honest", content: "우리 스킨십 솔직히 어떻게 느껴져?", answerType: "text" },
  { id: 1340, category: "honest", content: "내가 바꿨으면 하는 말투가 있을까?", answerType: "text" },
  { id: 1341, category: "honest", content: "나 보면서 속으로 한숨 쉰 적 있어?", answerType: "text" },
  { id: 1342, category: "honest", content: "내가 좀 매력 없게 느껴질 때 있어?", answerType: "text" },
  { id: 1343, category: "honest", content: "나한테 살짝 꺼내고 싶은 비밀 있을까?", answerType: "text" },
  // --- ifonly (15) ---
  { id: 1344, category: "ifonly", content: "내 마음을 들여다볼 수 있다면 뭐가 궁금해?", answerType: "text" },
  { id: 1345, category: "ifonly", content: "하루만 반대 성별이 된다면 뭐 해볼래?", answerType: "text" },
  { id: 1346, category: "ifonly", content: "기억 하나만 지울 수 있다면 어떤 거야?", answerType: "text" },
  { id: 1347, category: "ifonly", content: "동물로 변한다면 뭐가 되고 싶어?", answerType: "text" },
  { id: 1348, category: "ifonly", content: "영화 속 캐릭터가 된다면 누가 떠올라?", answerType: "text" },
  { id: 1349, category: "ifonly", content: "나랑 우주여행 간다면 뭐 해볼래?", answerType: "text" },
  { id: 1350, category: "ifonly", content: "하루만 유명인이 된다면 누가 되고 싶어?", answerType: "text" },
  { id: 1351, category: "ifonly", content: "마법으로 딱 하나 바꿀 수 있다면?", answerType: "text" },
  { id: 1352, category: "ifonly", content: "과거의 나에게 편지를 보낸다면 언제로?", answerType: "text" },
  { id: 1353, category: "ifonly", content: "일주일간 핸드폰 없이 지낼 수 있을까?", answerType: "text" },
  { id: 1354, category: "ifonly", content: "갑자기 재능이 하나 생긴다면 뭐면 좋겠어?", answerType: "text" },
  { id: 1355, category: "ifonly", content: "다른 시대에 태어난다면 언제가 좋아?", answerType: "text" },
  { id: 1356, category: "ifonly", content: "꿈을 현실로 만들 수 있다면 어떤 꿈이야?", answerType: "text" },
  { id: 1357, category: "ifonly", content: "하루만 어린이가 된다면 뭐 해볼래?", answerType: "text" },
  { id: 1358, category: "ifonly", content: "나랑 게임 세계에 들어간다면 뭐 할까?", answerType: "text" },
  // --- between (15) ---
  { id: 1359, category: "between", content: "우리 첫 데이트 때 뭐 입었는지 떠올라?", answerType: "text" },
  { id: 1360, category: "between", content: "나한테 처음 설렜던 순간 기억나?", answerType: "text" },
  { id: 1361, category: "between", content: "우리 관계를 한 단어로 담는다면?", answerType: "text" },
  { id: 1362, category: "between", content: "내가 자꾸 반복하는 습관 뭐가 떠올라?", answerType: "text" },
  { id: 1363, category: "between", content: "우리 커플 사진 중 제일 좋아하는 건?", answerType: "text" },
  { id: 1364, category: "between", content: "나랑 새벽에 같이 한 가장 재밌던 일은?", answerType: "text" },
  { id: 1365, category: "between", content: "우리가 가장 잘 통한다고 느꼈던 순간은?", answerType: "text" },
  { id: 1366, category: "between", content: "내가 전화하면 어떤 기분이 들어?", answerType: "text" },
  { id: 1367, category: "between", content: "우리 카톡 중에 제일 웃겼던 거 떠올라?", answerType: "text" },
  { id: 1368, category: "between", content: "내가 지어준 별명 중에 제일 좋은 건?", answerType: "text" },
  { id: 1369, category: "between", content: "나한테 받은 문자 중 가장 감동적인 건?", answerType: "text" },
  { id: 1370, category: "between", content: "우리가 같이 울었던 적 있었을까?", answerType: "text" },
  { id: 1371, category: "between", content: "나랑 같이 있을 때 시간이 제일 빨리 갈 때?", answerType: "text" },
  { id: 1372, category: "between", content: "우리만의 소소한 전통이 있다면 뭘까?", answerType: "text" },
  { id: 1373, category: "between", content: "나한테 가장 사랑받는다고 느꼈던 순간은?", answerType: "text" },
  // --- tmi (15) ---
  { id: 1374, category: "tmi", content: "어릴 때 제일 좋아했던 만화 떠올라?", answerType: "text" },
  { id: 1375, category: "tmi", content: "인생에서 가장 오래된 기억이 뭐야?", answerType: "text" },
  { id: 1376, category: "tmi", content: "가장 오래 입은 옷이 있어? 뭐야?", answerType: "text" },
  { id: 1377, category: "tmi", content: "SNS에서 요즘 제일 많이 보는 건?", answerType: "text" },
  { id: 1378, category: "tmi", content: "아침에 눈 뜨면 제일 먼저 뭐 해?", answerType: "text" },
  { id: 1379, category: "tmi", content: "노래방 가면 꼭 부르는 애창곡 있어?", answerType: "text" },
  { id: 1380, category: "tmi", content: "최근에 충동구매한 거 뭐가 떠올라?", answerType: "text" },
  { id: 1381, category: "tmi", content: "잠들기 전에 꼭 하는 루틴 있을까?", answerType: "text" },
  { id: 1382, category: "tmi", content: "나만 아는 꿀맛 음식 조합 있어?", answerType: "text" },
  { id: 1383, category: "tmi", content: "초등학교 때 제일 기억나는 일이 뭐야?", answerType: "text" },
  { id: 1384, category: "tmi", content: "요즘 새로 빠진 취미 있어?", answerType: "text" },
  { id: 1385, category: "tmi", content: "학교 급식 중 최고의 메뉴 떠올라?", answerType: "text" },
  { id: 1386, category: "tmi", content: "길에서 제일 창피했던 순간 있을까?", answerType: "text" },
  { id: 1387, category: "tmi", content: "가장 오래 유지하고 있는 습관이 뭐야?", answerType: "text" },
  { id: 1388, category: "tmi", content: "지금 가방 안에 뭐가 들어있어?", answerType: "text" },
  // --- future (15) ---
  { id: 1389, category: "future", content: "우리 신혼여행 어디로 가면 좋을까?", answerType: "text" },
  { id: 1390, category: "future", content: "나랑 같이 배워보고 싶은 거 있을까?", answerType: "text" },
  { id: 1391, category: "future", content: "우리 집에 꼭 있으면 좋겠는 건?", answerType: "text" },
  { id: 1392, category: "future", content: "나이 들면 어떤 모습일 것 같아?", answerType: "text" },
  { id: 1393, category: "future", content: "같이 만들고 싶은 버킷리스트 떠올라?", answerType: "text" },
  { id: 1394, category: "future", content: "우리 결혼기념일엔 뭐 하면 좋을까?", answerType: "text" },
  { id: 1395, category: "future", content: "나랑 같이 운영해보고 싶은 거 있을까?", answerType: "text" },
  { id: 1396, category: "future", content: "우리 아이한테 알려주고 싶은 가치는?", answerType: "text" },
  { id: 1397, category: "future", content: "10년 뒤에도 꼭 같이 하고 싶은 건?", answerType: "text" },
  { id: 1398, category: "future", content: "나랑 같이 가꿔보고 싶은 공간 있어?", answerType: "text" },
  { id: 1399, category: "future", content: "우리 나중에 어떤 동네에 살면 좋을까?", answerType: "text" },
  { id: 1400, category: "future", content: "50대가 되면 우리 뭐 하고 있을까?", answerType: "text" },
  { id: 1401, category: "future", content: "나랑 같이 도전해보고 싶은 운동 있어?", answerType: "text" },
  { id: 1402, category: "future", content: "우리 결혼식은 어떤 분위기면 좋겠어?", answerType: "text" },
  { id: 1403, category: "future", content: "올해 우리 같이 이루고 싶은 목표 있을까?", answerType: "text" },
  // --- values (14) ---
  { id: 1404, category: "values", content: "사랑이랑 우정 중에 뭐가 더 소중해?", answerType: "text" },
  { id: 1405, category: "values", content: "돈이랑 시간 중에 뭐가 더 귀하게 느껴져?", answerType: "text" },
  { id: 1406, category: "values", content: "너한테 가족이란 어떤 의미로 다가와?", answerType: "text" },
  { id: 1407, category: "values", content: "인생에서 절대 포기 못하는 게 있을까?", answerType: "text" },
  { id: 1408, category: "values", content: "좋은 부모란 어떤 모습일 것 같아?", answerType: "text" },
  { id: 1409, category: "values", content: "용서하기 가장 어려운 건 어떤 거야?", answerType: "text" },
  { id: 1410, category: "values", content: "행복한 노후에 가장 필요한 게 뭘까?", answerType: "text" },
  { id: 1411, category: "values", content: "진짜 친구의 기준이 뭐라고 느껴?", answerType: "text" },
  { id: 1412, category: "values", content: "마음속 좌우명 같은 게 있을까?", answerType: "text" },
  { id: 1413, category: "values", content: "성공이란 어떤 거라고 느껴져?", answerType: "text" },
  { id: 1414, category: "values", content: "절약이랑 투자 중 뭐가 더 와닿아?", answerType: "text" },
  { id: 1415, category: "values", content: "어떤 어른이 되고 싶은지 떠올라?", answerType: "text" },
  { id: 1416, category: "values", content: "결혼 생활에서 제일 소중한 건 뭘까?", answerType: "text" },
  { id: 1417, category: "values", content: "일과 삶의 균형이 너한텐 어떤 의미야?", answerType: "text" },
  // --- pet (15) ---
  { id: 1418, category: "pet", content: "밀크가 제일 귀여운 순간 떠올라?", answerType: "text" },
  { id: 1419, category: "pet", content: "밀크가 꿈을 꾼다면 어떤 꿈일까?", answerType: "text" },
  { id: 1420, category: "pet", content: "밀크한테 슈퍼파워가 생기면 뭘까?", answerType: "text" },
  { id: 1421, category: "pet", content: "밀크가 제일 좋아하는 장소가 어딜까?", answerType: "text" },
  { id: 1422, category: "pet", content: "밀크 SNS를 만든다면 이름은 뭐가 좋아?", answerType: "text" },
  { id: 1423, category: "pet", content: "밀크가 제일 싫어하는 건 뭘까?", answerType: "text" },
  { id: 1424, category: "pet", content: "밀크 생일 파티를 연다면 어떻게 해볼래?", answerType: "text" },
  { id: 1425, category: "pet", content: "밀크가 직업을 가진다면 뭐가 어울릴까?", answerType: "text" },
  { id: 1426, category: "pet", content: "밀크랑 여행 간다면 어디가 좋을까?", answerType: "text" },
  { id: 1427, category: "pet", content: "밀크가 제일 잘하는 건 뭘까?", answerType: "text" },
  { id: 1428, category: "pet", content: "밀크한테 해주고 싶은 말 하나 떠올라?", answerType: "text" },
  { id: 1429, category: "pet", content: "밀크가 유튜버가 되면 뭘 찍을까?", answerType: "text" },
  { id: 1430, category: "pet", content: "밀크 친구가 된다면 뭐 하며 놀까?", answerType: "text" },
  { id: 1431, category: "pet", content: "밀크가 요리를 한다면 뭘 만들까?", answerType: "text" },
  { id: 1432, category: "pet", content: "밀크랑 대화할 수 있는 하루가 온다면?", answerType: "text" },
];
