import type { Question } from "@/types/question";

/** 추가 자유서술 질문 Part 1 (ID 1329-1432) */
export const TEXT_EXTRA_1: Question[] = [
  // --- honest (15) ---
  { id: 1329, category: "honest", content: "내가 잘 때 솔직히 어떻게 생겼어?", answerType: "text" },
  { id: 1330, category: "honest", content: "나한테 가장 질투났던 순간은?", answerType: "text" },
  { id: 1331, category: "honest", content: "솔직히 내 패션 센스 어떤 것 같아?", answerType: "text" },
  { id: 1332, category: "honest", content: "나 없을 때 나 얘기 친구한테 해?", answerType: "text" },
  { id: 1333, category: "honest", content: "내가 고쳐야 할 습관 하나만 말해줘", answerType: "text" },
  { id: 1334, category: "honest", content: "우리 연애에 점수를 매긴다면?", answerType: "text" },
  { id: 1335, category: "honest", content: "내 요리 실력 솔직히 몇 점이야?", answerType: "text" },
  { id: 1336, category: "honest", content: "나랑 있을 때 가장 지루했던 때는?", answerType: "text" },
  { id: 1337, category: "honest", content: "내가 너무 집착한다고 느낀 적 있어?", answerType: "text" },
  { id: 1338, category: "honest", content: "나의 어떤 점이 가장 답답해?", answerType: "text" },
  { id: 1339, category: "honest", content: "솔직히 우리 스킨십 만족해?", answerType: "text" },
  { id: 1340, category: "honest", content: "내가 변했으면 하는 말투가 있어?", answerType: "text" },
  { id: 1341, category: "honest", content: "나 보면서 속으로 한숨 쉰 적 있어?", answerType: "text" },
  { id: 1342, category: "honest", content: "내가 가장 매력 없을 때는 언제야?", answerType: "text" },
  { id: 1343, category: "honest", content: "나한테 꼭 고백하고 싶은 비밀 있어?", answerType: "text" },
  // --- ifonly (15) ---
  { id: 1344, category: "ifonly", content: "내 마음을 읽을 수 있다면 뭘 알고 싶어?", answerType: "text" },
  { id: 1345, category: "ifonly", content: "하루만 반대 성별이 된다면 뭐 할래?", answerType: "text" },
  { id: 1346, category: "ifonly", content: "기억 하나만 지울 수 있다면 뭘 지울래?", answerType: "text" },
  { id: 1347, category: "ifonly", content: "동물로 변한다면 뭐가 되고 싶어?", answerType: "text" },
  { id: 1348, category: "ifonly", content: "영화 속 캐릭터가 된다면 누구?", answerType: "text" },
  { id: 1349, category: "ifonly", content: "나랑 우주여행 가면 뭐 하고 싶어?", answerType: "text" },
  { id: 1350, category: "ifonly", content: "하루만 유명인이 된다면 누가 될래?", answerType: "text" },
  { id: 1351, category: "ifonly", content: "마법으로 하나만 바꿀 수 있다면?", answerType: "text" },
  { id: 1352, category: "ifonly", content: "과거에 편지를 보낼 수 있다면 언제?", answerType: "text" },
  { id: 1353, category: "ifonly", content: "1주일간 핸드폰 없이 살 수 있어?", answerType: "text" },
  { id: 1354, category: "ifonly", content: "갑자기 재능이 하나 생긴다면 뭐 원해?", answerType: "text" },
  { id: 1355, category: "ifonly", content: "다른 시대에 태어난다면 어느 시대?", answerType: "text" },
  { id: 1356, category: "ifonly", content: "꿈을 현실로 만들 수 있다면 어떤 꿈?", answerType: "text" },
  { id: 1357, category: "ifonly", content: "하루만 어린이가 된다면 뭐 할래?", answerType: "text" },
  { id: 1358, category: "ifonly", content: "나랑 게임 세계에 들어가면 뭐 할래?", answerType: "text" },
  // --- between (15) ---
  { id: 1359, category: "between", content: "우리 첫 데이트 때 뭐 입었는지 기억나?", answerType: "text" },
  { id: 1360, category: "between", content: "나한테 처음 설렌 순간이 언제야?", answerType: "text" },
  { id: 1361, category: "between", content: "우리 관계를 한 단어로 표현하면?", answerType: "text" },
  { id: 1362, category: "between", content: "나한테 반복하는 습관 뭐가 있어?", answerType: "text" },
  { id: 1363, category: "between", content: "우리 커플 사진 중 제일 좋아하는 거는?", answerType: "text" },
  { id: 1364, category: "between", content: "나랑 같이 새벽에 한 제일 재밌던 일은?", answerType: "text" },
  { id: 1365, category: "between", content: "우리가 가장 잘 통한다고 느낀 순간은?", answerType: "text" },
  { id: 1366, category: "between", content: "내가 전화하면 기분이 어때?", answerType: "text" },
  { id: 1367, category: "between", content: "우리 카톡 대화 중 가장 웃긴 건?", answerType: "text" },
  { id: 1368, category: "between", content: "내가 만든 별명 중에 제일 좋은 거는?", answerType: "text" },
  { id: 1369, category: "between", content: "나한테 가장 감동받은 문자는?", answerType: "text" },
  { id: 1370, category: "between", content: "우리가 같이 울었던 적 있어?", answerType: "text" },
  { id: 1371, category: "between", content: "나랑 같이 할 때 시간이 제일 빨리 갈 때?", answerType: "text" },
  { id: 1372, category: "between", content: "우리만의 전통이 있다면 뭐야?", answerType: "text" },
  { id: 1373, category: "between", content: "나한테 가장 많이 사랑받는다고 느낀 때?", answerType: "text" },
  // --- tmi (15) ---
  { id: 1374, category: "tmi", content: "어릴 때 가장 좋아했던 만화는?", answerType: "text" },
  { id: 1375, category: "tmi", content: "인생 첫 번째 기억이 뭐야?", answerType: "text" },
  { id: 1376, category: "tmi", content: "가장 오래 입은 옷이 뭐야?", answerType: "text" },
  { id: 1377, category: "tmi", content: "SNS에서 가장 많이 보는 컨텐츠는?", answerType: "text" },
  { id: 1378, category: "tmi", content: "아침에 일어나서 제일 먼저 하는 건?", answerType: "text" },
  { id: 1379, category: "tmi", content: "가장 자신 있는 노래방 애창곡은?", answerType: "text" },
  { id: 1380, category: "tmi", content: "최근에 가장 충동구매한 건?", answerType: "text" },
  { id: 1381, category: "tmi", content: "잠들기 전 꼭 하는 루틴이 있어?", answerType: "text" },
  { id: 1382, category: "tmi", content: "나만 아는 꿀맛 음식 조합이 있어?", answerType: "text" },
  { id: 1383, category: "tmi", content: "초등학교 때 가장 기억나는 일은?", answerType: "text" },
  { id: 1384, category: "tmi", content: "가장 최근에 빠진 취미는 뭐야?", answerType: "text" },
  { id: 1385, category: "tmi", content: "내 인생 최고의 급식 메뉴는?", answerType: "text" },
  { id: 1386, category: "tmi", content: "길에서 가장 창피했던 경험은?", answerType: "text" },
  { id: 1387, category: "tmi", content: "가장 오래 유지한 습관이 뭐야?", answerType: "text" },
  { id: 1388, category: "tmi", content: "지금 가방 안에 뭐가 들어있어?", answerType: "text" },
  // --- future (15) ---
  { id: 1389, category: "future", content: "우리 신혼여행 어디로 가고 싶어?", answerType: "text" },
  { id: 1390, category: "future", content: "같이 배우고 싶은 것 하나는?", answerType: "text" },
  { id: 1391, category: "future", content: "우리 집에 꼭 있었으면 하는 건?", answerType: "text" },
  { id: 1392, category: "future", content: "나이 들면 어떤 할머니/할아버지가 될까?", answerType: "text" },
  { id: 1393, category: "future", content: "같이 만들고 싶은 커플 버킷리스트 3개?", answerType: "text" },
  { id: 1394, category: "future", content: "우리 결혼기념일에 뭐 하고 싶어?", answerType: "text" },
  { id: 1395, category: "future", content: "같이 운영해보고 싶은 것이 있다면?", answerType: "text" },
  { id: 1396, category: "future", content: "우리 아이한테 가르치고 싶은 가치는?", answerType: "text" },
  { id: 1397, category: "future", content: "10년 뒤에도 꼭 같이 하고 싶은 건?", answerType: "text" },
  { id: 1398, category: "future", content: "같이 가꾸고 싶은 공간이 있다면?", answerType: "text" },
  { id: 1399, category: "future", content: "우리 노후에 살고 싶은 동네는?", answerType: "text" },
  { id: 1400, category: "future", content: "50대가 되면 뭐 하고 있을 것 같아?", answerType: "text" },
  { id: 1401, category: "future", content: "같이 도전해보고 싶은 스포츠는?", answerType: "text" },
  { id: 1402, category: "future", content: "우리 결혼식 컨셉은 어떤 게 좋아?", answerType: "text" },
  { id: 1403, category: "future", content: "이루고 싶은 올해 커플 목표 하나는?", answerType: "text" },
  // --- values (14) ---
  { id: 1404, category: "values", content: "사랑이랑 우정 중에 뭐가 더 중요해?", answerType: "text" },
  { id: 1405, category: "values", content: "돈이랑 시간 중에 뭐가 더 소중해?", answerType: "text" },
  { id: 1406, category: "values", content: "나한테 가족이란 어떤 의미야?", answerType: "text" },
  { id: 1407, category: "values", content: "인생에서 절대 포기 못하는 건?", answerType: "text" },
  { id: 1408, category: "values", content: "좋은 부모란 어떤 거라고 생각해?", answerType: "text" },
  { id: 1409, category: "values", content: "용서하기 가장 어려운 잘못이 뭐야?", answerType: "text" },
  { id: 1410, category: "values", content: "행복한 노후에 가장 필요한 건?", answerType: "text" },
  { id: 1411, category: "values", content: "진짜 친구의 기준이 뭐야?", answerType: "text" },
  { id: 1412, category: "values", content: "내 인생의 좌우명은 뭐야?", answerType: "text" },
  { id: 1413, category: "values", content: "성공의 기준이 뭐라고 생각해?", answerType: "text" },
  { id: 1414, category: "values", content: "절약과 투자 중에 뭐가 중요해?", answerType: "text" },
  { id: 1415, category: "values", content: "어떤 어른이 되고 싶어?", answerType: "text" },
  { id: 1416, category: "values", content: "결혼 생활에서 가장 중요한 건?", answerType: "text" },
  { id: 1417, category: "values", content: "나한테 일과 삶의 균형이란?", answerType: "text" },
  // --- pet (15) ---
  { id: 1418, category: "pet", content: "밀크가 가장 귀여울 때는 언제야?", answerType: "text" },
  { id: 1419, category: "pet", content: "밀크가 꿈을 꾼다면 무슨 꿈일까?", answerType: "text" },
  { id: 1420, category: "pet", content: "밀크한테 슈퍼파워가 생기면 뭘까?", answerType: "text" },
  { id: 1421, category: "pet", content: "밀크가 좋아하는 장소가 어디일까?", answerType: "text" },
  { id: 1422, category: "pet", content: "밀크 SNS 계정을 만든다면 이름은?", answerType: "text" },
  { id: 1423, category: "pet", content: "밀크가 가장 싫어하는 건 뭘까?", answerType: "text" },
  { id: 1424, category: "pet", content: "밀크 생일 파티를 한다면 어떻게?", answerType: "text" },
  { id: 1425, category: "pet", content: "밀크가 직업을 가진다면 뭘 할까?", answerType: "text" },
  { id: 1426, category: "pet", content: "밀크랑 같이 여행 간다면 어디?", answerType: "text" },
  { id: 1427, category: "pet", content: "밀크가 가장 잘하는 건 뭘까?", answerType: "text" },
  { id: 1428, category: "pet", content: "밀크한테 해주고 싶은 말 하나는?", answerType: "text" },
  { id: 1429, category: "pet", content: "밀크가 유튜버가 되면 컨텐츠는?", answerType: "text" },
  { id: 1430, category: "pet", content: "밀크의 친구가 된다면 뭐 하고 놀까?", answerType: "text" },
  { id: 1431, category: "pet", content: "밀크가 요리를 한다면 뭘 만들까?", answerType: "text" },
  { id: 1432, category: "pet", content: "밀크와 대화할 수 있는 하루가 온다면?", answerType: "text" },
];
