import type { Question } from "@/types/question";

/** 추가 자유서술 질문 Part 2 (ID 1433-1536) */
export const TEXT_EXTRA_2: Question[] = [
  // --- honest (15) ---
  { id: 1433, category: "honest", content: "내가 화낼 때 솔직히 좀 무섭게 느껴져?", answerType: "text" },
  { id: 1434, category: "honest", content: "나한테 속상했는데 참았던 적 있을까?", answerType: "text" },
  { id: 1435, category: "honest", content: "내 친구들 중에 살짝 불편한 사람 있어?", answerType: "text" },
  { id: 1436, category: "honest", content: "나랑 사귀면서 포기하게 된 게 있을까?", answerType: "text" },
  { id: 1437, category: "honest", content: "내가 좀 못한다고 느끼는 게 있어?", answerType: "text" },
  { id: 1438, category: "honest", content: "나한테 살짝 실망했던 순간이 있을까?", answerType: "text" },
  { id: 1439, category: "honest", content: "내 운전 실력 솔직히 어떻게 느껴져?", answerType: "text" },
  { id: 1440, category: "honest", content: "나한테 작은 거짓말 했던 적 있을까?", answerType: "text" },
  { id: 1441, category: "honest", content: "내 말투에서 고치면 좋을 점 있을까?", answerType: "text" },
  { id: 1442, category: "honest", content: "내가 무관심하다고 느꼈던 적 있어?", answerType: "text" },
  { id: 1443, category: "honest", content: "나랑 있으면서 외로웠던 적 있었을까?", answerType: "text" },
  { id: 1444, category: "honest", content: "내 외모 중에 제일 좋아하는 부분은?", answerType: "text" },
  { id: 1445, category: "honest", content: "내가 다른 사람한테 하면 질투나는 행동?", answerType: "text" },
  { id: 1446, category: "honest", content: "우리 대화가 솔직히 어떻게 느껴져?", answerType: "text" },
  { id: 1447, category: "honest", content: "나한테 고마우면서도 미안한 점이 있을까?", answerType: "text" },
  // --- ifonly (15) ---
  { id: 1448, category: "ifonly", content: "나랑 다른 행성에서 산다면 어디가 좋아?", answerType: "text" },
  { id: 1449, category: "ifonly", content: "100년 전에 태어났다면 뭐 하며 살았을까?", answerType: "text" },
  { id: 1450, category: "ifonly", content: "내 감정이 색깔로 보인다면 어떨까?", answerType: "text" },
  { id: 1451, category: "ifonly", content: "하루만 거인이 된다면 뭐 해볼래?", answerType: "text" },
  { id: 1452, category: "ifonly", content: "평생 음식 하나만 먹어야 한다면 뭘까?", answerType: "text" },
  { id: 1453, category: "ifonly", content: "나랑 만화 속에 들어간다면 어떤 만화?", answerType: "text" },
  { id: 1454, category: "ifonly", content: "지금 어디든 순간이동 한다면 어디로 갈래?", answerType: "text" },
  { id: 1455, category: "ifonly", content: "하루가 48시간이라면 뭐 해볼래?", answerType: "text" },
  { id: 1456, category: "ifonly", content: "언어를 하나 더 배울 수 있다면 뭘 할래?", answerType: "text" },
  { id: 1457, category: "ifonly", content: "드라마 속 커플이 된다면 어떤 드라마?", answerType: "text" },
  { id: 1458, category: "ifonly", content: "타임머신이 있다면 미래랑 과거 중 어디?", answerType: "text" },
  { id: 1459, category: "ifonly", content: "나랑 카페를 연다면 어떤 분위기가 좋아?", answerType: "text" },
  { id: 1460, category: "ifonly", content: "보이지 않는 힘이 생기면 뭐에 쓰고 싶어?", answerType: "text" },
  { id: 1461, category: "ifonly", content: "나랑 무인도에 가면 제일 먼저 뭐 할까?", answerType: "text" },
  { id: 1462, category: "ifonly", content: "날씨를 마음대로 바꿀 수 있다면 어떨까?", answerType: "text" },
  // --- between (15) ---
  { id: 1463, category: "between", content: "나한테 받은 편지 중 기억나는 거 있어?", answerType: "text" },
  { id: 1464, category: "between", content: "우리가 제일 심하게 싸웠던 이유 떠올라?", answerType: "text" },
  { id: 1465, category: "between", content: "나 때문에 제일 많이 웃었던 날 기억나?", answerType: "text" },
  { id: 1466, category: "between", content: "우리 처음 뽀뽀한 날 기억나?", answerType: "text" },
  { id: 1467, category: "between", content: "내가 가장 든든하게 느껴졌던 순간은?", answerType: "text" },
  { id: 1468, category: "between", content: "우리 기념일 중에 가장 좋았던 건?", answerType: "text" },
  { id: 1469, category: "between", content: "나랑 대화할 때 제일 잘 통하는 주제는?", answerType: "text" },
  { id: 1470, category: "between", content: "우리 커플템 중에 가장 마음에 드는 건?", answerType: "text" },
  { id: 1471, category: "between", content: "비 오는 날 나랑 함께한 추억 떠올라?", answerType: "text" },
  { id: 1472, category: "between", content: "내가 울 때 어떻게 해주면 좋겠어?", answerType: "text" },
  { id: 1473, category: "between", content: "우리가 아직 못 해본 게 아쉬운 건?", answerType: "text" },
  { id: 1474, category: "between", content: "나한테 받은 서프라이즈 중 최고는 뭐야?", answerType: "text" },
  { id: 1475, category: "between", content: "우리 영상통화 중 제일 웃겼던 때 있어?", answerType: "text" },
  { id: 1476, category: "between", content: "나랑 같이 먹었던 최고의 음식 떠올라?", answerType: "text" },
  { id: 1477, category: "between", content: "우리 사이에서 함께 성장한 부분이 있을까?", answerType: "text" },
  // --- tmi (15) ---
  { id: 1478, category: "tmi", content: "어릴 때 제일 무서워했던 게 뭐야?", answerType: "text" },
  { id: 1479, category: "tmi", content: "요즘 제일 빠져있는 유튜브 채널 있어?", answerType: "text" },
  { id: 1480, category: "tmi", content: "인생 최고의 생일 선물 뭐였는지 떠올라?", answerType: "text" },
  { id: 1481, category: "tmi", content: "제일 좋아하는 계절은 뭐야? 이유도~", answerType: "text" },
  { id: 1482, category: "tmi", content: "스트레스 받으면 어떻게 풀어?", answerType: "text" },
  { id: 1483, category: "tmi", content: "기억에 남는 학교 선생님 떠올라?", answerType: "text" },
  { id: 1484, category: "tmi", content: "인생에서 가장 용감했던 순간이 있을까?", answerType: "text" },
  { id: 1485, category: "tmi", content: "지금까지 받은 최고의 칭찬이 뭐였어?", answerType: "text" },
  { id: 1486, category: "tmi", content: "어릴 때 제일 좋아했던 놀이가 뭐야?", answerType: "text" },
  { id: 1487, category: "tmi", content: "가장 오래 줄 서봤던 적 있어?", answerType: "text" },
  { id: 1488, category: "tmi", content: "편의점 가면 꼭 사는 간식 있을까?", answerType: "text" },
  { id: 1489, category: "tmi", content: "제일 후회되는 머리 스타일 떠올라?", answerType: "text" },
  { id: 1490, category: "tmi", content: "나만의 독특한 잠버릇이 있을까?", answerType: "text" },
  { id: 1491, category: "tmi", content: "인생 첫 알바 경험 어땠어?", answerType: "text" },
  { id: 1492, category: "tmi", content: "절대 안 질리는 노래 하나 있어?", answerType: "text" },
  // --- future (14) ---
  { id: 1493, category: "future", content: "나랑 같이 만들어보고 싶은 요리 있어?", answerType: "text" },
  { id: 1494, category: "future", content: "같이 늙어서 꼭 해보고 싶은 거 있을까?", answerType: "text" },
  { id: 1495, category: "future", content: "우리 거실에 꼭 놓고 싶은 가구 있어?", answerType: "text" },
  { id: 1496, category: "future", content: "같이 키워보고 싶은 식물 있을까?", answerType: "text" },
  { id: 1497, category: "future", content: "우리 결혼 반지는 어떤 게 어울릴까?", answerType: "text" },
  { id: 1498, category: "future", content: "나랑 같이 해보고 싶은 봉사활동 있어?", answerType: "text" },
  { id: 1499, category: "future", content: "우리만의 주말 루틴을 만든다면?", answerType: "text" },
  { id: 1500, category: "future", content: "같이 달성하고 싶은 저축 목표 있을까?", answerType: "text" },
  { id: 1501, category: "future", content: "우리 아이 방을 꾸민다면 어떤 느낌?", answerType: "text" },
  { id: 1502, category: "future", content: "같이 자주 가고 싶은 단골 가게 있어?", answerType: "text" },
  { id: 1503, category: "future", content: "우리만의 크리스마스 전통을 만들어볼래?", answerType: "text" },
  { id: 1504, category: "future", content: "같이 가계부를 쓴다면 어떤 방식이 좋아?", answerType: "text" },
  { id: 1505, category: "future", content: "5년 뒤 우리 모습은 어떨 것 같아?", answerType: "text" },
  { id: 1506, category: "future", content: "나랑 같이 시작해보고 싶은 운동 있어?", answerType: "text" },
  // --- values (15) ---
  { id: 1507, category: "values", content: "너한테 신뢰란 어떤 느낌이야?", answerType: "text" },
  { id: 1508, category: "values", content: "나이 들수록 소중해지는 건 뭘까?", answerType: "text" },
  { id: 1509, category: "values", content: "인생에서 터닝포인트가 된 순간 떠올라?", answerType: "text" },
  { id: 1510, category: "values", content: "후회 없이 살려면 뭐가 필요할까?", answerType: "text" },
  { id: 1511, category: "values", content: "배려가 가장 빛나는 순간은 언제일까?", answerType: "text" },
  { id: 1512, category: "values", content: "돈보다 더 가치 있는 것 3가지 떠올라?", answerType: "text" },
  { id: 1513, category: "values", content: "좋은 대화란 어떤 거라고 느껴져?", answerType: "text" },
  { id: 1514, category: "values", content: "마음이 평화로워지려면 뭐가 필요해?", answerType: "text" },
  { id: 1515, category: "values", content: "나를 키운 건 사랑일까 고난일까?", answerType: "text" },
  { id: 1516, category: "values", content: "사과할 때 가장 중요한 건 뭘까?", answerType: "text" },
  { id: 1517, category: "values", content: "살면서 가장 잘한 선택이 뭐였어?", answerType: "text" },
  { id: 1518, category: "values", content: "너한테 건강이란 어떤 의미로 다가와?", answerType: "text" },
  { id: 1519, category: "values", content: "좋은 리더는 어떤 사람이라고 느껴?", answerType: "text" },
  { id: 1520, category: "values", content: "혼자만의 시간이 왜 소중하게 느껴져?", answerType: "text" },
  { id: 1521, category: "values", content: "진정한 용기란 어떤 거라고 느껴져?", answerType: "text" },
  // --- pet (15) ---
  { id: 1522, category: "pet", content: "밀크가 학교 다닌다면 좋아할 과목은?", answerType: "text" },
  { id: 1523, category: "pet", content: "밀크의 MBTI는 뭘 것 같아?", answerType: "text" },
  { id: 1524, category: "pet", content: "밀크에게 옷을 입힌다면 어떤 느낌?", answerType: "text" },
  { id: 1525, category: "pet", content: "밀크가 제일 잘 알아듣는 말이 뭘까?", answerType: "text" },
  { id: 1526, category: "pet", content: "밀크가 좋아하는 간식 순위 매겨볼래?", answerType: "text" },
  { id: 1527, category: "pet", content: "밀크한테 동생이 생기면 어떨 것 같아?", answerType: "text" },
  { id: 1528, category: "pet", content: "밀크가 제일 기뻐하는 순간 떠올라?", answerType: "text" },
  { id: 1529, category: "pet", content: "밀크의 하루를 시간표로 만들어볼래?", answerType: "text" },
  { id: 1530, category: "pet", content: "밀크가 우리 말을 다 알아듣는다면?", answerType: "text" },
  { id: 1531, category: "pet", content: "밀크가 제일 무서워하는 건 뭘까?", answerType: "text" },
  { id: 1532, category: "pet", content: "밀크를 한 문장으로 소개해볼래?", answerType: "text" },
  { id: 1533, category: "pet", content: "밀크가 영화 주인공이 된다면 장르는?", answerType: "text" },
  { id: 1534, category: "pet", content: "밀크한테 제일 미안했던 순간 있을까?", answerType: "text" },
  { id: 1535, category: "pet", content: "밀크의 베프가 될 동물은 뭘까?", answerType: "text" },
  { id: 1536, category: "pet", content: "밀크가 다른 댕댕이를 만나면 뭐라 할까?", answerType: "text" },
];
