import type { Question } from "@/types/question";

/** 추가 자유서술 질문 Part 2 (ID 1433-1536) */
export const TEXT_EXTRA_2: Question[] = [
  // --- honest (15) ---
  { id: 1433, category: "honest", content: "내가 화낼 때 솔직히 무섭다고 느껴?", answerType: "text" },
  { id: 1434, category: "honest", content: "나한테 속상했는데 참은 적 있어?", answerType: "text" },
  { id: 1435, category: "honest", content: "내 친구들 중에 솔직히 불편한 사람 있어?", answerType: "text" },
  { id: 1436, category: "honest", content: "나랑 사귀면서 포기한 게 있어?", answerType: "text" },
  { id: 1437, category: "honest", content: "솔직히 내가 가장 못하는 게 뭐야?", answerType: "text" },
  { id: 1438, category: "honest", content: "나한테 실망했던 적 있으면 말해줘", answerType: "text" },
  { id: 1439, category: "honest", content: "내 운전 실력 솔직히 어때?", answerType: "text" },
  { id: 1440, category: "honest", content: "나한테 거짓말한 적 있어? 뭐였어?", answerType: "text" },
  { id: 1441, category: "honest", content: "솔직히 내 말투에서 고칠 점 있어?", answerType: "text" },
  { id: 1442, category: "honest", content: "내가 너무 무관심하다고 느낀 적 있어?", answerType: "text" },
  { id: 1443, category: "honest", content: "나랑 있을 때 외로운 적 있었어?", answerType: "text" },
  { id: 1444, category: "honest", content: "나의 외모 중 가장 좋은 부분은?", answerType: "text" },
  { id: 1445, category: "honest", content: "내가 다른 사람한테 하면 질투나는 행동?", answerType: "text" },
  { id: 1446, category: "honest", content: "솔직히 우리 대화 만족스러워?", answerType: "text" },
  { id: 1447, category: "honest", content: "나한테 가장 고마우면서 미안한 점은?", answerType: "text" },
  // --- ifonly (15) ---
  { id: 1448, category: "ifonly", content: "나랑 다른 행성에서 산다면 어디?", answerType: "text" },
  { id: 1449, category: "ifonly", content: "100년 전에 태어났다면 뭐 하고 살까?", answerType: "text" },
  { id: 1450, category: "ifonly", content: "내 감정을 색깔로 볼 수 있다면?", answerType: "text" },
  { id: 1451, category: "ifonly", content: "하루만 거인이 된다면 뭐 할래?", answerType: "text" },
  { id: 1452, category: "ifonly", content: "음식을 하나만 평생 먹어야 한다면?", answerType: "text" },
  { id: 1453, category: "ifonly", content: "나랑 만화 속에 들어간다면 어떤 만화?", answerType: "text" },
  { id: 1454, category: "ifonly", content: "지금 어디든 순간이동 할 수 있다면?", answerType: "text" },
  { id: 1455, category: "ifonly", content: "하루 48시간이 된다면 뭐 할래?", answerType: "text" },
  { id: 1456, category: "ifonly", content: "언어를 하나 더 할 수 있다면 뭘 배울래?", answerType: "text" },
  { id: 1457, category: "ifonly", content: "드라마 속 커플이 된다면 어떤 드라마?", answerType: "text" },
  { id: 1458, category: "ifonly", content: "타임머신이 있다면 미래 vs 과거?", answerType: "text" },
  { id: 1459, category: "ifonly", content: "나랑 카페를 열면 어떤 컨셉이 좋아?", answerType: "text" },
  { id: 1460, category: "ifonly", content: "보이지 않는 힘이 생기면 뭐에 쓸래?", answerType: "text" },
  { id: 1461, category: "ifonly", content: "나랑 무인도에 가면 가장 먼저 뭐 할래?", answerType: "text" },
  { id: 1462, category: "ifonly", content: "날씨를 조종할 수 있다면 어떻게 할래?", answerType: "text" },
  // --- between (15) ---
  { id: 1463, category: "between", content: "나한테 받은 편지 중에 기억나는 거?", answerType: "text" },
  { id: 1464, category: "between", content: "우리가 가장 열심히 싸운 이유는?", answerType: "text" },
  { id: 1465, category: "between", content: "나 때문에 가장 많이 웃었던 날은?", answerType: "text" },
  { id: 1466, category: "between", content: "우리가 처음 뽀뽀한 날 기억나?", answerType: "text" },
  { id: 1467, category: "between", content: "나한테 가장 든든했던 순간은?", answerType: "text" },
  { id: 1468, category: "between", content: "우리 기념일 중에 가장 좋았던 건?", answerType: "text" },
  { id: 1469, category: "between", content: "나랑 대화가 가장 잘 통하는 주제는?", answerType: "text" },
  { id: 1470, category: "between", content: "우리 커플링/아이템 중 가장 좋은 건?", answerType: "text" },
  { id: 1471, category: "between", content: "나랑 비 오는 날 같이 한 추억은?", answerType: "text" },
  { id: 1472, category: "between", content: "내가 울 때 어떻게 해주면 좋겠어?", answerType: "text" },
  { id: 1473, category: "between", content: "우리가 같이 못 해본 게 아쉬운 건?", answerType: "text" },
  { id: 1474, category: "between", content: "나한테 서프라이즈 받은 거 중 최고는?", answerType: "text" },
  { id: 1475, category: "between", content: "우리 영상통화 중 가장 웃겼던 때는?", answerType: "text" },
  { id: 1476, category: "between", content: "나랑 같이 먹은 최고의 음식은?", answerType: "text" },
  { id: 1477, category: "between", content: "우리 사이의 성장 포인트가 있다면?", answerType: "text" },
  // --- tmi (15) ---
  { id: 1478, category: "tmi", content: "어릴 때 가장 무서워했던 건 뭐야?", answerType: "text" },
  { id: 1479, category: "tmi", content: "요즘 가장 빠져있는 유튜브 채널은?", answerType: "text" },
  { id: 1480, category: "tmi", content: "인생 최고의 생일 선물은 뭐였어?", answerType: "text" },
  { id: 1481, category: "tmi", content: "가장 좋아하는 계절과 그 이유는?", answerType: "text" },
  { id: 1482, category: "tmi", content: "스트레스 받으면 어떻게 풀어?", answerType: "text" },
  { id: 1483, category: "tmi", content: "가장 기억에 남는 학교 선생님은?", answerType: "text" },
  { id: 1484, category: "tmi", content: "인생에서 가장 용감했던 순간은?", answerType: "text" },
  { id: 1485, category: "tmi", content: "지금까지 받은 최고의 칭찬은?", answerType: "text" },
  { id: 1486, category: "tmi", content: "어릴 때 가장 좋아했던 놀이는?", answerType: "text" },
  { id: 1487, category: "tmi", content: "가장 오래 줄 서본 경험은?", answerType: "text" },
  { id: 1488, category: "tmi", content: "나의 최애 편의점 간식은?", answerType: "text" },
  { id: 1489, category: "tmi", content: "가장 후회되는 머리 스타일은?", answerType: "text" },
  { id: 1490, category: "tmi", content: "나만의 독특한 잠버릇이 있어?", answerType: "text" },
  { id: 1491, category: "tmi", content: "인생 첫 알바 경험이 뭐야?", answerType: "text" },
  { id: 1492, category: "tmi", content: "절대 질리지 않는 노래 하나는?", answerType: "text" },
  // --- future (14) ---
  { id: 1493, category: "future", content: "같이 만들고 싶은 요리가 있어?", answerType: "text" },
  { id: 1494, category: "future", content: "같이 늙어서 꼭 하고 싶은 건?", answerType: "text" },
  { id: 1495, category: "future", content: "우리 거실에 꼭 놓고 싶은 가구는?", answerType: "text" },
  { id: 1496, category: "future", content: "같이 키우고 싶은 식물이 있어?", answerType: "text" },
  { id: 1497, category: "future", content: "우리 결혼 반지는 어떤 게 좋아?", answerType: "text" },
  { id: 1498, category: "future", content: "같이 참여해보고 싶은 봉사활동은?", answerType: "text" },
  { id: 1499, category: "future", content: "우리 주말 루틴을 만든다면?", answerType: "text" },
  { id: 1500, category: "future", content: "같이 달성하고 싶은 저축 목표는?", answerType: "text" },
  { id: 1501, category: "future", content: "우리 아이방을 꾸민다면 어떻게?", answerType: "text" },
  { id: 1502, category: "future", content: "같이 다니고 싶은 동네 단골 가게는?", answerType: "text" },
  { id: 1503, category: "future", content: "우리 크리스마스 전통을 만든다면?", answerType: "text" },
  { id: 1504, category: "future", content: "같이 써보고 싶은 가계부 방식은?", answerType: "text" },
  { id: 1505, category: "future", content: "5년 뒤 우리 연봉은 얼마일 것 같아?", answerType: "text" },
  { id: 1506, category: "future", content: "같이 시작하고 싶은 운동이 있어?", answerType: "text" },
  // --- values (15) ---
  { id: 1507, category: "values", content: "나한테 신뢰란 어떤 의미야?", answerType: "text" },
  { id: 1508, category: "values", content: "나이 들수록 중요해지는 건 뭘까?", answerType: "text" },
  { id: 1509, category: "values", content: "내 인생에서 터닝포인트가 된 사건은?", answerType: "text" },
  { id: 1510, category: "values", content: "후회 없는 삶을 위해 필요한 건?", answerType: "text" },
  { id: 1511, category: "values", content: "배려가 가장 중요한 상황은 언제야?", answerType: "text" },
  { id: 1512, category: "values", content: "돈보다 가치 있는 것 3가지는?", answerType: "text" },
  { id: 1513, category: "values", content: "내가 생각하는 좋은 대화란?", answerType: "text" },
  { id: 1514, category: "values", content: "마음의 평화를 위해 하는 건 뭐야?", answerType: "text" },
  { id: 1515, category: "values", content: "나를 키워준 건 사랑 vs 고난?", answerType: "text" },
  { id: 1516, category: "values", content: "사과할 때 가장 중요한 건 뭘까?", answerType: "text" },
  { id: 1517, category: "values", content: "지금까지 살면서 가장 잘한 선택은?", answerType: "text" },
  { id: 1518, category: "values", content: "나한테 건강이란 어떤 의미야?", answerType: "text" },
  { id: 1519, category: "values", content: "좋은 리더의 조건이 뭐라고 생각해?", answerType: "text" },
  { id: 1520, category: "values", content: "혼자만의 시간이 왜 중요하다고 생각해?", answerType: "text" },
  { id: 1521, category: "values", content: "내가 생각하는 진정한 용기란?", answerType: "text" },
  // --- pet (15) ---
  { id: 1522, category: "pet", content: "밀크가 학교에 다닌다면 좋아하는 과목은?", answerType: "text" },
  { id: 1523, category: "pet", content: "밀크의 MBTI는 뭘 것 같아?", answerType: "text" },
  { id: 1524, category: "pet", content: "밀크에게 옷을 입힌다면 어떤 스타일?", answerType: "text" },
  { id: 1525, category: "pet", content: "밀크가 가장 잘 이해하는 말은?", answerType: "text" },
  { id: 1526, category: "pet", content: "밀크가 좋아하는 간식 순위 매겨봐", answerType: "text" },
  { id: 1527, category: "pet", content: "밀크한테 동생이 생기면 어떨까?", answerType: "text" },
  { id: 1528, category: "pet", content: "밀크가 가장 기뻐하는 순간은?", answerType: "text" },
  { id: 1529, category: "pet", content: "밀크의 하루 일과를 시간표로 만들면?", answerType: "text" },
  { id: 1530, category: "pet", content: "밀크가 우리 말을 다 알아듣는다면?", answerType: "text" },
  { id: 1531, category: "pet", content: "밀크가 가장 무서워하는 건 뭘까?", answerType: "text" },
  { id: 1532, category: "pet", content: "밀크를 한 문장으로 소개한다면?", answerType: "text" },
  { id: 1533, category: "pet", content: "밀크가 영화 주인공이 된다면 장르는?", answerType: "text" },
  { id: 1534, category: "pet", content: "밀크한테 가장 미안한 순간 Top 3?", answerType: "text" },
  { id: 1535, category: "pet", content: "밀크의 베프가 될 동물은 뭘까?", answerType: "text" },
  { id: 1536, category: "pet", content: "밀크가 타 집 댕댕이를 만나면 뭐라 할까?", answerType: "text" },
];
